### ISSUE TITLE
Support OSX 10.9.5

### ISSUE THREAD

**Issue by rafaelverger** [Floris497/mac-pixel-clock-patch-V2#10]
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.9.5 build:13F1603

     otool IOKit: e28bf4715837f534f1fb1e03a5f860b3
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: 1cff5bd867df979766d04afd103acdda
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment]
It seems like this version was never submitted, can you email me the IOKit of your system? with this ```open -a mail /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit``` you can mail it to my paypal email as listed in the readme :) You could also try forcing the patch with version 4 or 5, it's right on the transition.. it might even have a different one..

**Comment by rafaelverger** [comment]
Awesome! I've tried the patch using v4 and it worked flawlessly.. thanks !

**Comment by Floris497** [comment]
Great, can you run MD5 again so i can add everything?

**Comment by rafaelverger** [comment]
Sure :)
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.9.5 build:13F1603

     otool IOKit: 02d46535bc6afb4831db47c5e66535d2
 otool IOKit.bak: e28bf4715837f534f1fb1e03a5f860b3
           IOKit: ccdc329557cf204df1d92c4f33f46876
       IOKit.bak: 1cff5bd867df979766d04afd103acdda

---- ENDING MD5 HASH SUMS -------
```

BTW i just ran this patch for two other colleagues (10.10.2 and 10.11.2) and its all good, thanks a lot and I will do a paypal donation for sure :)

**Comment by Floris497** [comment]
I'm happy it helped you and your colleagues :) thank you!

**Comment by rafaelverger** [comment]
Hey @Floris497 , my monitor is not working anymore :/ I installed the security update 2016-002 and after this the monitor keep showing the message "Out of scale" and do not allow me to access its options' menu :s 
Any thoughts?

**Comment by Floris497** [comment]
Yes, you set the wrong values in switchresx, try resetting NVRAM and such

**Comment by rafaelverger** [comment]
Yeah... it did the trick :) thanks!

**Comment by Floris497** [comment]
Good to hear!
