### ISSUE TITLE
MacBook (12") on Sierra 10.12.2 Public Beta 1

### ISSUE THREAD

**Issue by rdonnelly** [Floris497/mac-pixel-clock-patch-V2#102]
Ran on my MacBook (12") on Sierra 10.12.2 Public Beta 1. Any idea how to get this working? I had previously patched with 10.11 using IOKit, I think.

Thanks!

---

**~/Downloads/mac-pixel-clock-patch-V2-master ./CoreDisplay-patcher.command md5**
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.2 build:16C32f

     otool CoreDisplay: 0657d9fee305e1beeea8ddf0c833d9d5
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: c71c6582dfd10cb0f59b1984c9d2ff11
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

**~/Downloads/mac-pixel-clock-patch-V2-master ./CoreDisplay-patcher.command patch v2**
```
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 2
Password:
Re-singing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
The code is still the same.. Patch did seem to run, but was probbably from the wrong version..
If you are running an new os run ./CoreDisplay-patcher.command md5 and ask the maintainer of this script to add support for your system
```

**Comment by manusajith** [comment]
bumped into same issue after my mac automatically updated.

**Comment by Floris497** [comment]
I don't run beta at the moment.. so I can't find a new patch.. it looks like the code has changed a bit.. maybe the executable makes it to my mailbox somehow.. you never know ;)

**Comment by gothickitty93** [comment]
I am also having this issue with a mid 2012 11" MBA running 10.12.2

**Comment by Floris497** [comment]
Unfortunately I don't have the executable for the beta so I can't do anything.. if only someone by accident would used this command `mail /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay` And by accident put my email adress in there and it would magically appear in my mailbox i would be able to do something.. but what are the odds of that happening 😜

**Comment by gothickitty93** [comment]
I hope I didn't do that by accident...

**Comment by Floris497** [comment]
See updated file :)

**Comment by rdonnelly** [comment]
Thank you! Very much appreciated!

**Comment by Floris497** [comment]
It's working correctly?

**Comment by rdonnelly** [comment]
Yep, worked like a charm!

![screenshot 2016-11-07 21 12 51](https://cloud.githubusercontent.com/assets/563418/20084260/21544178-a52f-11e6-9cff-b7e2ab6be3ae.png)
