### ISSUE TITLE
10.11.4 Support

### ISSUE THREAD

**Issue by Kazom** [Floris497/mac-pixel-clock-patch-V2#11]
Just an open reminder for support for the new update.

**Comment by Floris497** [comment]
I'll update my mac and upload it :)

**Comment by Kazom** [comment]
Awesome thank you so much @Floris497

**Comment by Floris497** [comment]
DL is slow.. apple servers are overwhelmed i think.. do you have  the final version already installed?
if so can you mail me your IOKit? ```open -a mail /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit``` will add the file as an attachment my mail can be found on my Paypal thing :-)

**Comment by Kazom** [comment]
@Floris497 I don't have it downloaded yet :/ I didn't want to risk upgrading and my monitors not work properly.

**Comment by Floris497** [comment]
Oh, this patch will work already :) but not automatically detect the IOKit or Nvidia driver.

**Comment by edderrd** [comment]
Just updated and isn't working for me, only outputs this:

```
IP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.4 build:15E65

     otool IOKit: 769a955b82a16fde0f1ae41eb4bdff7f
 otool IOKit.bak: e70f3a302a6f87190e6d6fe7609cb4b5
           IOKit: 50fef4db03f5680e83c6bbb969e3e85e
       IOKit.bak: 3cec8ae287ee52a3622082bfc049bb86

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment]
This seems correct, the OS update does not delete your old file, the bak file is from 10.11.3 i'm updating in 2 minutes. then i will add what is needed to the script :)

**Comment by Floris497** [comment]
Added 10.11.4 to script

**Comment by kataklops** [comment]
Hi @Floris497 !
I have installed IOKit-patcher but I'm not sure it works.
can you help me
I installed the pacht in Mac Pro early 2008 with nVidia gtx680
I look forward to your help, thank you!

**Comment by kataklops** [comment]
sorry, this is the answer that I get in the terminal:

SIP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G22010

     otool IOKit: 9fead49fe59828405a6489a06335ff0a
 otool IOKit.bak: aee2e3c30a213cf4299497a02da5aa1e
           IOKit: 7c2f57b5446b2121a8a019e82775baaa
       IOKit.bak: b8f9112f6e66ab4d8f74c50340ae8636

---- ENDING MD5 HASH SUMS -------

**Comment by kataklops** [comment]
Hello @Floris497 
Can you help me please?
:-)
