### ISSUE TITLE
which path should I use for MacBook Pro(late 2016)

### ISSUE THREAD

**Issue by tangticco** [Floris497/mac-pixel-clock-patch-V2#112]
I just got the new MacBook Pro(late 2016) with Radeon Pro 450 2048 MB
Intel HD Graphics 530 1536 MB and a LG 4K TV. I used a HDMI 2.0 cable and official Apple AV adapter but the refresh rate is only 24Hz. Which patch should I use?

**Comment by Floris497** [comment]
The USB-C AV adapter also used for macbook 12" does only support resolutions up to 4k@30Hz as far as i know..

**Comment by tangticco** [comment]
I saw on Apple Support that it will support.....disappointing...

> MacBook (Retina, 12-inch, Early 2016) and late-2016 MacBook Pro models support 60Hz refresh rates over HDMI when used with a supported HDMI 2.0 display, an HDMI Premium Certified cable, and a supported USB-C to HDMI 2.0 adapter.

[https://support.apple.com/en-us/HT206587](url)

**Comment by Floris497** [comment]
"a supported USB-C to HDMI 2.0 adapter." The apple AV adapter is most probably HDMI1.4

**Comment by tangticco** [comment]
Oh, really??? WTF?? Do you have any adapter recommendations ?

**Comment by Floris497** [comment]
Any adapter that claims USB-C and HDMI2.0 Club3D CAC-1504 would be a good option i think

**Comment by rdewolff** [comment]
Having the same issue here with the new Macbook Pro, 13", late 2016 and it's Intel Iris Graphics 550.

I have all the component that should be 4K compatible at 60 Hz. But I cannot choose that option. 

My hardware setup is the following : 
- Macbook Pro 13"
- Official Apple USB-C to HDMI adapter. (http://www.apple.com/shop/product/MJ1K2AM/A/usb-c-digital-av-multiport-adapter).
- Inakustik High Speed HDMI 
- Monitor Philips Brillance 288P 4K (Ultra HD 2160p)

@Floris497 @tangticco : the official apple USB-C to HDMI adapter should work on 4K @ 60Hz. See http://www.apple.com/shop/product/MJ1K2AM/A/usb-c-digital-av-multiport-adapter. Or are you talking about another version/device?

@tangticco : do you got your Macbook Pro working on 4K @ 60 Hz now ? If yes, did you use the patch here? If yes, which one.

Any other advice?

**Comment by Floris497** [comment]
"display in up to 1080p at 60Hz or UHD (3840 by 2160) at 30Hz" where do you read 60Hz on 4k?

**Comment by rdewolff** [comment]
Oh damn! You are right. These are not compatible!

**Comment by Floris497** [comment]
Unfortunately they are not no :/

**Comment by rdewolff** [comment]
Aaah Apple, you break my heart!

**Comment by tangticco** [comment]
@rdewolff I have bought the adapter that @Floris497 recommended. Expected to get that tomorrow and I will test that

**Comment by tangticco** [comment]
@Floris497 @rdewolff It works perfect!!!! Thanks @Floris497

**Comment by Floris497** [comment]
Good to know :)

Enjoy!
