### ISSUE TITLE
10.12.2 Beta (16C60b)

### ISSUE THREAD

**Issue by breyer** [Floris497/mac-pixel-clock-patch-V2#115]
fyi: New beta currently not supported.

./CoreDisplay-patcher.command status
SIP looks to be disabled, all good!

Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.2 build:16C60b

     otool CoreDisplay: 8fd4077d823909373d5428add4dc480c
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: 38f158fed9a52b3045914a961c9c034a
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Did you try and force it?

**Comment by breyer** [comment]
./CoreDisplay-patcher.command patch v3
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-singing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
The code of CoreDisplay changed, the patch was probbably succesfull

---> 5min to reboot
