### ISSUE TITLE
MacBook 12" - 10.12.2 - issues executing Core Patch

### ISSUE THREAD

**Issue by xerox88** [Floris497/mac-pixel-clock-patch-V2#118]
I have some issues after executing the script:

Downloads/CoreDisplay-patcher.command: line 5: syntax error near unexpected token `newline'
/Downloads/CoreDisplay-patcher.command: line 5: `<!DOCTYPE html>'

Any idea?

**Comment by Floris497** [comment]
Maybe you downloaded the HTML page? That's mostly the cause of this type of error. Would suggest you to download the zip :)

**Comment by xerox88** [comment]
You´re right. The guy in front of the screen is the idiot :-)
