### ISSUE TITLE
Mac mini (late 2012) md5 update

### ISSUE THREAD

**Issue by andreisabau** [Floris497/mac-pixel-clock-patch-V2#119]
Hello, can you please add the following hashes? Thanks!

---- BEGINNING MD5 HASH SUMS ---- version: 10.12.1 build:16B2555

     otool IOKit: 4c8ae5fc02ae81d525490d3c13296101
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: 75f158db68b20861dd1eaebdf6fdcb8d
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
So IOKit is still working?

**Comment by andreisabau** [comment]
Sorry, somehow I skipped the "10.12 and up please use the CoreDisplay" part.
CoreDisplay patch is giving me:
Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.1 build:16B2555

     otool CoreDisplay: 127c930ff200a296e8d890c43863dbb2
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: b38bbe5c6fbde7892e3ee8af78737d50
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Please try and force v2 :)

**Comment by andreisabau** [comment]
Now the 3840x2160 resolution appears in the list, but when I select it the TV doesn't receive any signal over HDMI.

**Comment by Floris497** [comment]
Are you trying to set 4k@60Hz? What cable do you use?

**Comment by andreisabau** [comment]
No, I tried with 24Hz, 25Hz and 30Hz and used some generic cables, 3 of them. None work with the Mac mini but they work fine with my MBP set to 4K@60Hz.

**Comment by andreisabau** [comment]
I reinstalled macOS Sierra 10.12.2 to have a clean os on my system which is a Mac mini (late 2012), 2.5GHz Core i5, 16GB ram and Intel HD Graphics 4000 with 1536 MB of VRAM.

Then I tried again patching with v2, patch didn't apply, I received the message with "the code is still the same.. ".
Then patched with v3 and the patch was applied successfully but I still have the same issue.
No more signal coming out of the HDMI port on any resolution (3840x2160 or 1920x1080) with any refresh rate.
Any suggestion on what I should do?

**Comment by Floris497** [comment]
Try to open a remote connection and try to play with the settings a bit.. I think I remember mac mini 2012 has some framebuffer limitations.. those are not easy to fix.. I'll have a better answer for you tomorrow. If still needed by then :)

**Comment by andreisabau** [comment]
Already did that, I'm in front of the TV to which the Mac mini is connected and I'm controlling it through Screen sharing. Tried out all the possible combinations of resolutions and refresh rates but none work with the v3 patch. No signal comes out of the HDMI, if I remove the patch it work normally after a restart.

**Comment by pritpal** [comment]
I'm in the same boat, I got Mac mini (Late 2012).. I can see the 2560x1440 resolution but when I select it.. monitor is not receiving any signal. I even reinstalled macOS Sierra 10.2.2 and tried again but same thing. Please help me, Thank you.

**Comment by shakeebr** [comment]
Hello,

Having the same issue as @andreisabau and @pritpal. Mac mini (late 2012) -- applied v3, and getting a black screen via HDMI when running any 4k resolution.  Any ideas, @Floris497 ?

Thanks!

**Comment by andsimakov** [comment]
Have same issue with v3 on MD388.

**Comment by Floris497** [comment]
What framerate?

**Comment by andsimakov** [comment]
I don't have more than 20...x1080px via hdmi at all. One more strange thing, seems aspect ratio after recent firmware update is not 16:9. At least Mini sees the display via hdmi in that way. :(

**Comment by Floris497** [comment]
I have no idea now.. write here again at 3rd of January and I'll look at it again :)
