### ISSUE TITLE
10.11.4 + Nvidia web driver + patch-V2 boots to black screen.

### ISSUE THREAD

**Issue by kenmadsen** [Floris497/mac-pixel-clock-patch-V2#12]
Hi it appears after applying the patch-v2 on mac os 10.11.4 with the nv web driver working and everything. My system now boots into blank screens. Much like the way the nvidia drivers boot until the AppleGraphicsDevicePolicy.kext is changed.

patching using the IOKit patch went fine according to the terminal output..

**Comment by Floris497** [comment]
This script does not patch NVidia web driver.. Did you update to the latest Nvidia driver? Try booting with cmd+v and see if there is something interesting going on..

**Comment by kenmadsen** [comment]
Will be closing this issue, after some sleep, a mountain of coffee, 100 reboots and fixes I'm not even sure what does, its all functioning now :)

**Comment by Floris497** [comment]
If you discover what did fix it, relevant to this script or not. I'm interested to know :). Good it works now!
