### ISSUE TITLE
Support for 10.9.5 build 13F1911

### ISSUE THREAD

**Issue by newperson1746** [Floris497/mac-pixel-clock-patch-V2#124]
Hello,

With 14F1911 (Security update 2016-004) I can't get it to work.
As expected I receive the message "Unknown version of IOKit found"

Here is the output of IOKit-patcher.command md5:

```
---- BEGINNING MD5 HASH SUMS ---- version: 10.9.5 build:13F1911

     otool IOKit: e28bf4715837f534f1fb1e03a5f860b3
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: 1cff5bd867df979766d04afd103acdda
       IOKit.bak: NO FILE (this is okay)

```
Thank you.

**Comment by d3funkt** [comment]
You could try to force the 10.9.4 patch:

`IOKit-patcher.command patch v4`

v4 is the patch for 10.9.4 so it may work for you.

To revert to stock:

`IOKit-patcher.command unpatch`

**Comment by Floris497** [comment]
Did this work? can I close the issue?

**Comment by newperson1746** [comment]
Yes, it did work. Thank you
