### ISSUE TITLE
mac mini 2014 MGEM2 with LG 27UD68

### ISSUE THREAD

**Issue by dennygun** [Floris497/mac-pixel-clock-patch-V2#129]
I have successfully install using this patch, my connection using mini thunderbolt to hdmi adapter.
And the LG deep color has to be on, to achieve 60hz. 
However when the screen goes to sleep, it stays black until I turn off the lg deep color (this way only 30hz working), and later when I turn it back on, i got 60 hz working again.

Sometimes when turning on for the first time also having this kind of problem. I have to turn off the lg deep color, later again, turn it on.

I hope patch V3 will fix this problem, thx.

**Comment by Floris497** [comment]
Unfortunately this patch doesn't fix this kind of problem. Also I'm not quite sure what causes it. But I can say that the locks we remove are there for a reason :)
