### ISSUE TITLE
Unknown version of the nvidia driver found..

### ISSUE THREAD

**Issue by TheLynxDr** [Floris497/mac-pixel-clock-patch-V2#13]
After installing 10.11.4 update. the resolution went back to 1920x1080 and the patch gives me this:

```
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading

Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.4 build:15E65

     NVDAGK100Hal: 840234288d56c2171e75083dfdd6b1d9
 NVDAGK100Hal.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment]
That is correct, i have not had the time to update nvidia, you might just force the patch.. I'll look into it in an hour or 2. So waiting is also an option if you don't feel like forcing it :)

**Comment by TheLynxDr** [comment]
I installed that IOKit and ran the script again.. After the restart it still didn't work. 

Later i needed to visit Windows and when i got back to OS X the native resolution appeared to the display settings.. I may have missed it the first time, but now it's working again. :D

Keep up the great work! <3
