### ISSUE TITLE
100% CPU usage 10.12.2 MBP 13" 2016 with RDM

### ISSUE THREAD

**Issue by majuss** [Floris497/mac-pixel-clock-patch-V2#136]
After patching the CoreDisplay, the icdd is using 100% CPU power when I plug in an external screen and set my internal resolution with RDM to 2560x1600. This renders the patch useless for me :(

**Comment by Floris497** [comment]
I have little idea why this is happening, why not disconnect the screen when remote desktop?

**Comment by majuss** [comment]
RDM ≠ Remote Desktop Management
RDM -> https://github.com/avibrazil/RDM

Sorry should have added the link to the issue.

**Comment by Floris497** [comment]
Ah, please use switchresx :D in my opinion that one is far superior :)

**Comment by majuss** [comment]
After investigating I found out that it's not related to any program but macOS itself... The iccd is the image capturing deamon and its going nuts if a VGA display is attached via USB-C. The 2016er MBP has so much bugs with external displays its really sad : /

**Comment by Floris497** [comment]
Uhg.. I hope this will be fixed for you in a future release of macOS.
