### ISSUE TITLE
10.12.3 support

### ISSUE THREAD

**Issue by metzc** [Floris497/mac-pixel-clock-patch-V2#138]
I tried to re-apply the patch after 10.12.3 update. I need the patch for my dual monitor setup - doesn't seem to work for me anymore.

**Comment by metzc** [comment]
never mind, running AGDPfix restored the dual monitor setup. Possible that I also used that before the update in combination with the pixel-clock-patch.

**Comment by diafebus** [comment]
I confirm this works on 12.3!
