### ISSUE TITLE
10.11.4laptop IOKit md5 50fef4db03f5680e83c6bbb969e3e85e

### ISSUE THREAD

**Issue by 0x2c0d** [Floris497/mac-pixel-clock-patch-V2#14]
hi, i just install 
10.11.4 release version to my laptop 
I run the  "md5 -q "  /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
it return 
 50fef4db03f5680e83c6bbb969e3e85e

It seems can not patch with this script ?

thank you .

after fresh reinstall.

it shows 

---- BEGINNING MD5 HASH SUMS ---- version: 10.11.4 build:15E65

     otool IOKit: 637f064f5d76492f7ac5479e6554caa6
 otool IOKit.bak: 637f064f5d76492f7ac5479e6554caa6
           IOKit: b3904b21b423857a2821ff241cc10475
       IOKit.bak: 239d4c19c927f333b58257776e406a21

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Can you try the script with ```script.command md5``` and post all the md5 signatures :)

**Comment by legotheboss** [comment]
Have you disabled SIP before running the script?
