### ISSUE TITLE
10.12.4 support

### ISSUE THREAD

**Issue by Jani4ik** [Floris497/mac-pixel-clock-patch-V2#158]
After the update on 10.12.4, the patch stopped working.
![1490686581196](https://cloud.githubusercontent.com/assets/13448816/24393847/6c8c0d9c-13a2-11e7-84c6-109c6482879e.jpg)
I ask to help to solve this problem.
Thank you!

**Comment by Floris497** [comment]
It's updated now :) someone was quick with the update today!

**Comment by Jani4ik** [comment]
Many thanks, earned! 🥇

**Comment by Floris497** [comment]
Thank @farkasseb this time someone was before me :p
