### ISSUE TITLE
My computer is restarting after screen goes to sleep

### ISSUE THREAD

**Issue by diafebus** [Floris497/mac-pixel-clock-patch-V2#16]
Hi! Your command lines made my system get the right resolution 2560x1440, I was desperate, but I seem to have the same problem as using this other version of fix: https://github.com/toleda/graphics_Intel_framebuffers

Do you know if that problem is from clover or from the patch? Whenever i let my computer screen go to sleep, as soon as I wake it up it restarts, it doesn't happen with DVI, I'm on HDMI right now, I can't use DVI because for some reason the cable seems to be broken and I can't get more than 1080 because te dual link of it seems to not work, I don't know if its because of the cable, the PC output or the screen input… and I have no way to check it. 

I already had to cut the computer for sleeping… at least I'd like to be able to switch off the screen…

Thank you!

**Comment by Floris497** [comment]
Surprisingly i have never had a hackintosh or any experience with it. But I know a few things. Because a lot of what i try can be accomplished with hackintosh software :)

Most systems will not support sleep, that has nothing do do with whatever screen you use

Make sure you are using dual link dvi, it is certainly possible that you display cannot receive 1440p over the DVI connection. But can overcome DisplayPort or HDMI, you can try with a different pc or windows.

What kind if HD graphics do you have? 4600? I know it works for people, but not support on mac by default.

The framebuffer thing is interesting, I'll look into that.. The last script I used to edit it broke for an unknown reason to me.. And i have no time finding a fix.. But it should even be able to make 4k possible on some macs that have totally no way of getting it with my IOKit patch.. While older machines do. 

Not sure if this answers your question.

If you want to know more please let me know, maybe i can help you

**Comment by diafebus** [comment]
thanks for such a fast reply! Well my DVI cable seems to be broken… when I plug it, it show dual link is not working properly, and on windows it can only display 1920x1080, on mac displayed the correct resolution but it was giving me that dual link error on the screen all the time. Over HDMI your patch works great except I can't put the screen to sleep, if you could help me fix that issue, that would be great… Yes I'm using HD4600, and I also used your IOKit patch.  Using an nvidia graphics card I had no such problems, but I'm selling it because I'll be upgrading this June when the new ones come out hehe So this would be a temporary solution… I guess I could live a couple of months with no screen sleep.

**Comment by Floris497** [comment]
Hm, that is interesting, so no problem with HDMI? Can you try and see if you have this problem with hdmi and this patch not applied? 

The DVI cable might not even have the wiring fro dual link, look it op on the inthernet, but a gap in the middle if the pins point that out. It should be all pins and 4 pins or a dach at the side. (Side can be bit different tho)

Why not used the nvidia gpu then?

**Comment by diafebus** [comment]
With this patch not applied HDMI will only show up to 1920x1080… I have no clue on why. The DVI cable has the wiring because it worked in the past, and its from the ASUS screen I have, it came with it, so it's a legit dual link DVI cable ;)

Well as I explained I'm planning on sell it as soon as possible to not let the price go down too much before new nvidia series comes out haha, that's why I'd like the screen fixed now :) It almost works good, is just that, hotplugging HDMI makes shit crash, and DVI or cable is wrong or I don't get it… with the patches of the link I put on top It made DVI display 2560x1440 on OSX with that error showing on the screen, but the resolution was correct, but then when I use windows I can't get it to display 2560x1440 because it won't ignore the error… it is indeed very strange hahaha so fixing HDMI seems the easy one… or buying a new cable but good quality DVI cables are expensive, and to use it for 1 or 2 months is not worth it.

Thanks again

**Comment by Floris497** [comment]
Doubt it's the cable.. I cannot imagine it's te patch.. Did you try switchresx without my patch? Maybe that works? Else I need to think really hard what can be wrong..

**Comment by diafebus** [comment]
Well using a tester on the DVI cable http://www.alciro.org/images/alciro/586_conexion-patillas-conector-DVI.png
Pin 24 and C5 are not giving me continuity, the other 23 pins give me continuity… and 24 being a clock, could be the reason why dual link is not working with the cable… I should get another cable just to be sure. I'll try to borrow one from any friend and see if that could fix my issue 💃  👍 

Thanks again

**Comment by alex88** [comment]
@Floris497 not sure if it's something related but in my case after waking up from blank screen (the screen turns off, pc doesn't go to sleep) the screen is black and I just see the mouse cursor (and a couple times some artifacts like flashing green lines).

This happens randomly and starter right after I added your patch.

**Comment by diafebus** [comment]
Hey one question, is it possible to create a 2560x1440 at 59Hz instead of 60Hz? Because my screen seems to not be cool with 60Hz it prefers 59,9something and everytime my display goes on I see an error message but the resolution displayed thanks to your patch is correct… I'd just need to add this 59Hz instead of 60 and I think it all would be fine… Thanks!

**Comment by Floris497** [comment]
Use switchresx
