### ISSUE TITLE
privacy

### ISSUE THREAD

**Issue by wuya2357** [Floris497/mac-pixel-clock-patch-V2#164]
privacy

**Comment by wuya2357** [comment]
terminal output show it use patch v3.not work

**Comment by wuya2357** [comment]
i use switchresx.
with hdmi,it can only work on 2560 * 1440(no hidpi) at 60hz.

**Comment by wuya2357** [comment]
the dp1.2 to hdmi2.0 adapter works in windows10 (4k 60hz)
with or without adapter,both works alright(4k 60hz) in windows10.

**Comment by wuya2357** [comment]
for guys intresting.i use cy dp active adapter.
there's cheap dp1.2 to hdmi2.0 active adapter in chinese taobao.about 60rmb.
i'm sure it works 4k60hz.i test it in windows10.

**Comment by wuya2357** [comment]
i find other people have same issue.
in comments of http://osxdaily.com/2017/03/27/macos-sierra-10-12-4-download-update/.

**Comment by Floris497** [comment]
Unfortunately I'm far far away from home without any pc near me.. maybe I'll be able to remote into home later this week and check it out :) but there's little i can help you guys with right now

**Comment by wuya2357** [comment]
thx.more info.
with your v3 patch,i can use switchresx to set 1280*720(hi_dpi).
without patch,it seems monitor can't be set to 1280*720(hi_dpi).
with or without,both can use 2560 * 1440.

and when i use patch,the monitor blink time is very short.
without patch,when i change monitor resolution,it blink for 1-3 seconds.

**Comment by Floris497** [comment]
Please wait for 77+ series driver from nvidia :) they are realeasing new drivers soon that support upto pascal cards (latest on market) ar where right now they only support up to 600 series cards officialy

**Comment by battler2** [comment]
Hi Floris, Hope you're enjoying your holiday. Nvidia just released the pascal drivers which I had long been waiting for in the hope that it would enable 60hz at 4k, as previously I was using my CPU graphics and was limited to 24hz (intel cpu)). I tried your patch with 10.12.4 final but it is limited to 30hz. Tried making a custom res and refresh rate with switchresX with no success. I think Apple might have removed this support, so I'm not sure if you are able to fix it. I'm not sure how many people use 4k, I use the retina mode of 4k so 1080, but this needs 4k at 60hz to work smoothly. If you could take a look at this when you get back that would be great. Thnx.

**Comment by Floris497** [comment]
Yes drivers have been released :) what patch are you using? What kind of cable what monitor?

**Comment by Erhesar** [comment]
Hello! For now i'm using 2 dell u2415 monitors (1920x1200) via DisplayPort and samsung 4k tv as third monitor via hdmi on my gtx 1080, all works brilliant, but tv is only 30Hz refresh rate. Have no results in making 60hz. Sierra 10.12.14.

**Comment by Floris497** [comment]
Does your TV support full 4K60Hz over HDMI2.0? Then make sure you also use the correct port on the TV where mostly only 1 or 2 ports support it.. I'm back from holidays in about a week and wil happily try my own 1080 :) but i have no idea for how far it works like the 900 series cards. (I assume you mean 10.12.4?)

**Comment by Erhesar** [comment]
Yeap, tv support it, because when i loading win10 system from second ssd - it works on 60hz.

**Comment by Floris497** [comment]
It could be windows is tricking 60Hz by using half the amount if color bits (4:2:0 YUV instead of 4:4:4 RGB) but I can't tell you now because I can't really access my mac right now :)

**Comment by crossfuture** [comment]
Hello @Floris497 ,
I have a GTX970, with JVC 50T TV, which can support HDMI 2.0, but only YUV420 @4K60Hz
It works fine on Windows @4K60Hz, but how about Mac? With CoreDisplay patch, can Mac output YUV420@4K60Hz?

Because I tried CoreDisplay patch with 10.12.3 or 10.12.4 with HDMI output, it never worked for me
Every time I just get black screen, so I just wondering is it the YUV420 problem?

**Comment by Floris497** [comment]
I think outputting YUV 4:2:0 isn't something macOS likes to do..

**Comment by mastersdk** [comment]
Hi, have the same issue.. have a Samsung 40" 4K UHD Smart TV UE40KU6075 that works great on Windows 10 but with Sierra I can only get it to do 30hz...

Did any of you find a solution for this?

Thx

**Comment by mastersdk** [comment]
Apple is saying that 60hz is supported over DisplayPort - will it work with a adapter from display to HDMI 4k port ?

https://support.apple.com/en-gb/HT206587

**Comment by mastersdk** [comment]
Anybody that know if this works ?
https://9to5mac.com/2016/06/04/how-to-enable-4k-60hz-resolution-2016-macbook/

**Comment by Floris497** [comment]
What mac do you have? And what cable do you use?

**Comment by mastersdk** [comment]
Its a hackintosh:

Nvidia GeForce GTX 1080 Armor 8G OC Edition
Intel Core i7-6700K CPU
MSI Nightblade X2-254EU

**Comment by Floris497** [comment]
So.. for some reason I could not get my 1080 to do 4k@60Hz over HDMI, now recently I've updated the patch for NVIDIA to support the pascal web drivers. I don't really feel like putting my rig downstair where the TV is to test it.. but if you want to test I'll give you the command. but first update to 10.12.5 (pascal driver has been updated for this) and I'll patch the new Nvidia driver :) see if that helps

**Comment by mastersdk** [comment]
ok, will have do the update to 10.12.5 and yes please let me have the command :-)

**Comment by Floris497** [comment]
```sudo perl -i.bak -pe '$oldLimit1 = qr"\x8B\x82\xB0\x00\x00\x00\xB9\x88\x84\x02\x00"s;$newLimit1 = "\x8B\x82\xB0\x00\x00\x00\xB9\x00\x35\x0C\x00";s/$oldLimit1/$newLimit1/g' $NVDALocation
      sudo touch /System/Library/Extensions```

**Comment by Floris497** [comment]
You might have to use it in combination with the CoreDisplay patch.. did you get anything to work?

**Comment by mastersdk** [comment]
still looking on updating to 10.12.05 (like to keep .04) and try this: https://github.com/Floris497/mac-pixel-clock-patch-V2

will that work on a hackintosh ?

**Comment by mastersdk** [comment]
see another post from you here: https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/76 where it seems liked you fix it ?

> All I did was what dockdude did:

Install Xcode from the terminal with xcode-select --install (for those who didn't)
Disabled SIP with clover boot Rt-variables
To disable or enable SIP add the settings to your config.plist.
Clover Configurator > Rt Variables > BooterConfig and CsrActiveConfig

Relevant user options for SIP are as follows:
csr-active-config 0x0 = SIP Enabled (Default)
csr-active-config 0x3 = SIP Partially Disabled (Loads unsigned kexts)
csr-active-config 0x67 = SIP Disabled completely
use chmod +x to make the patches executable, and run first the new IOKit-patcher.command, then CoreDisplay-patcher.command.
reboot
BAM! all systems functional.
Thank you again, and godspeed! Let me know your paypal link too.

**Comment by Floris497** [comment]
Same code as I just put there will work on 10.12.4 but the driver for 10.12.5 is updated, so chance is that they fixed something with HDMI2.0 for now it even looks like DP MST does not work properly.. only SST so my MST monitors run at 30Hz

**Comment by mastersdk** [comment]
sorry you are confusing me :-) in #76 it seems like it will push UHD 4k by HDIM in 3440x1440 in 60hz.. but are you now saying it will only do 30hz..? :-)

**Comment by Floris497** [comment]
Sorry to confuse you.. it should be able to do this.. currently my self and some others report that the 10 series nvidia cards don't deliver 4k@60Hz over HDMI2.0 this is a driver issue for sure as the 900 series cards can do this when CoreDisplay is patched. I myself have not tested this for 10.12.5 drivers from nvidia. Also (Multi Stream Transport) does not seem to work properly for me now.. please try with the both patched CoreDisplays from the script and nvidia driver with the commands I just put here.

**Comment by mastersdk** [comment]
Just run this: sudo perl -i.bak -pe '$oldLimit1 = qr"\x8B\x82\xB0\x00\x00\x00\xB9\x88\x84\x02\x00"s;$newLimit1 = "\x8B\x82\xB0\x00\x00\x00\xB9\x00\x35\x0C\x00";s/$oldLimit1/$newLimit1/g' /System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb
sudo touch /System/Library/Extensions

**Comment by Floris497** [comment]
Yes 😊

**Comment by mastersdk** [comment]
did not see any change it just ask for the password and then: MSIs-iMac:~ msi$

**Comment by Floris497** [comment]
Correct

**Comment by mastersdk** [comment]
so after reboot I maybe work ?

**Comment by Floris497** [comment]
Wait.. I'll give you a wat to check if it was correctly patched 2 sec

**Comment by Floris497** [comment]
```
md5 /System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb*
```

If both signatures are different you are fine:

mine reports this but since you are on older drivers that will not be the same as mine:
```
MD5 (/System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb) = 096a081347024086efa8d396d814afd0
MD5 (/System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb.bak) = cbe4cf2687f7828c64a1698a910ae124
```

**Comment by mastersdk** [comment]
got this back: 

> MD5 (/System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb) = f0b8c545e5b5f684173c25d32517fdf0
> MD5 (/System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb.bak) = 0ee0407775db6da70015dbcc75780e66

**Comment by Floris497** [comment]
Looks to be fine, reboot and see if that changed anything

**Comment by mastersdk** [comment]
it seems liked it worked - THANKS FOR THE HELP, YOUR THE BEST :-)

![floris497 is the best](https://cloud.githubusercontent.com/assets/28774421/26204473/28a49544-3bdf-11e7-8496-331bb48cc794.jpg)

**Comment by Floris497** [comment]
Would you like to test something for me? could you unpatch CoreDisplay and see if it's still working?

**Comment by mastersdk** [comment]
Hi, have just removed macOS as I had to many issues under booting and programs not working.. needed to use the PC for work, so have to be sure my setup is stable... so need to work a bit more on it, but when I get it backup I will let you know... again thanks for the help..

**Comment by Floris497** [comment]
No problem, at least we know it works :D

**Comment by c-man90** [comment]
I followed all the steps on here and I cannot get my GTX 1080 over HDMI or DP to HDMI adaptor to do 60hz. Only showing 30hz option. My MD5 is showing both the same tho?

`MD5 (/System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb) = 096a081347024086efa8d396d814afd0
MD5 (/System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb.bak) = 096a081347024086efa8d396d814afd0`

**Comment by wuya2357** [comment]
hi,i'm sorry i can't tell wether the new version works or not.
for job need,i update my pc totaly in a hurry.only dp now.
wish all of you success on 4k60hz hdmi.

**Comment by Floris497** [comment]
HDMI seems to he broken on 900 and 10 series cards.. not sure who is to blame.. and no time really to look into it
