### ISSUE TITLE
10.12.4 gtx650 hdmi2.0 4k60hz - not work

### ISSUE THREAD

**Issue by imKota** [Floris497/mac-pixel-clock-patch-V2#167]
Hello!
MacOS 10.12.4
i use gtx650, UHD Smart TV (hdmi v 2.0), hdmi cable v2.0, 4k in 60hz not work. only 30hz (CoreDisplay patch v3) http://take.ms/CKbpf

On windows 7, hdmi 4k in 60hz works.

**Comment by Floris497** [comment]
Windows tricks you with 4:2:0 colors instead of full RGB 4:4:4 so no way 650 can do it on a mac with HDMI :D

**Comment by imKota** [comment]
> 650 can do it on a mac with HDMI

Ned new video card?

**Comment by imKota** [comment]
Maybe all the same there is a way?

**Comment by Floris497** [comment]
Does your 650 have displayport? Else ehm.. i think it's impossible on mac.. but also look at what your screen takes as an input

**Comment by imKota** [comment]
only DVI or HDMI
On windows^
![default](https://cloud.githubusercontent.com/assets/24241471/25100089/83f71876-23b7-11e7-80b0-1c71a1f42a54.png)

**Comment by Floris497** [comment]
Yes it says YCbCr420 (Aka YUV 4:2:0) for the moment it's nit really possible to use this on mac.. I just didn't put that much research into that. Maybe it's possible to trigger by EDID edits. But don't expect anything soon :) not from me the coming 4 months i have a shitload of other stuff to do :)

**Comment by imKota** [comment]
@Floris497 What video card do you recommend to buy? Not very expensive, but to handle 4k
