### ISSUE TITLE
Can't run 4k @ 60hz on ASUS PA328Q (32 " 4K Ultra HD ProArt Professional Monitor)

### ISSUE THREAD

**Issue by lukeknep** [Floris497/mac-pixel-clock-patch-V2#169]
I have a 13" MBP (2016, touchbar, four thunderbolt ports) with Intel Iris 550 running 10.12.2.

I installed IOKit Patcher v7 first, and then CoreDisplay patcher. Unfortunately my ASUS PA328Q is still running 4k at 30hz over a USBC to Display Port cable (the monitor is set on Thunderbolt 1.2)

Unless there's some additional step to set the monitor to run at 60hz after I've installed the patch, it sadly doesn't seem to work.

Thanks for all the hard work!

**Comment by Floris497** [comment]
Use CoreDisplay patch as states in readme for 10.12+ :) but I'm under the impression that a 2016 mac should not need any patch..

**Comment by lukeknep** [comment]
@Floris497 thanks. You don't think it needs a patch? I thought that it's widely known that the new MBPs don't support 4k@60hz natively? (only 4k@30hz)
at least according to this article (which is how I found your awesome repo)
https://9to5mac.com/2016/06/04/how-to-enable-4k-60hz-resolution-2016-macbook/

**Comment by Floris497** [comment]
That's a normal macbook not a MacBook Pro..

**Comment by lukeknep** [comment]
@Floris497 Ah. My bad. Thanks!

**Comment by Floris497** [comment]
Let me know if you get it to work properly :)

**Comment by lukeknep** [comment]
@Floris497 Thanks, it works now! I'm not sure what I was doing wrong at first. Probably some sequence of unplug-reboot-replug that I didn't quite get right.

Can confirm that I'm driving 3840 x 2160 @ 60 Hz (4k) on a ASUS PA328Q with a 2016 MacBook Pro with Touchbar through a USBC to Display Port cable.

**Comment by Floris497** [comment]
Enjoy it! So without patch right?

**Comment by lukeknep** [comment]
@Floris497 I think the patch did in fact enable it, but I'm not 100% sure.
