### ISSUE TITLE
Signal cutout and strange pixel snow

### ISSUE THREAD

**Issue by punziecam** [Floris497/mac-pixel-clock-patch-V2#17]
Used V2 on OSX 10.11.4 for a 55-inch Bravia XD93

I can see 3840x2160 @30hz (but not 60hz) but the signal via mini-DisplayPort on MacBookPro Retina (Early 2015) to the TV screen cuts out occasionally (I could not determine a pattern) and when the image is up I see faint/minor pixel snow (like the GPU is stressed on overclock).

Not sure what is up with it... I didn't want to risk burning my laptop or TV so I went back to HDMI-HDMI until this issue can resolved.

The hash of IOKit was e2324202132be7b0839b1b2f8357e739

**Comment by Floris497** [comment]
Does the screen support displayport? I've never heard anyone about this problem.. Your MacBook should be able to do it without the patch.. Use only switchresx.

**Comment by punziecam** [comment]
HDMI only. Everything works fine MacBook-HDMI to TV-HDMI at 3840x2160@30hz (never seen 60hz) and works flawlessly. The DisplayPort, with patch allows a strange 3360x2100 but not 3840x2160, doesn't behave so well. I removed the patched IOKit to the original and tried using SwitchResX but I get almost same result if not worse - no 3840x2160 output, only 1080p.

I kind of want to give up on it now... I had hopes that outputting mDP->HDMI would be great but it doesn't seem to be getting me anywhere.

**Comment by Floris497** [comment]
I would advise a mDP to HDMI2.0 cable, of your tv dies 60Hz over hdmi that would work.. 4k should just work out of the box on your mac..

**Comment by punziecam** [comment]
Yeah 4k works out of the box but via HDMI only. Referencing https://support.apple.com/en-gb/HT202856 shows that external 4k (TV) is only supported via HDMI. Single-Stream (SST) doesn't seem to apply to UHD TVs, but desktop monitors. Even if mDP-to-HDMI does work, without V2 patch OSX allows only very limited resolution options. Patched, works but not as great as HDMI-to-HDMI. SwitchResX would be good I suppose, but I can't get 3840x2160 listed on the display output.

I am thinking either; (a) The TV doesn't like the mDP signal. (b) The mDP cable I have isn't great itself and is causing the problem. (c) My MBP-Retina just can't handle outputting that resolution/refresh via mDP.

**Comment by Floris497** [comment]
mDP is fine, as long as you have a good cable. My macmini 2011 does 4k@40Hz on a hd3000

Make a custom resolution in switchresx that is what you use it for :) and make sure your mDP is not to long.

**Comment by punziecam** [comment]
Okay I did exactly as you said. I created a custom setting for 4k@40hz but it doesn't show up in the list (attached screenshot). Also this is the cable I am using: http://www.amazon.co.uk/REALMAX%C2%AE-Display-Thunderbolt-Macbook-Microsoft/dp/B015GGUHGO
![2016-04-18 at 02 03 09](https://cloud.githubusercontent.com/assets/17160043/14591476/f7d81074-0509-11e6-98b4-97aeb064ca37.jpg)

**Comment by punziecam** [comment]
And after the reboot, the custom setting status says "Not activated - invalid?". I tried a lower refresh rate, and lower pixel clock but something is preventing the setting from activating. I tried also the simplified settings too. I am scanning the madrau community for similar issues after reboot.

**Comment by Floris497** [comment]
That is why you need the IOKit patch. Do you have dedicated graphics? Then you also need the Nvidia patch.

**Comment by Floris497** [comment]
But the thing is, i do not understand why you need the patch on a 2015 macbook pro.. This machine should support 4k.. Your tv should be able to do 25Hz 30Hz 50Hz and 60Hz. Also sometimes you need to disable a lot of tv settings to make the image look good because tv's tend to do a whole lot of image adjustments. Which gives a big delay and weird colors.

**Comment by punziecam** [comment]
Oh I see... I need to patch. I'll do that when I get home. Yeah TV seems to get what I want to do with my other machines and doesn't give me much hassle (much). Really, thank you for your patience and responding every time! You're awesome!! 💃

**Comment by Floris497** [comment]
No problem :) try it and let me know it that works!

**Comment by punziecam** [comment]
It didn't work with patched IOKit, mDP, SwitchResX(custom:3840x2160@anything). I tried 60hz, 40hz, 30hz. I tried alternating simplified modes also as that seems to slightly adjust the pixel clock - nothing output. Boo!

**Comment by Floris497** [comment]
Should just work.. I don't get it.. Last option would be better cable. Your DP to HDMI does not support that resolution then.. Club3D has a mDP to HDMI2.0 cable.. But it's expensive like 50 euro.. I thought you said your display had DP input..

**Comment by punziecam** [comment]
Okay, I'll have a look. No TV only has HDMI input. Which is why I have mDP-to-HDMI cable.

**Comment by Floris497** [comment]
What was the problem with using HDMI then?

**Comment by punziecam** [comment]
HDMI-to-HDMI has a 30hz cap, it's what I am using at the moment. I was hoping to open up 60hz with mDP, which is why I started experimenting with your solutions.

**Comment by Floris497** [comment]
Oooh.. So HDMI on mac can go to 4k@30Hz.. That is a hardware limit. mDP can go to 60Hz, but, you need an andapter that can handle HDMI2.0 and there is to my knowledge only 1 available. You will probably still need the IOKit patch to enable the higher pixel clock for the HDMI2.0 on the adapter.
