### ISSUE TITLE
MBP 2014 Mid 4k@60hz does not work

### ISSUE THREAD

**Issue by karek314** [Floris497/mac-pixel-clock-patch-V2#170]
Hi,
Good work with this tool.

However it didn't worked for me yet.
MacBook Pro (Retina, 15-inch, Mid 2014)
macOS Sierra 10.12.4 (16E195)

What i did:
-diasbled sip
-restarted
-executed `CoreDisplay-patcher.command` with positive result.
```
 ./CoreDisplay-patcher.command
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12.4 16E195.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
Closing..
```
-rebooted again into recovery, enabled sip
-rebooted

Didn't worked, still can't use 60hz, still System Preferences > Display forces 30hz.
Display is 4k, fully supporting 60hz - works fine with other computer window based.

After noticing that it didn't applied so i have repeated process
```
./CoreDisplay-patcher.command
SIP looks to be disabled, all good!
(otool) Detected patched CoreDisplay on OS X 10.12.4 16E195.
```

Any hints ?

If that matters using HDMI output, not thunderbolt nor usb-c.

**Comment by Floris497** [comment]
Depending on the version of HDMI this can be the bottleneck.. so what cable/port are you using?

**Comment by Floris497** [comment]
And have you tried anything with Switchresx?

**Comment by karek314** [comment]
HDMI cable, even the one advertised as with 4k support. As output i have been using build in HDMI port in MBP mid 2014. Display i have support HDMI & Display Port both with 4k@60hz.

Checking Switchresx now.

**Comment by Floris497** [comment]
Well but what port are you using? HDMI port on mac can't do 60Hz

**Comment by karek314** [comment]
Picking custom resulted in issue, entire screen was reversed so instantly it went back to default.
<img width="1686" alt="screen shot 2017-04-21 at 00 57 43" src="https://cloud.githubusercontent.com/assets/9548618/25256053/69470a94-262e-11e7-846a-03db7ea5bc83.png">

**Comment by Floris497** [comment]
2014 has no USB-C right? Use mDP to DP cable just forget about HDMI.. :)

**Comment by Floris497** [comment]
Oh.. why would you want to avoid displayport? Then go for mDP to HDMI2.0 make sure it is really HDMI2.0 and not something like '4k capable' I could recommend Club3D adapters

**Comment by karek314** [comment]
Display Port in my monitor is used by something else. It's trouble to switch it.

Will it work ? - https://www.apple.com/shop/product/HHLN2ZM/B/belkin-4k-mini-displayport-to-hdmi-adapter

**Comment by Floris497** [comment]
Does it say 'HDMI2.0'?

**Comment by karek314** [comment]
How about second link i have pasted ?

**Comment by Floris497** [comment]
That last one probably does work

**Comment by karek314** [comment]
Okay, Thank you. 
So actually using that one, system should automatically pick 60hz or at least allow it within settings or Switchresx is mandatory ?

**Comment by Floris497** [comment]
Maybe you still need the core display patch but yes if your screen supports it it should work

**Comment by karek314** [comment]
Thank you, from my side i will keep this issue open until i confirm if it works with adapter.
Appreciate your effort on creating this and supporting.

**Comment by Floris497** [comment]
No problem please let me know if it works

**Comment by karek314** [comment]
Sure will do. By the way what's you opinion on why apple did not allowed it to work by default ? Boosting sales of new products / bad image of lack of support hdmi 2.0 or something else ?

**Comment by karek314** [comment]
Adapter arrived. However it does not work, setting anything higher than 30hz at 3840x2160 cause no signal on external monitor.

**Comment by Floris497** [comment]
I'm not completely sure why apple does this, but it might have to do that the GPU's are technically capable of delivering this resolution it won't run smooth all the time.. something apple doesn't want to happen to much.. till now there is no single Mac that has HDMI2.0 I'm not sure why but I think they are pushing for DisplayPort and Thunderbolt (essentially the same) but as usual with apple you never know.. (Just wild guesses)

So as long as you can set these resolutions on the macOS part it should be working.. although now is the question why your monitor does not recognise the signal.. could you give me the model ID of you screen?

**Comment by karek314** [comment]
Thanks for reply.
It's ASUS PB27U.

According to resolution, i wasn't able to set 60hz or anything higher than 30hz with 4k - there is no such option in System Preferences > Display or predefined in Switchscreenx (Current tab). I have tried to use custom one defined by me which resulted in no signal detected by monitor.

**Comment by karek314** [comment]
Maybe that's gpu itself, being not capable of pushing 4k@31-60hz
  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0d26

**Comment by Floris497** [comment]
If it shows the resolution it will send it over the cable.. are you sure you put the HDMI on the designated port for HDMI2.0 (port 1)

**Comment by karek314** [comment]
You are right, i had it in HDMI 3, didn't thought that other ports are not 2.0. What's the point putting old standard ports there, isn't 2.0 backwards compatible ?

Anyway, back to topic - It claims it's running over 60hz on 4k, but it's not that smooth like on Macbook screen itself. To me it still seems like 30hz. I have been testing different resolutions and for example. Scaled 1280x720@60hz works smooth like on MBP screen. Moreover with proper port it instantly shows 60hz option in System Preferences > Display, even when connected directly from MBP Hdmi output, isn't that weird ? With adapter, even running at 60hz still doesn't feels like it is.

**Comment by karek314** [comment]
If i force 4k@60hz manually via Switchscreenx (even when it claims that it's working at it) then it does display only 1cm of screen flashing with pink colour. Weird.

**Comment by Floris497** [comment]
I guess HDMI2.0 Chips are expensive.. and not many people will want to connect multiple of them to the screen anyways. My guess because almost all HDMI2.0 capable screens have only 1 port for this..
It could show the resolution if connected to HDMI but I doubt it would work.. 
That it doesn't run smoothly is because your GPU probably can't handle the load.. animations with be somewhat choppy at some point.. but you should most definitely see a difference in the cursor

**Comment by Floris497** [comment]
Or mouse pointer I mean.. if that runs smoothly it should be 60Hz

**Comment by karek314** [comment]
I think it doesn't. Looks like to 30hz to me, still.

**Comment by Floris497** [comment]
What does system information say?

**Comment by karek314** [comment]
Closing because couldn't manage to fix that. Running 4k@60hz causing image to not appear / flashing with pink/red colour/showing only 2cm of screen in pink colour.

**Comment by Floris497** [comment]
Don't really know what's going on.. but can't help you unfortunately

**Comment by karek314** [comment]
Thanks anyways.

It would need some more research, while your script has been ran correctly, valid adapter, 4k display - should work. I don't need it that much to spend more time to make it work.

**Comment by Floris497** [comment]
http://www.madrau.com
