### ISSUE TITLE
Patching CoreDisplay on Skylake+Sierra 10.12.4 does not lead to QuadHD

### ISSUE THREAD

**Issue by EugenMayer** [Floris497/mac-pixel-clock-patch-V2#171]
macOS: 10.12.4
GPU: Intel HD Graphics 520
CPU: i7 6600u
Device: Lenovo T460

Patching works:
   ./CoreDisplay-patcher.command patch v3
   SIP looks to be disabled, all good!
   Patching CoreDisplay with patch version 3
   Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
   /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature

After a reboot though, still only have FullHD max, on the DP port and the HDMI port ( both have QuadHD displays connected).

Any further information you might need?

**Comment by Floris497** [comment]
Did you try anything with Switchresx? And what cables are you using?

**Comment by EugenMayer** [comment]
the cables both def. support quad, e.g. on the other devices ( so thats assured ) . What is swtichresx?

**Comment by Floris497** [comment]
But you don't even want 4k right? Only 2560x1440.. I would still recommend you to try and make a custom resolution for this in switchresx and see what it tells you..

**Comment by yongming-qin** [comment]
I tried many time to set 3200x1600 for my laptop by hand, rdm or switchresx and failed . At last I tried a different ig-platform-id. Then all the scaled resolution can be set. It worth a try.

**Comment by edwindijas** [comment]
Did you get the issue fixed, i have identical issue! Can't find a work around.

**Comment by edwindijas** [comment]
Also identical model
