### ISSUE TITLE
actual NVIDIA Web Driver patching

### ISSUE THREAD

**Issue by TasPats** [Floris497/mac-pixel-clock-patch-V2#173]
MacOS 10.12.3
NVIDIA 750GT
NVIDIA Web Driver 367.15.10.35f01 (Up to date)
DELL P2715Q, HDMI
now run at 3840x2160, 30Hz
Windows 10 run at 3840x2160, 60Hz

regards readme.md table I need to run CoreDisplay Patcher (why not Nvidia patcher?)

Nvidia patcher patches (NVDALocation=)
/System/Library/Extensions/NVDAGK100Hal.kext/Contents/MacOS/NVDAGK100Hal

but if I use Nvidia Web drivers, proper driver for patching isn't
/System/Library/Extensions/NVDAGK100HalWeb.kext/Contents/MacOS/NVDAGK100HalWeb

thanks,
TP

**Comment by Floris497** [comment]
HDMI is not able to support full 4K@60Hz your card does not have HDMI2.0 so you should be looking at DisplayPort for this. Windows is tricking this by using only half the colors.. (4:2:0 YUV instead of 4:4:4 RGB)

**Comment by TasPats** [comment]
thanks!
