### ISSUE TITLE
MBP 2011 early, I want to use 2560x1080 on my LG 29UM58

### ISSUE THREAD

**Issue by jtjoo** [Floris497/mac-pixel-clock-patch-V2#177]
Hello I have MBP 2011 early which has ATI Radeon 6750M
And I bought new monitor (LG 29UM58 : http://www.lg.com/us/monitors/lg-29UM58-P-ultrawide-monitor ) 
And my MBP doesn't show 2560x1080 but works at 1920x1080 60hz linked by Moshi miniDP-HDMI Connector + HDMI cable (hi-speed with ethernet)

I've tried 2560x1080 resoluition at my PC (which has Radeon 6570) and I succeed by using Pixel-clock-patch(https://www.monitortests.com/forum/Thread-AMD-ATI-Pixel-Clock-Patcher) and CRU (https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU).

And I thought there will be similar one and finally I got your patch.
But still doesn't work... 

My succeeded settings 

![2017-05-06 1 31 00](https://cloud.githubusercontent.com/assets/10439318/25769885/496eb9f4-3260-11e7-8ea0-b9b41d33f7e9.png)

this worked on my PC and not working on my MBP.

And monitor info...

![2017-05-06 1 28 33](https://cloud.githubusercontent.com/assets/10439318/25769886/65f77570-3260-11e7-9e1b-5f1ced21a7cf.png)

Graphic information...

```
AMD Radeon HD 6750M:

Chipset Model: AMD Radeon HD 6750M
Type: GPU
Bus: PCIe
PCIe lane width: x8
VRAM (whole): 1024MB
Vendor: ATI (0x1002)
Advertiser ID: 0x6741
Revision ID: 0x0000
ROM revision: 113-C0170L-573
Automatic graphical transition: Supported
GMux version: 1.9.23
EFI version: 01.00.573
display :
SwitchResX4 - Color LCD:
Type: LCD
Resolution: 1680 x 1050
Pixel Depth: 32-bit color (ARGB8888)
Primary Display: Yes
Mirror: ㅇ
Online: Yes
Rotation: Supported
Auto brightening: Yes.
SwitchResX4 - LG Ultra Wide:
Resolution: 1920 x 1080 @ 60 Hz
Pixel Depth: 32-bit color (ARGB8888)
Mirror: ㅇ
Online: Yes
Rotation: Supported
Automatically adjust brightness: No.
```

**Comment by jtjoo** [comment]
No one answers ... so i close it.

**Comment by Floris497** [comment]
What did you try? I wasn't home for more than a week so unfortunately couldn't check all the new issues..

**Comment by Floris497** [comment]
And idk why I didn't see this for 3 months 😅

**Comment by jtjoo** [comment]
Oh... thx for your response. 
I need a time to check what I did because it's been a long time since I gave up while satisfying using 1080p mode. 
Happy to hear your response. Thanks

**Comment by Floris497** [comment]
So did you try CoreDisplay patcher?

**Comment by jtjoo** [comment]
I tried CoreDisplay patch but it still doesn't work.
![2017-08-14 8 00 25](https://user-images.githubusercontent.com/10439318/29254017-aaf78d2c-80c6-11e7-9a5b-778c4a6b73ac.png)

**Comment by Floris497** [comment]
It shows in switchresx that the values you set are invalid.. what is the values you filled in?

**Comment by jtjoo** [comment]
Guess the values are from pixel clock patch (as I wrote on this issue) my windows 10 desktop uses ATI radeon 6570.

![2017-08-15 12 31 20](https://user-images.githubusercontent.com/10439318/29278912-14f13d06-8151-11e7-89ad-88543d3b30c3.png)

**Comment by Floris497** [comment]
Then you should save and reboot.. did you do this? What kind if cable are you using?

**Comment by jtjoo** [comment]
I've already tried save this setting and reboot... and I am using miniDP to HDMI cable of Moshi which is working 2560x1080 on my PC.

**Comment by jtjoo** [comment]
Then I see horizontally flipped screen.

**Comment by Floris497** [comment]
Oh.. that's even more interesting?? How's that possible

**Comment by jtjoo** [comment]
I think it'll be better way if you tell me setting numbers...
![2017-08-15 4 10 10](https://user-images.githubusercontent.com/10439318/29287206-a556601a-816f-11e7-8f9e-eaa9c240fde5.png)

**Comment by jtjoo** [comment]
It would be nice you tell me various ways to diagnosis. 
I should sleep now, I'll try after I wake up.

**Comment by Floris497** [comment]
Create a new custom resolution, fill in a only active pixels: 2560 active lines: 1080 and then scan rate in 30Hz the rest should be good automatically

**Comment by Floris497** [comment]
If that works try 60Hz

**Comment by jtjoo** [comment]
doesn't work T_T

![2017-08-15 4 16 13](https://user-images.githubusercontent.com/10439318/29287458-7ebf122a-8170-11e7-84e5-56de4df35ed1.png)

**Comment by jtjoo** [comment]
I'll try after I woke up... it's too late night here.

**Comment by Floris497** [comment]
Do not fille the kHz field but the Hz Field

**Comment by jtjoo** [comment]
Still same ..

![2017-08-15 4 18 07](https://user-images.githubusercontent.com/10439318/29287534-c18ab92e-8170-11e7-9fca-9e7c344b413e.png)

**Comment by Floris497** [comment]
Press OK and reboot and see what happens, did you do? I'm out of options a bit.. I'll think what fan fix your problem

**Comment by jtjoo** [comment]
I see flipped screen again.

**Comment by Floris497** [comment]
I've never heard of this problem before..

**Comment by jtjoo** [comment]
Hmm I'll try another way after I sleep. And will comment here. Thanks.

**Comment by jtjoo** [comment]
There is good news!
I solved my problem with this setting of switchresX. I am purchasing switchresX right now ;)
https://gist.github.com/erichrobinson/9755ba1f3ec45b289c40

![2018-02-06 10 58 44](https://user-images.githubusercontent.com/10439318/35863454-095482c0-0b92-11e8-862e-a8b40661a210.png)

**Comment by iamperi** [comment]
@jtjoo thanks for posting the solution. It worked for me too. Thanks again.
