### ISSUE TITLE
Unknown io kit version - GTX 1050 2GB - 10.12.5

### ISSUE THREAD

**Issue by ulrichdahl** [Floris497/mac-pixel-clock-patch-V2#183]
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

otool IOKit: 991df1fc5d2538f50a7e58e55f3a8fba
otool IOKit.bak: NO FILE (this is okay)
IOKit: 366073413424a33fd43a96b7ad30103f
IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by ulrichdahl** [comment]
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     NVDAGK100Hal: 18a647b2070fa53ec186415757cf6334
 NVDAGK100Hal.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
IOKit is not being used anymore.. so use CoreDisplay. for pascal cards I have a patch for the Nvidia web drivers:

```
sudo perl -i.bak -pe '$oldLimit1 = qr"\x8B\x82\xB0\x00\x00\x00\xB9\x88\x84\x02\x00"s;$newLimit1 = "\x8B\x82\xB0\x00\x00\x00\xB9\x00\x35\x0C\x00";s/$oldLimit1/$newLimit1/g' /System/Library/Extensions/NVDAGP100HalWeb.kext/Contents/MacOS/NVDAGP100HalWeb
sudo touch /System/Library/Extensions
```

**Comment by ulrichdahl** [comment]
After applying the patches for CoreDisplay and Nvidia, it still does not work. 
Is this is a limitation in the GTX 1050? It is not a reference design board (Gigabyte 1050 2G OC Windforce) it has 3 x HDMI, 1 x DP and 1 x DVI. 2 of the HDMI ports does not work at all.

**Comment by Floris497** [comment]
Can you try the new WEB patch for Pascal? I addition to CoreDisplay

**Comment by Floris497** [comment]
Oh.. wasn't reading good.. ehm let me think

**Comment by ulrichdahl** [comment]
No change with the new pascal patch.
```
Detected unpatched Nvidia driver on OS X nvidia web: 378.05.05.15f01 (10.18.5).
Patching NVDAGP100HalWeb with patch version 1
```

**Comment by Floris497** [comment]
Hm.. what kind of connection are you using?

**Comment by ulrichdahl** [comment]
Monitor 1: DP is connected with DP cable (supplied with monitor)
Monitor 2: HDMI port 1 with HDMI 2.0 cable (supplied with monitor)
Both monitors are LG 27UD58-B and have been tested to be cabable of 4K @ 60HZ on all inputs.

**Comment by ulrichdahl** [comment]
And the DP connection is working in 4K @ 60hz 😄

**Comment by Floris497** [comment]
Did you already mess with switchresx?

**Comment by ulrichdahl** [comment]
Yes, but it just gave me black screens or very low res on both displays... 
Maybe I am doing something wrong there, but I have tried to play with some settings in it. Do you think I should try that again?

Anyway, THANK YOU so much for your help 👍

**Comment by ulrichdahl** [comment]
Okay... I owe you a massive beer or something if I ever meet you 😄 

Just tried to hook the monitor up to my NVIDIA Shield.. It does 4k @ 60hz on my TV so I know it can do it... but connected to the monitor it only allows 30hz in 4K... DAMN IT... false advertizing!

So I will need to replace my graphics card with a reference GTX 1060 to get 2 DP connectors...

Thank you, and I am so sorry for being an idiot here 😃

**Comment by ulrichdahl** [comment]
Okay, know things got really weird.. I enable "HDMI ULTRA HD Deep Color" in the monitor and NOW it will do 4k @ 60Hz from my NV Shield.. Connected to the computer the other screen flashes and shows me that it has selected 60Hz 4K scaled resolution.. but the screen is black 😒 

Maybe NOW playing with switchresx is a good idea 😄

**Comment by Floris497** [comment]
Haha just play around with it a but.. I have the feeling that drivers for pascal need some work my card isn't working fully either.. the card is advertised as HDMI2.0b I could not imagine they limit here.. your shield might be doing 4:2:0 YUV instead of 4:4:4 RGB to have half the color space and dubbe the frame rate..

**Comment by Floris497** [comment]
Reading about both your card and screens it should work full color full framerste on both HDMI and DP.. so I'm not sure why it's not working as expected.. did you try different HDMI ports?

**Comment by ulrichdahl** [comment]
Never did get HDMI to work with your patch. I have now bought an EVGA GTX 1060 with 3 DP ports that all work out the box with giving me full 4k 60hz glory 😃
I did end up trying to fiddle with the HDMI settings of the monitor in a virgin vanilla installation without any patching done, it gave exactly the same results.

But THANKYOU so much for your help in trying to get this to work. 👍

**Comment by Floris497** [comment]
Displayport is always better :D enjoy the view!
