### ISSUE TITLE
Black Screen on Boot-up

### ISSUE THREAD

**Issue by Mark19318** [Floris497/mac-pixel-clock-patch-V2#184]
I have a late 2014 Mac Mini.  After doing the CoreDisplay patch and turning SIP back on I have the following issue.  I get a black screen on boot.  I have to force a shutdown and then do a PRAM reset.  Then I get the login screen and all is well.  I noticed that if I set my screen to 30hz before shutting down my Mini Will boot as normal.  If I leave it at 60hz I get a black screen on boot-up.  I also have the same issue if I let the computer go into deep sleep.

**Comment by Floris497** [comment]
Please reopen if you still have this issue
