### ISSUE TITLE
10.13 build:17A264c High Sierra

### ISSUE THREAD

**Issue by sherlockmac** [Floris497/mac-pixel-clock-patch-V2#187]
otool CoreDisplay: 64f70047bbd562a6822a70350cf0b6fc
CoreDisplay: a33cb5ab87b07a0d97fc73eebafe255c

**Comment by Floris497** [comment]
Thanks will add :)

**Comment by Floris497** [comment]
They are the same as 10.12.. :)

**Comment by sherlockmac** [comment]
Thank you 👍🏼🙏🏼

**Comment by sherlockmac** [comment]
Can you tell me it resembles which version of 10.12?

**Comment by Floris497** [comment]
What do you mean?

**Comment by sherlockmac** [comment]
you said they are the same as 10.12

**Comment by Floris497** [comment]
Yes, it looks like the signatures are the same as 10.12.5. So it should work :)

**Comment by Floris497** [comment]
Oh.. maybe it isn’t.. i think i ran a different update on my machine.. will check when i get to my computer...

**Comment by charlieustc** [comment]
Same issue as op
