### ISSUE TITLE
v2 error

### ISSUE THREAD

**Issue by BignThicc** [Floris497/mac-pixel-clock-patch-V2#188]
I'm certain there must be an issue with the script. If "patch v2" is tried, there is a return of "this patch does not exist". This results in the only available path being v1 which patches 
cbe4cf2687f7828c64a1698a910ae124 'nvidia web PASCAL: 378.05.05.15f01 (10.18.5)'
incorrectly to
096a081347024086efa8d396d814afd0 'nvidia web PASCAL: 378.05.05.05f02 (10.17.34)'
Thank you for your time and attention to this issue.

**Comment by Floris497** [comment]
There is only a v1 :)

**Comment by Floris497** [comment]
But what are you trying to do?

**Comment by BignThicc** [comment]
I'm trying to run the patch and even though it detects my current version as 10.18.5, it patches it to 096a081347024086efa8d396d814afd0 instead of 0ee0407775db6da70015dbcc75780e66.

**Comment by BignThicc** [comment]
Beautiful work btw

**Comment by Floris497** [comment]
No but you want 4k for HDMI i guess? I think it’s not working with current drivers and i can’t do tests because i don’t have a capable screen for HDMI2.0 but try CoreDisplay patch first :)

**Comment by BignThicc** [comment]
Nope. Displayport. I ran the CoreDisplay patcher with only v3 appearing successful and then I ran the pascal patch command. The issue is that after I run the Pascal command, the driver is patched for 378.05.05.05f02 instead of 378.05.05.15f01 which is the one I am running.

**Comment by Floris497** [comment]
Ah, that’s okay, because that’s just a nr.. the patch for both versions is the same.. maybe there is missing signatures.. the files are in BETA. And actually the web driver patch is to be used for enabling >330Mhz over dual link DVI

**Comment by Floris497** [comment]
DP should work without any patch..
