### ISSUE TITLE
Not working on 10.11.4

### ISSUE THREAD

**Issue by mehmetyildiz94** [Floris497/mac-pixel-clock-patch-V2#19]
After update to 10.11.4 from 10.11.3 the patch does not work anymore. Tried to unpatch and patch it again but that did also not work. SIP is disabled. I have a MacBook Air.
Edit:
```
These are my md5 sums:
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.4 build:15E65

     otool IOKit: 422c441e207a011b355f712fc0ff7fba
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: 2f32c634a4100dabab994d0f1748fd03
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment]
You did something the patch can not prevent.. After the update, you unpatched the old backup that was still in place.. This means you are now running a patched version of the old file.. Unfortunately the only thing you can do now is running the OS X installer again..
