### ISSUE TITLE
No signal showed after display sleep & slow movement

### ISSUE THREAD

**Issue by soundsticks** [Floris497/mac-pixel-clock-patch-V2#193]
I'm using this CoreDisplay patcher for Intel HD630, but after the MacOS turn off it display after 15min I won't able to get the display signal but the OS it still running.

Also the graphic movement are slow especially the fade in/out folder and mouse movement.

**Comment by Floris497** [comment]
Kaby lake? No idea about it..

**Comment by soundsticks** [comment]
Yes I'm using KabyLake

**Comment by Floris497** [comment]
Sorry.. I have no idea.. I think you can do without patch and use SwitchResX? did you try that?

**Comment by soundsticks** [comment]
I try using SwitchResX before the patch. Not working. 

And how to uninstall the patches?

**Comment by Floris497** [comment]
Add unpatch after the script, see readme

**Comment by Floris497** [comment]
Maybe it will work with the new High Sierra patch that I'm testing now..
