### ISSUE TITLE
[OT] Compatible device

### ISSUE THREAD

**Issue by LETRA** [Floris497/mac-pixel-clock-patch-V2#194]
Floris, excuse the off topic. A question. This device requires Mini Display Port 1.2. Is it compatible with Mac Mini 2012? http://www.ebay.es/itm/LINDY-Mini-DisplayPort-to-2-x-HDMI-Splitter/332176562505?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2055119.m1438.l2649

A greeting

**Comment by Floris497** [comment]
I hope it worked :)
