### ISSUE TITLE
Not able to set 60Hz on macbook (12" early 2016) with osx 10.11.6

### ISSUE THREAD

**Issue by YuaShizuki** [Floris497/mac-pixel-clock-patch-V2#196]
Used the IOKit patch but was unable to get 60Hz on my LG 27UD68 4K screen. I am using the Apple MJ1K2ZM/A USB-C Digital AV Multiport Adapter cable.

Can some please help

**Comment by Floris497** [comment]
Does that cable advertise HDMI2.0? I think it does not.. so it doesn't support 4k@60Hz
