### ISSUE TITLE
Hello need help please.

### ISSUE THREAD

**Issue by Harrynaf** [Floris497/mac-pixel-clock-patch-V2#197]
Hey just updated my hackintosh to 10.12.6(4k uhd),everything working but my coredisplay patch got ***ked as usual,problem is when i run your coredisplay says Unknown version of CoreDisplay found..,so what i did is i run the md5 command
<img width="564" alt="screen shot 2017-07-21 at 16 45 22" src="https://user-images.githubusercontent.com/19495385/28466186-4518e270-6e34-11e7-93a1-0f790405a714.png"> and this is the terminal output,i hope you can update it as soon as you can ,hope you read this.

**Comment by marnovo** [comment]
Same here when running `CoreDisplay-patcher.command`.

```
SIP looks to be disabled, all good!

Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.6 build:16G29

     otool CoreDisplay: 9a653ffdfb5e1bcfaa71412000d0b111
 otool CoreDisplay.bak: 54a5a1adfb1225411bacf5c3ee0b4d9a
           CoreDisplay: 188ac719b7f00e15c7ae23d0b97af669
       CoreDisplay.bak: 5ebdbc42c414d053ae14f38f7601f1ba
```

@Floris497, any way to hotfix this ourselves?

**Comment by Floris497** [comment]
Oh totally forgot 😅 will fix right away

**Comment by Floris497** [comment]
Updated

**Comment by Harrynaf** [comment]
Just patched,everything splendid.Thanks.

**Comment by marnovo** [comment]
Great, thank you. Could we do this ourselves to submit a PR for next versions? This will be a recurring issue, so…

**Comment by Floris497** [comment]
Yep, with `file.command parch vX` you can patch with the latest version. Mostly the patch will work without any problems on a new version. The script will tell you if it was successful or not. Mostly I'll update the script very easily mostly an hour after release or something.
