### ISSUE TITLE
Does this work with "Scaled" Display?

### ISSUE THREAD

**Issue by anthonylbest** [Floris497/mac-pixel-clock-patch-V2#198]
I am running this with a 4k TV with 60Hz inputs, but the default display size is 1920, so i have to change to scaled mode and can only select 30Hz.

**Comment by Floris497** [comment]
What kind of cable/adapter and what mac do you have?

**Comment by anthonylbest** [comment]
Early 2015 MB Air.  I am using the Elgato thunderbolt dock 2, and a hdmi 2.0 cable.  I also have a Plugable mdp - hdmi adapter.  Both state they can do 4k at 60hz.

**Comment by Floris497** [comment]
Not sure if your Mac can do 4k.. I think it cannot..
