### ISSUE TITLE
GTX 1050 10.12.5

### ISSUE THREAD

**Issue by howardwkim** [Floris497/mac-pixel-clock-patch-V2#199]
Hello! Will this work for EVGA GeForce GTX 1050 using HDMI 2.0? I tried out the mac-pixel-clock-patch-V2 without success, but before I attempt to debug the problem I wanted to check if this video card is supported (I noticed that it was not listed). Thanks!

**Comment by Floris497** [comment]
Ehm.. I think currently it doesn't.. pascal cards have some problems with HDMI 2.0 but it should work on 900 series cards.. although I'm not sure if they do work in 10.12.6.

**Comment by howardwkim** [comment]
If I go the HDMI 2.0 to Displayport 1.2 route, will it work on the EVGA GeForce GTX 1050?

**Comment by Floris497** [comment]
Yes you have a higher chance for that to work properly.

**Comment by srxa** [comment]
10.12.6 HDMI 2.0 is not working  neither on maxwell or pascal ... Tested with Asus turbo 1070 and Asus strix 980ti

**Comment by Floris497** [comment]
Was it working on 10.12.5?

**Comment by srxa** [comment]
I don't know, I installed fresh 10.12.6. Asus strix 980ti was working on El Capitain 10.11.6.

**Comment by Floris497** [comment]
Pascal isn't working with hdmi2.0 as far as I know.. not for my tv.. but also the tv i have is crap.. maxwell i have no idea for current OS.. don't have a card like that..

**Comment by srxa** [comment]
I have samsung 48JU7500 which is one of better TV's for using as 4k monitors. I can help you with debugging a problem if you give me some instructions what to try.

**Comment by howardwkim** [comment]
Tried installing CoreDisplay patcher and rebooting, but I do not see the option for 60hz (currently set at 30hz, and I see option for 24hz and 25hz).

Here is what I see when installing the patch:

```
Howards-iMac:Downloads hwk$ ~/Downloads/CoreDisplay-patcher.command 
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12.5 16F73.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
Closing..
Howards-iMac:Downloads hwk$ ~/Downloads/CoreDisplay-patcher.command 
SIP looks to be disabled, all good!

(otool) Detected patched CoreDisplay on OS X 10.12.5 16F73.
```

**Comment by howardwkim** [comment]
Tried installing CoreDisplay patcher and rebooting, but I do not see the option for 60hz (currently set at 30hz, and I can also see option for 24hz and 25hz, but no option for 60hz).

Here is what I see when installing the patch:

```
Howards-iMac:Downloads hwk$ ~/Downloads/CoreDisplay-patcher.command 
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12.5 16F73.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
Closing..
Howards-iMac:Downloads hwk$ ~/Downloads/CoreDisplay-patcher.command 
SIP looks to be disabled, all good!

(otool) Detected patched CoreDisplay on OS X 10.12.5 16F73.
```

Am I forgetting a step?

**Comment by Floris497** [comment]
Ah so what needs to be done is patching CoreDisplay.. that should do the trick initially. Not sure if it still does, see if you can add any resolutions with switchresx. If not continue to patch IOKit and Nvidia Web drivers for your card model. I'll check in a moment if it needs updating. But I think the old patch can be forced.. be careful with the web driver patch because if you break it you might have no video at all..

**Comment by howardwkim** [comment]
I want to make sure I understand your instructions:

1. Patch using CoreDisplay-patcher.command, which can be found in this GitHub repo. This is what  I did in my comment above.
2. Install switchresx to see whether I have an option to switch from 4k@30hz to 4k@60hz using this tool. (Assuming switchresx allows me to change the refresh rate to 60hz, will I will need to purchase switchresx if I want to continue running at that refresh rate?)

If I am still unable to get the 60hz refresh rate with the aforementioned steps:

3. Patch with ```IOKit-patcher.command``` (from this GitHub repo)
4. Patch with ```NVIDIA-WEB-PASCAL-patcher.command``` (also from this GitHub Repo) since I have a GeForce GTX 1050. Note: I already have the latest Web Drivers from Nvidia for macos 10.12.5.

As for your last comment, what does it mean to force the old patch? Is this something I must actively do? And when installing the web driver patch (```NVIDIA-WEB-PASCAL-patcher.command```), what precautions can I take to ensure that I don't end up with no video at all? Thanks!

**Comment by srxa** [comment]
As i stated before, I tried all of that options, HDMI 2.0 is not working, meaning you can get maximum 30hz on 4k over HDMI.
What I tried:
CoreDisplay-patcher.command patch v3
IOKit-patcher.command patch v7
NVIDIA-WEB-MAXWELL-patcher.command patch v1 (in that moment i was trying with 980ti, and there is only v1 patch in script)

I am using EasyRes, which is simillar to switchres x but free, and was working well on 10.11.6.
There is option to select 3840x2160@60hz, but you will only get black screen. Anything above 1920x1080@60hz is not working for me. 30hz works fine.
You will not break driver with any of this patches.

**Comment by howardwkim** [comment]
I am still unable to get 4K@60hz to work. I tried using switchresx and used a setting that turned my signal black and I was unable to change it back, so I reinstalled Sierra.

I am using an HDMI 2.0 cable + Club3D DisplayPort 1.2 to HDMI 2.0 UHD Active Adapter.
Sierra 10.12.5. EVGA GeForce GTX 1050. Samsung 40" 4K Ultra HD LED LCD TV UN40KU6290FXZA (identical to Samsung KU6300). UHD Color option is OFF.

1. I ran ```CoreDisplay-patcher.command``` and it installed v1. This is what I saw:

```
Howards-iMac:Downloads hwk$ ~/Downloads/CoreDisplay-patcher.command
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12 16A313a.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 1
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
Closing..
```
I reset my computer and tried again, this time it installed v3:

```
Howards-iMac:Downloads hwk$ ~/Downloads/CoreDisplay-patcher.command
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12.5 16F73.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
Closing..
```

I installed SwitchResX. No native option for 4k@60hz. Under my SAMSUNG monitor within SwitchResX I tried setting the Startup Resolution to 3840x2160@60hz. I also tried creating a Custom Resolution for 3840x2160@60hz. Neither option worked.

Next I installed ```IOKit-patcher.command```  and then I accidentally installed ```NVIDIA-patcher.command```. Here is what I saw:

```
Howards-iMac:Downloads hwk$ ~/Downloads/IOKit-patcher.command 
SIP looks to be disabled, all good!

(otool) Detected unpatched IOKit on OS X 10.12.5 16F73 and 10.12.6 16G29.
SIP looks to be disabled, all good!
Patching IOKit with patch version 7
Password:
Re-signing /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: replacing existing signature
Closing..
Howards-iMac:Downloads hwk$ ~/Downloads/NVIDIA-patcher.command 
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading

Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     NVDAGK100Hal: 18a647b2070fa53ec186415757cf6334
 NVDAGK100Hal.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

No luck after these two patches. I then tried the correct patch ```NVIDIA-WEB-PASCAL-patcher.command```: 

```
Howards-iMac:Downloads hwk$ ~/Downloads/NVIDIA-WEB-PASCAL-patcher.command
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading

Detected unpatched Nvidia driver on OS X nvidia web PASCAL: 378.05.05.15f01 (10.18.5).
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading
Patching NVDAGP100HalWeb with patch version 1
Password:
Closing..
Howards-iMac:Downloads hwk$ ~/Downloads/NVIDIA-WEB-PASCAL-patcher.command
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading

Detected patched Nvidia driver on OS X nvidia web PASCAL: 378.05.05.05f02 (10.17.34).
```

Still no luck.  I unsuccessfully attempted to unpatch ```NVIDIA-patcher.command```:

```
Howards-iMac:Downloads hwk$ ~/Downloads/NVIDIA-patcher.command unpatch
There is no backup file, we can not undo the patch. the patch might not even been done.
Closing..
```

Any ideas on how to proceed? Thanks!

**Comment by howardwkim** [comment]
Success! Turns out I was looking in the wrong place for a solution. If you are not careful with Switchresx, you can end up selecting settings within your computer that your monitor does not recognize, cuasing your display
