### ISSUE TITLE
Will this fix the 30hz (should be 60hz) problem?

### ISSUE THREAD

**Issue by est4tic** [Floris497/mac-pixel-clock-patch-V2#20]
Hi,

I'm sorry if this is not the place to ask, but I have a Dell P2715Q monitor and I'm using it with a Late 2013 iMac (with a GeForce 780M video card) and I can't make it work in 60hz (only 30hz). I'm using a Dell mDP > DP cable and the screen has MST off.

Thanks!

**Comment by Floris497** [comment]
Did you try switchresx? That is the first thing you try, if that doesn't work you would want to look into using this patch. 

Please let me know how this is going for you!

**Comment by est4tic** [comment]
I'm trying it as we speak, but I cannot make a custom resolution - all of my tries ended up invalid. :(

**Comment by Floris497** [comment]
Then try the IOKit patch, if that doesn't work try the Nvidia one also.

**Comment by est4tic** [comment]
Thanks!

Sorry to keep bothering you, but where exactly can I find the NVIDIA one?

**Comment by est4tic** [comment]
I have applied both patches, but it didn't change anything related to the refresh rate. :(

**Comment by Floris497** [comment]
Can you get it to go to 40Hz? Try with switchresx, are you sure the patch did actually patch?

**Comment by est4tic** [comment]
I've tried making different custom resolutions with SwitchResX, from 50hz to 60hz, but all of them turned out invalid after restarting the iMac. After applying the patches I didn't use SwitchResX anymore, should I ?

**Comment by Floris497** [comment]
Yes you should still use that program

**Comment by est4tic** [comment]
Hi again,
It doesn't work - I still can't get it to work in 60hz. :(

**Comment by est4tic** [comment]
Hi again,
It doesn't work - I still can't get it to work in 60hz. :(

**Comment by est4tic** [comment]
Hi again,
It doesn't work - I still can't get it to work in 60hz. :(

**Comment by Floris497** [comment]
Easy on.. I'm thinking 😝😝

**Comment by Floris497** [comment]
can you get this one to 40Hz or does your display only accept 30Hz and 60Hz and nothing in between?

**Comment by est4tic** [comment]
Hi, thanks for the reply. I was unable to get any custom resolution validated in SwitchResX. On the other hand, I just bought a Thunderbolt 2 cable and it doesn't even detect the screen. :(

Should I get the Club 3D Mini DisplayPort 1.2 auf HDMI 2.0 4K60Hz UHD Aktiver Adapter?

Thanks!

**Comment by Floris497** [comment]
Thunderbolt cable does not work on displayport connections.. Use a valid displayport cable

**Comment by est4tic** [comment]
Until now I've only tried different DELL cables (mDP > DP), do you recommend something else?
Should I get the Club 3D Mini DisplayPort 1.2 auf HDMI 2.0 4K60Hz UHD Aktiver Adapter?

**Comment by Floris497** [comment]
No.. If your display has DP i would recommend you using that!
