### ISSUE TITLE
how to enable sip on macpro 5.1 

### ISSUE THREAD

**Issue by jaywe155** [Floris497/mac-pixel-clock-patch-V2#201]
I've followed all your steps and its working fine with my 1080 gtx the only problem now is to reactivate the SIP my older graphic card which I used to boot into recovery mode after this it is not working anymore. what can I do in this situation?
 Thanks

**Comment by Floris497** [comment]
HDMI? Don't think you need anything with for displayport

**Comment by jaywe155** [comment]
ah maybe i should change the resolution before i put my old graphic card in i dont think the old one is working on 3440x1440 60hz... 
and my old card was running on mini display port

**Comment by Floris497** [comment]
What is the old card you have? It might not natively run that resolution on the card..

**Comment by jaywe155** [comment]
I tried it again with my stock graphics card in another resolution but its just sitting in a black screen it seems like I'm stuck can't get back into recovery mode...

**Comment by jaywe155** [comment]
ATI Radeon HD 5870 1 GB

**Comment by jaywe155** [comment]
if you also want to use an Nvidia/AMD driver that has been patched you need to keep SIP disabled. this is because SIP will not allow you to run drivers which have a broken or no codesignature.

shit didn't read that sorry so I should stay in SIP disabled mode

**Comment by Floris497** [comment]
This AMD GPU has a limit for 4k@40Hz this should mean it can output your resolution on 60Hz but idk if your mac supports that 😅
