### ISSUE TITLE
60hz option is available after the patch but it still does not work when i connect to 4k tv?

### ISSUE THREAD

**Issue by don47** [Floris497/mac-pixel-clock-patch-V2#202]
Hi. I downloaded the patch IOkit and core display and it was a success. In the display setting I finally had the option to use 4k 60hz. I directly connected my 2015 macbook pro with a HDMI cable made by the company called monster, I have the latest one with 27gbps, I did not use any adapter or displayport only an HDMI cable. When I got picture on my TV I still had the option to use 4k 60hz. I chose 4k 60hz and my screen refreshed on tv and mac. I moved my cursor and it stil was 30hz even though in the settings it said that it was 4k 60hz. What did I do wrong?

My tv is Samsung Ue49ks7005. Its a SUHD tv and it definitly support 60hz.

**Comment by Floris497** [comment]
Your MacBook has a hardware limit to 30Hz on the HDMI port.. so you need an mDP to HDMI2.0 adapter.

**Comment by don47** [comment]
Thank you, any idea where I can buy that from. Do Apple sell any beacause I really want to buy from the store not any other websites.

**Comment by Floris497** [comment]
I would go for club3D adapter

**Comment by don47** [comment]
Do you mean these?

https://www.multicom.no/club-3d-mini-displayport-til-hdmi/cat-p/c/p8428817

http://www.club-3d.com/en/detail/2339/mini-displayportt-1.2-to-hdmi-2.0/

**Comment by don47** [comment]
Another question. The mini display adapter from club 3d, will it connect to my thunderbolt port or what? My macbook has usb port, hdmi port, power port, and thunderbolt port.

**Comment by Floris497** [comment]
TB Is backwards compatible with Mini DisplayPort so yes it connects to that port

**Comment by don47** [comment]
Thank you very much for your help.
