### ISSUE TITLE
IOKit syntax error

### ISSUE THREAD

**Issue by kcornman** [Floris497/mac-pixel-clock-patch-V2#203]
Trying to install this on my Mac Air, OS X 10.11.6 and I get a syntax error. I kind of new to this, so am I doing something wrong here or is it a script issue? Here is my terminal window:

cher$ chmod +x ~/Downloads/IOKit-patcher.command
cher$ ~/Downloads/IOKit-patcher.command
/Users/cher/Downloads/IOKit-patcher.command: line 7: syntax error near unexpected token `newline'
/Users/cher/Downloads/IOKit-patcher.command: line 7: `<!DOCTYPE html>'
cher$

**Comment by Floris497** [comment]
1. Why IOKit 2. You downloaded the HTML page hosting that file? What year is your MacBook air?

**Comment by kcornman** [comment]
It's an early 2014 13" with Intel HD Graphics.  I'm trying to make a LG Ultrawide monitor work on it. So are you saying I downloaded the IOKit wrong? How would be the correct way to download and run this script? Like I mentioned, I'm pretty new to having to run a script, so please bear with me. Thank you.

**Comment by Floris497** [comment]
You need coredisplay patch, download the zip archive from github and you will be fine. :) let me know if you have any other questions

**Comment by kcornman** [comment]
Thank you Floris, this is what I get now:

cher$ chmod +x ~/Downloads/CoreDisplay-patcher.command
cher$ ~/Downloads/CoreDisplay-patcher.command
md5: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: No such file or directory
/Library/Developer/CommandLineTools/usr/bin/objdump: '/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay': No such file or directory.
fatal error: /Library/Developer/CommandLineTools/usr/bin/otool: internal objdump command failed
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12 16A313a.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 1
Password:
Can't open /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: No such file or directory.
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: No such file or directory
Closing..
cher$

**Comment by kcornman** [comment]
I have since updated the OS to Sierra 10.12.6. I tried running the core display patch again and it still comes up with errors. Any ideas on what I can do? This is what I get now:

Last login: Fri Aug  4 16:09:49 on ttys000
cher$ chmod +x ~/Downloads/CoreDisplay-patcher.command
cher$ ~/Downloads/CoreDisplay-patcher.command
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12 16A313a.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 1
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: the codesign_allocate helper tool cannot be found or used
Closing..
cher$

**Comment by Floris497** [comment]
Install xcode :)
