### ISSUE TITLE
Needs support for latest High Sierra Public Beta 10.13 (17A315i)

### ISSUE THREAD

**Issue by Herolordman** [Floris497/mac-pixel-clock-patch-V2#204]
Needs to be updated to run / work on public beta (17A315i)

**Comment by Floris497** [comment]
Eh.. i have no computer near me for some days.. please force as described in readme :) maybe i can do something today but don't count on it

**Comment by Herolordman** [comment]
I didnt know there was a way to force, I will look again. I am new, so all I knew to attempt was to delete the part of the code that checks for correct MD5 :D

**Comment by Herolordman** [comment]
if I try to force by adding v3, it returns "option is not valid" followed by the help menu items.

**Comment by Floris497** [comment]
`Patch.command patch v3`
