### ISSUE TITLE
For anyone running pascal (GTX9XX or 10XX series) trying for 4K

### ISSUE THREAD

**Issue by mark3p** [Floris497/mac-pixel-clock-patch-V2#208]
Not an issue, just for a bit of information as I see a lot of people raising issues for Floris497.

Apple do funky things with displayport to HDMI protocol and that only got worse when they re-engineered it to transport over USBC. At the moment HDMI protocol is capped at 1.4 at an OS level meaning HDMI2.0 will never work as there is no system level extensions for it (these were restricted in Sierra, El Cap is fine).

To run 4K @ 60hz 4:4:4 chroma sub-sampling you will need to be exclusively displayport until you are outside of the OS layer. This can be achieved with an ACTIVE displayport to HDMI adapter 2.0 adapter (where conversion happens in the adapter rater than the OS).

The current one I use for all hackintosh builds in https://www.amazon.co.uk/Plugable-DisplayPort-Supports-displays-3840x2160/dp/B00S0C7QO8/ref=sr_1_1?ie=UTF8&qid=1502045792&sr=8-1&keywords=plugable+displayport+hdmi+2.0+adapter

Note this will also work for anyone using a mac-pro with a pascal series graphics card. Audio transport is limited to 2ch 16bit. CoreDisplay patch is all you need.

These issues also effect the new macbooks / macbook pro's using USBC whereby the USBC to HDMI is capped at 1.4 due to OS layer so you need to use USBC to Displayport with an Active adapter to HDMI2.0. Cables are now out which combine these such as https://www.amazon.co.uk/CHOETECH-Thunderbolt-Compatible-MacBook-ChromeBook/dp/B06XS7T4GP/ref=sr_1_2?ie=UTF8&qid=1502046484&sr=8-2&keywords=usb+c+to+hdmi+2.0

Cheers guys

**Comment by guzferreira** [comment]
Hi, do you know if this adapter works? 
http://www.dell.com/en-us/shop/dell-adapter-displayport-to-hdmi-2-0-4k/apd/492-bbxu/pc-accessories. 
It was the only one I found in Brazil that explicitly said it was DisplayPort -> HDMI 2.0 (I did find the Club3d one, but it was too expensive. I bought it, and it works for a minute or so, then it goes black.

**Comment by Floris497** [comment]
Maybe the HDMI cable you use is too long or poor quality?

**Comment by guzferreira** [comment]
Maybe yes, but I don't know. It seems like it, doesn't it? 
I bought two other hdmi cables, this one is the only one I can get a signal. 
I'll try and buy one from a famous brand or something.

**Comment by Floris497** [comment]
Hm, some famous brand does not make a huge difference mostly.. just buy one that is certified for 4k@60Hz and it should be fine.. I hope :)

**Comment by guzferreira** [comment]
How can I know it is certified for 4k@60hz? The brand is a way of "knowing", I guess. 
Anyway, I'll look for it and report back. 
Thanks! :)

**Comment by Floris497** [comment]
I think it should state on the box, there is an official certification for HDMI cables

**Comment by mark3p** [comment]
One of the main factors is it supporting a 594mhz clock rate and HDMI 2.0 6ghz however most of the cheap ones on amazon don't state their specs

**Comment by Floris497** [comment]
All HDMI cables should in theory be able to do it.. only some interference between the different wires is creating a problem.. so isolation and copper alloy used is the main difference

**Comment by guzferreira** [comment]
I tried with a different cable. Same result. 
I noticed something: In the System Report, the display sections says the connection is via HDMI or DVI, and it states Television: YES.
Because of the adapter, shouldn't the connection be "DisplayPort"? Maybe the adapter is not active? Could somebody with a working adapter confirm to me how is that info on their System Report?

**Comment by mark3p** [comment]
Here is my system report:

SAMSUNG:
  Resolution:	3840 x 2160 @ 60 Hz
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DVI or HDMI
  Adapter Firmware Version:	7.46
  Television:	Yes

And am using the adapter detailed in my first post. As you can see fully working.

If you get an image for a bit and then it goes black or is intermittent then that's usually a sign that the cable you are using cannot keep up with the bandwidth. Order the pluggable one I've linked in my original post or find an active displayport to HDMI2.0 adapter that specifically says it supports HDMI2.0 6ghz and clock rate of 594mhz.

**Comment by guzferreira** [comment]
Thank you. I'll keep trying

**Comment by guzferreira** [comment]
I'm glad to inform that I tried yet another cable aaaand. It works! Finally. Thank you guys for your support.

**Comment by guzferreira** [comment]
OK. Too fast. It worked for more time than before, but it still gave me blinking screen after a while. I guess I can confirm the problem is the cable, since the variation occurs by changing it.

**Comment by Floris497** [comment]
Try to keep the cable away from other cables a bit see what happens.. and buy an as short as possible cable :) hope you get it working!

**Comment by gitpsychedelic** [comment]
I forgot because I asked before but if HDMI2.0 doesn't work on Sierra what is the point of this patch on Sierra? If you always need the adapter that is.
(I had the Club3D, worked for 8 months, now it gives me blinking on windows, blue screen on macOS, removed it and turned the 4k TV back to 4k@30Hz and works on HDMI while I think about what other brand of adapter to buy, probably they all die sooner than later judging from Amazon reviews).

**Comment by Floris497** [comment]
As far as I know Club3D is making some quality products.. if it's 8 months new, I'm sure it's covered under warranty? (I've not been so active on the patch lately, I've lost control of the hundreds of possible configurations with nvidia amd intel mackbook macmini Imac hackintosh..

**Comment by gitpsychedelic** [comment]
Yeah pretty sure covered in guarantee but don't live in the US so it either works or not, cannot send anything for guarantee but anyway I lost trust on Club3D.
Leaving that aside Florian I'd appreciate if you enlighten me of the point of this patch in Sierra. I'm currently back to the old 4k@30Hz (have a second 2k@144hz monitor with obviously native DP input so it's not so bad) but while I order a new adapter from a different company and stuff, the patch wouldn't let me run 4k@60Hz via HDMI right? So what is it good for really?
