### ISSUE TITLE
Reinstalled OS - now reapplying patch doesn't work. 

### ISSUE THREAD

**Issue by Solarity01** [Floris497/mac-pixel-clock-patch-V2#21]
My patch was working fine until last week when I decided to clean install my OS on my Mac Mini 2012. Now the patch will not work and I get the dreaded black screen every time. I've wrecked my brain, I've bought replacement cables and adapters and nothing works.

**Comment by Floris497** [comment]
Oh it doesn't really matter where you open your issue, did you disable SIP?

**Comment by Solarity01** [comment]
Yeah, SIP is disabled. Patch says it detects unpatched IOKit and then patches it. After reboot and SwitchResX configured I get black screen.

**Comment by Floris497** [comment]
At this point i have no idea why it is not working for you :(..

**Comment by Solarity01** [comment]
Could this be an issue?

  Version:	10.10.5.2
  Last Modified:	2/26/16, 11:30 PM
  Bundle ID:	com.apple.nvidia.driver.NVDAGK100Hal
  Loaded:	No
  Get Info String:	NVDAGK100Hal 10.10.5.2 310.42.25f01
  Obtained from:	Unknown
  Kind:	Intel
  Architectures:	x86_64
  64-Bit (Intel):	Yes
  Location:	/System/Library/Extensions/NVDAGK100Hal.kext
  Kext Version:	10.1.0
  Loadable:	No
  Signature Validation Errors:	Kext signature validation error code -67061
  Dependencies:	Satisfied
  Signed by:	Unknown

**Comment by Floris497** [comment]
Yes.. This is correct.. If you patch the file.. The codesign is invalid. Thus the kext won't be loaded unless SIP is turned off all the time.
