### ISSUE TITLE
4k @ 30 hz

### ISSUE THREAD

**Issue by neemagha** [Floris497/mac-pixel-clock-patch-V2#210]
Hello -

I have a Hackintosh (EVGA Nvidia 950 GTX, monitor Dell P2415Q). I've installed and run the patch as instructed and when I launch the web-maxwells, it says that it doesn't recognize the drivers (running OS X 10.12.6 and Nvidia web driver 378.05.05.25f01). I bought a DP 1.2 cable to avoid the HDMI issues and have also used HDMI 2.0 cable without success. 

SwitchResX only shows 30 hz options amongst the HDPI selections.

Any help would be appreciated.

**Comment by Floris497** [comment]
Seems to be an issue with MST.. I have a monitor like that too..

**Comment by neemagha** [comment]
What is MST?

**Comment by neemagha** [comment]
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.6 build:16G29

     NVDAGM100HalWeb: d1ff18802f0ba85eaea624d384356acf
 NVDAGM100HalWeb.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Multi Stream Transport, is an Displayport standard that allows for tiled displays like the ine you have.. basically you have 2 monitors in 1 panel (left and right) with a single stream this screen can only go up to 30Hz

**Comment by neemagha** [comment]
Floris, thank you for responding. I'm confused because Dell's website specifically states: 

"4K UHD (2160p) 3840 x 2160 (DisplayPort: 60 Hz, HDMI: 30 Hz)"
http://www.dell.com/en-us/shop/dell-24-ultra-hd-4k-monitor-p2415q/apd/860-bbff/monitors-monitor-accessories

I guess I'll install Windows and see if it's capable of displaying at that resolution with 60 hz refresh rate. I specifically bought the monitor based upon the feature set... and avoided the whole HDMI situation accordingly.

**Comment by neemagha** [comment]
http://tanalin.com/en/blog/2015/05/dell-p2415q-review/

"SST and 60 Hz without MST

Unlike the 2014’s UP2414Q model, the new P2415Q model supports full refresh rate of 60 Hz via DisplayPort interface without using MST mode. This is proved out, in particular, by the fact of correct GPU-powered scaling of signal with resolution different from native monitor resolution — this was impossible with UP2414Q.

So, as expected based on the leaked user manual, the P2415Q monitor uses SST mode to trasfer data, while MST mode in this monitor is used as intended — for daisy-chaining of two 4K monitors operating at half refresh rate of 30 Hz. For daisy-chaining, the monitor is equipped not just with DP input (to connect a computer), but also with DP output (to connect a second 4K monitor to the first one)."

**Comment by Floris497** [comment]
Oh so then it's interesting.. look in the screens OSD to see if you can enable/disable SST/MST DP1.1/DP1.2 that could get you some better results..

**Comment by Floris497** [comment]
Oh and did you add a custom resolution with switchresx?

**Comment by neemagha** [comment]
Not many options on the Dell OSD setting. I can change the MST to be primary or secondary. 

I did try making the custom resolution but it doesn't work.

**Comment by mark3p** [comment]
Saw this in macrumors thread about your screen:

MST should be off in the monitor (it is off by default) to run it at 60hz. Monitor needs to be turned off before booting or restarting the Mac. Once the boot chime is heard, wait a few seconds just to be sure and then turn on the monitor using the power button. I'm running the monitor at the scaled 2560X1440 at 60hz which makes things nice and clear. If I need the bootscreen, one can change the MST setting to I believe MST Secondary (if one can't get into the menu, one holds the GREEN Checkmark for 8 seconds to change the MST settings) 

Update: 7-29-2017 One can also change the MST setting to secondary via the menu first before restarting (or during a OS update).
