### ISSUE TITLE
MacBook Pro(late 2016) with LG UD58PB 4K only 30Hz

### ISSUE THREAD

**Issue by tangticco** [Floris497/mac-pixel-clock-patch-V2#213]
Hi, I have used your patch with my LG 4K TV before and it worked. But now....

I use an MacBook Pro (late 2016) model with amd card. I use a USB-c to HDMI 2.0 with HDMI 2.0 cable. And the new monitor is LG UD58P-B which LG said it has two version 2.0 hdmi and supports 4K at 60Hz.’

I patch the coredisplay one and it still is 30Hz. How can I solve that?

**Comment by Floris497** [comment]
What changed? OS update?

**Comment by tangticco** [comment]
I don't think the OS changed. I can still achieve 4k 60Hz on my LG TV using the same adapter and cable......

**Comment by Floris497** [comment]
Is there more that 1 HDMI2.0 port? (some only have the 4k@60Hz on 1 of more ports)
Did you try setting the resolution in SwitchResX?
(I missed that you had a different monitor now)

**Comment by tangticco** [comment]
Thank you so much!!!! It's working now...but I am not sure if it is the port's problem since on LG's support page says 2 HDMI 2.0. However, when I changed to another hdmi port, it just show 60Hz

**Comment by Floris497** [comment]
No problem Enjoy :)

**Comment by tangticco** [comment]
Um....however, after I enable SIP, it seems that it backs to 60Hz...

**Comment by Floris497** [comment]
60 or 30?

**Comment by tangticco** [comment]
Sorry, back to 30Hz...I disable SIP again now to see if it is back to 60Hz

**Comment by Floris497** [comment]
Hm, no idea.. then maybe code signing didn't go well.. let me check tomorrow okay? (send me a message tomorrow to remind me)

**Comment by tangticco** [comment]
Yep......

**Comment by Floris497** [comment]
Cool :P

**Comment by tangticco** [comment]
So I am back with new Issue. I found that I turned on SIP and it worked perfectly! Thank you!
However, it seems every time I disconnected the monitor and MacBook, I have to reboot the laptop in order for the display to show up. The MacBook detects my monitor but the monitor just show no signal and went black.

**Comment by Floris497** [comment]
Try to change resolutions instead of rebooting maybe that can also do the trick?

**Comment by tangticco** [comment]
Em....weirdly, I unplugged every other I/O devices connected to my laptop and reconnect to the monitor. It just works.   Thanks anyway for the fast reply.
