### ISSUE TITLE
Applying Patch : Terminal Permission Denied

### ISSUE THREAD

**Issue by GaryAtTango** [Floris497/mac-pixel-clock-patch-V2#215]
Hi guys,

I'm trying to apply the patch as mentioned on 9to5, i've followed everything step by step, but when it comes to dragging the patch into terminal and then hitting return, it says "permission denied"?

Why is this, I have already disabled csrutil on.

The Gear:
Macbook 2016
LG 27UD68 4k

If you guys could give me a reason why this might be happening and how to fix it, it would be very much appreciated.

Thanks.

**Comment by Floris497** [comment]
What says permission denied? could you be a bit more specific?

**Comment by GaryAtTango** [comment]
In terminal, when I drag the file onto the terminal window, and then click return(enter), it then says permission denied at the end of the string, as if I don't have pemission to execute the patch, even though I am the administrator.

**Comment by Floris497** [comment]
Could you provide me with a screenshot?
