### ISSUE TITLE
No signal output above 3480x2160@30Hz via HDMI

### ISSUE THREAD

**Issue by mcp73** [Floris497/mac-pixel-clock-patch-V2#216]
First of all, thank you Floris497, for your work! I read through the threads but didn't see exactly my situation...

Using the CoreDisplay-patcher.command and SwitcherResX, i was able to successfully enable 3480x2160@60Hz via USB-C (DP pass-thru), however i can only get 3480x2160@30Hz via the HDMI 2.0 port.

Can anyone help with why i am limited to 3480x2160@30Hz:
1)  via the HDMI port
2)  when using the native drivers KBL drivers, AppleIntelKBLGraphics and AppleIntelKBLGraphicsFrameBuffer (spoofed SKL drivers give 3480x2160@60Hz via USB-C).

My specs:
 - NUC7i5BNK, integrated graphics description, page 23: 
https://www.intel.com/content/dam/support/us/en/documents/boardsandkits/NUC7i5BN_NUC7i7BN_TechProdSpec.pdf
 - Hackintosh, Mac OS 10.12.6 Sierra running spoofed AppleIntelSKLGraphics 10.25.17 and AppleIntelSKLGraphicsFrameBuffer 10.25.17
 - USB-C: working at 3480x2160@60Hz via Club 3D active adapter
 - HDMI: working at 3480x2160@30Hz, max supported resolution 4096 x 2160 @ 60 Hz, 24bpp, HDMI 2.0 spec
 - Display: Vizio M43-C1, port 5 3480x2160@60Hz

Thanks for thoughts on this 30Hz limit.

**Comment by Floris497** [comment]
So if I understand correct, it is working with `USB-C -> DP` but not with your internal HDMI2.0 port?

~Just to make sure you are using the right. HDMI input on your monitor? as some only accept the resolution on 1 specific port~ I just read that you use port 5 and that should work.. mhm for the moment I have no idea since I've not tested HDMI2.0 on my board.. no capable TV for it.. And at this moment I'm not sure if it works at all for hackintosh..

**Comment by mcp73** [comment]
Yes, I am getting 3480x2160@60Hz via USB-C -> Club 3D active adapter -> HDMI 2.0 cable -> Vizio M43-C1, HDMI port 5.

I only get 3480x2160@30Hz via NUC7 HDMI (2.0a spec) -> HDMI 2.0 cable -> Vizio M43-C1, HDMI port 5. Also, only 3480x2160@30Hz via both USB-C and HDMI when using native Kaby Lake graphics drivers.

So it sounds like CoreDisplay-patcher.command and SwitcherResX are working correctly, it may be some other limitation of MacOS since there is no problem getting 60Hz via HDMI port on this same NUC7 running Linux and Win10. The other thought is that no Apple hardware provides 3480x2160@60Hz via HDMI port - only via Thunderbolt/DP, so maybe there is a constraint there. 

Thanks again Floris497 for making this available to all of us. Maybe someone else in the forum have tried this and can comment.

**Comment by dinpin** [comment]
hey, pretty much the same situation with the native HDMI of my GTX 970. Both in Sierra and in High Sierra if the resolution is set the 2160p@60 it goes to sleep. It is as if the connection only work up until HDMI1.4 speeds.  


This tool has been saving my ass with my early HDMI2.0 setup, and for that a big thank you.

**Comment by Floris497** [comment]
New patch for High Sierra should be here soon :) (only need to do some testing)
