### ISSUE TITLE
Macbook pro 2013 stuck restarting

### ISSUE THREAD

**Issue by DannyKong12** [Floris497/mac-pixel-clock-patch-V2#219]
taking incredibly long to restart after applying patch 15+ minutes and still going usually takes <1 min

**Comment by Floris497** [comment]
Please restart holding cmd+v and check where it gets stuck

**Comment by oller** [comment]
I'm encountering this too on new touchbar macbook pro on latest Sierra. Any luck @dannykong12?

**Comment by oller** [comment]
Ok, error is and it's hard to read, font very small...
```
IOPPF: XCPM mode
IO80211 Interface: :updateReport _peerManager is missing
```

Has this bricked my macbook?

**Comment by Floris497** [comment]
Hm.. idk, what version of MacOS are you on? what you can do now is boot into recovery and reinstall MacOS

**Comment by oller** [comment]
how can I work out what version from recovery mode?

**Comment by oller** [comment]
there's no way to rollback the patch? I have to reinstall the os?

**Comment by Floris497** [comment]
Hm, I thought you might remember, but not 10.13 already right?
You can boot into single user mode, and place he CoreDisplay.BAK file over the CoreDisplay file.. it might work as well

**Comment by oller** [comment]
Updated previous comment with version. I ran coredisplay patch as described, no errors. I'm on touchbar macbook pro with Intel and radeon gfx cards.

**Comment by oller** [comment]
Thanks for prompt responses! do you have any docs for booting into single user mode and the full paths for the files you suggest swapping?

**Comment by oller** [comment]
Can I try the unpatch method, I'm not sure if the warning about updating applies? This is the first instance of trying to use this patch on this machine

**Comment by Floris497** [comment]
Hm.. if you can locate the patch file, yes you can use the unpatch command

**Comment by oller** [comment]
Bit of a journey that!  Back in now, succesfully went into single user mode, had to mount the disk to get write permissions and unpatched.

So back up and running, but of course still at 30hz.  Anyway, thanks for the prompt responses, and hope that debug error is useful.

**Comment by Floris497** [comment]
Hm.. so what configuration are you using?

**Comment by oller** [comment]
I just manually swapped back around `CoreDisplay.bak` and `CoreDisplay` so whatever the contents of what `.bak` is.  Happy to paste anything into a gist.  It's as if the laptop is back to before I'd done anything, still driving the 4k monitor at 30hz and no additional options in the display preference pane.

**Comment by Floris497** [comment]
I mean.. what cable what screen?

**Comment by MrToLLi** [comment]
Same issue as @DannyKong12 with same OS version, fixed by also booting into single user mode, mounting main drive with write permissions then running unpatch. First attempt was with HDMI cable, second attempt was with DisplayPort cable. Monitor is Samsung U28E590D. Using a late 2014 mac mini (intel iris).

**Comment by DannyKong12** [comment]
I'm on 2013 macbook 13'' screen is lg 25um58-p also 10.12.6 will try unpatching as soon as i get home

**Comment by DannyKong12** [comment]
can someone give me more specific steps to unpatch? Don't wanna mess anything up further

**Comment by MrToLLi** [comment]
1. restart holding `cmd+s` when you hear chime or see logo to boot into single user mode
2. wait for the prompt, then type `/sbin/mount -uw /` and hit `enter` to mount your drive with write permissions
3. `cd` into the directory where you downloaded CoreDisplay-patcher.command
4. type `./CoreDisplay-patcher.command unpatch` and hit `enter`

That did it for me :)

NOTE: you don't have to hit `enter`, a mere light press will suffice ;)

**Comment by MrToLLi** [comment]
@Floris497 below is the output of the command if it helps

```
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12.6 16G29.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: code object is not signed at all
In subcomponent: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.tbd
Closing..
```

**Comment by Floris497** [comment]
Hm.. that is weird...

**Comment by Thunderbottom** [comment]
Having the same issue as @MrToLLi, stuck on restart. Had the same output in the terminal when I ran the command.

**Comment by DannyKong12** [comment]
Fixed it by going to the path and just doing mv coredisplay.bak coredisplay

**Comment by Floris497** [comment]
I have no idea why there is this same problem popping up for so many people.. for me it works fine...

**Comment by MrToLLi** [comment]
@Floris497 what mac are you using and which OS version? If it's the same version perhaps if you give me your CoreDisplay file I could try patching it? Or maybe if you just give me your patched CoreDisplay file I could just drop it in? Or does it not work like that?

**Comment by Floris497** [comment]
I don't really understand the 'CoreDisplay.tbd' file... I'll have a quick look later.. I'm running 10.12.6 on a hack..

**Comment by MrToLLi** [comment]
ok cool, quite happy to test stuff as the mac I'm testing this on isn't my daily driver, just let me know :)

**Comment by ploddi** [comment]
Seems like I am having same issue with my Mac mini (late 2012) macOS 10.12.6 - got stuck on loading.

**Comment by DannyKong12** [comment]
I have the same monitor as you. Running unpatch or manually reverting the patch in single user mode will allow your computer to boot up again. As for your monitor, I have heard people using mini displayport/thunderbolt port for that monitor and having it work perfectly fine, so feel free to try picking one up from amazon. My monitor only works in bootcamp win10 so the port isnt the issue, but on mac its being recognized as a 1080p tv.. (DO NOT QUOTE ME ON THIS IM NOT 100% SURE dont blame me for making you buy a thunderbolt-hdmi adapter and it not working)

**Comment by ploddi** [comment]
I am using my Mac mini at office and we have plenty of **passive** DisplayPort-HDMI adapters and they do not help. Maybe some kind of active adapter needed.

**Comment by Floris497** [comment]
Ah.. looks like the patch wasn't really successful.. could you check what files are in the directory fir CoreDisplay?

**Comment by ploddi** [comment]
`./CoreDisplay-patcher.command status
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12.6 16G29.`

`./CoreDisplay-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.6 build:16G29

     otool CoreDisplay: 9a653ffdfb5e1bcfaa71412000d0b111
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: 188ac719b7f00e15c7ae23d0b97af669
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------`

`./CoreDisplay-patcher.command
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12.6 16G29.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: code object is not signed at all
In subcomponent: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.tbd
Closing..`

`./CoreDisplay-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.6 build:16G29

     otool CoreDisplay: 6708362921f852600e59e68c3e811eda
 otool CoreDisplay.bak: 9a653ffdfb5e1bcfaa71412000d0b111
           CoreDisplay: 3522132c94cef79e36aad7c138ce167f
       CoreDisplay.bak: 188ac719b7f00e15c7ae23d0b97af669

---- ENDING MD5 HASH SUMS -------`

**Comment by ploddi** [comment]
Cant load even with `SIP` disabled all time.

**Comment by Floris497** [comment]
Can you `ls -la`/System/Library/Frameworks/CoreDisplay.framework/Versions/A/`

**Comment by ploddi** [comment]
Unpatched:
```
drwxr-xr-x  6 root  wheel      204 Sep 27 12:28 .
drwxr-xr-x  4 root  wheel      136 Sep 26 17:40 ..
-rwxr-xr-x  1 root  wheel  1013872 Jul 15 07:37 CoreDisplay
-rw-r--r--  1 root  wheel    14366 Jul 25 21:52 CoreDisplay.tbd
drwxr-xr-x  6 root  wheel      204 Sep 26 18:21 Resources
drwxr-xr-x  3 root  wheel      102 Sep 26 18:21 _CodeSignature
```

**Comment by Floris497** [comment]
Hm.. verry interesting.. where does the .tbd file come from.. never seen it there

**Comment by Floris497** [comment]
Hm.. verry interesting.. where does the .tbd file come from.. never seen it there

**Comment by ploddi** [comment]
https://gist.github.com/ploddi/f4652cd73fc196936bde2adad39d9d2b

**Comment by ploddi** [comment]
Possibly developers tools related. I have Xcode 9 installed.

**Comment by michalpetrov** [comment]
unpatch, remove .tbd file, patch again, restart.

This fixed it for me.

**Comment by ploddi** [comment]
Solves my issue as well. After `.tbd` and patching code signing works correctly.

**Comment by jovanialferez** [comment]
@michalpetrov works for me as well. thanks! fyi, setup is hackintosh updated to 10.12.6

**Comment by DannyKong12** [comment]
Ive also just tested and unpatching fixes the boot up issue and the removing the .tbd file and repatching works perfectly, and I get full resolution on my monitor, so I'm closing this issue as resolved.
