### ISSUE TITLE
OSX 10.11.5 MD5

### ISSUE THREAD

**Issue by cnluzhang** [Floris497/mac-pixel-clock-patch-V2#22]
When I was 10.11.4, I patched successfully (disable SIP --> patch --> enable SIP), and today I have already updated to 10.11.5, and the MD5 is below (SIP enabled)

```
Model: MacBook (Early 2016)

---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

     otool IOKit: d8829f2234464985863c7a501c288547
 otool IOKit.bak: 769a955b82a16fde0f1ae41eb4bdff7f
           IOKit: a73dd1ed37da96000958bb781ce4ac15
       IOKit.bak: c5505ca2c70d3f4580c8034e1a107ab8

---- ENDING MD5 HASH SUMS -------
```
Thanks.

**Comment by mcphone2004** [comment]
After update to 10.11.5, mac mini (late 2012) cannot do 4K @ 24Hz

---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

     otool IOKit: 637f064f5d76492f7ac5479e6554caa6
 otool IOKit.bak: 769a955b82a16fde0f1ae41eb4bdff7f
           IOKit: 5e5e4edd26db71deedd31697fde4f105
       IOKit.bak: 50fef4db03f5680e83c6bbb969e3e85e

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
I have to look at it later.. I have little time today.. Thanks

**Comment by RiaanW12** [comment]
@mcphone2004 

on a different note - how were you able to get 24hz on your mac mini 2012? I ran the patcher succesfully with a normal Mini DP to Displayport Cable but it just failed - get a black screen or flickering. So I've ordered a Accell Active Mini DP to Displayport Adapter - hopefully this works.

**Comment by mcphone2004** [comment]
I am using a Seiki SE42UM, so my only option is to connect it with hdmi and use a Mini DP to hdmi adaptor.

**Comment by Floris497** [comment]
Get the club3d dp to hdmi2.0 adapter, currently the only one that does 4k@60Hz

I had no time to read most of what you said so i hope this helps you :p

**Comment by RiaanW12** [comment]
@Floris497 dont think I will be able to get 4k@60hz on the Mac Mini 2012 model though

**Comment by mcphone2004** [comment]
Mac Mini 2012 does not have enough bandwidth for 4k@60Hz.

**Comment by Floris497** [comment]
It must be able to do 40.. My 2011 model does 40Hz

**Comment by RiaanW12** [comment]
Interesting... If I knew this a week sooner I would have gone straight for the Club 3D one then, I will probably get one eventually for my MacBook Retina 13" Mid 2014 but I was able to obtain 52Hz with the patch.

**Comment by kenrucker** [comment]
Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

     otool IOKit: d8829f2234464985863c7a501c288547
 otool IOKit.bak: 769a955b82a16fde0f1ae41eb4bdff7f
           IOKit: a73dd1ed37da96000958bb781ce4ac15
       IOKit.bak: 50fef4db03f5680e83c6bbb969e3e85e

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Yep.. I need to update it, I'll do it when i have time later this day :)

**Comment by adrieno** [comment]
@Floris497: Just installed update for El Capitan 10.11.5 ! And lost one hour to search for a solution because can't find anymore the 2560x1080 resolution. But I'm happy to read your last post and see the solution was not far :) Thx and congratulations for your work ! Very easy solution (Before I used SwitchResX) ;) You think we will have a news IOKit-patcher for 10.11.5 during the next days ?

**Comment by cirodevel** [comment]
I had the same problem. Follow the output:

SIP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

     otool IOKit: d8829f2234464985863c7a501c288547
 otool IOKit.bak: 769a955b82a16fde0f1ae41eb4bdff7f
           IOKit: a73dd1ed37da96000958bb781ce4ac15
       IOKit.bak: 50fef4db03f5680e83c6bbb969e3e85e

---- ENDING MD5 HASH SUMS -------

Thanks

**Comment by kencar** [comment]
10.11.5 MD5
NVDAGK100Hal:840234288d56c2171e75083dfdd6b1d9
IOKit:a73dd1ed37da96000958bb781ce4ac15
Thanks a Bunch!

**Comment by adrieno** [comment]
@Floris497 there is no problem to make a donation on Paypal for your work ! I understand this take a lot of time to develop ! Just want to know when it will be available ? (If I wait 1 or 2 two days with this issue) or if I go back with my last save to 10.11.4 until it will works if it takes more days to develop it :)
Thk U so much !!!

**Comment by RiaanW12** [comment]
Got the Accell adapter and it works at 30hz but only in version 10.11.4... Updated to 10.11.5 and not working anymore as confirmed previously. Busy reloading 10.11.4

**Comment by Floris497** [comment]
Are you sure? I didn't update the script for 10.11.5 yet..

**Comment by RiaanW12** [comment]
100% positive, seems like the adapter only works @ 4k with the script.

**Comment by Floris497** [comment]
So I'm now updating my machine to 10.11.5, so the script should be updated within an hour

**Comment by adrieno** [comment]
The best news today !!! @Floris497 : do you want to marry me ? :D

**Comment by adrieno** [comment]
don't know if it's normal but I have errors ! :/

/Users/adrienobjois/Downloads/IOKit-patcher.command: line 5: syntax error near unexpected token `newline'
/Users/adrienobjois/Downloads/IOKit-patcher.command: line 5: `<!DOCTYPE html>'
iMac-de-Adrien:downloads adrienobjois$

**Comment by Floris497** [comment]
That is entirely true! You need to download the raw version not the HTML page :) download the zip that works best!

**Comment by Ryloth** [comment]
Worked without a hitch, doing 2560x1080 @60Hz on my Acer V3-571G. Thanks!

**Comment by adrieno** [comment]
ohhh what a dumb I am !!! I was sure it was not normal !!! thx

**Comment by RiaanW12** [comment]
stupid question but is xcode essential to have when running the patch?

**Comment by Floris497** [comment]
Ehm.. I think so.. But when I read it I wasn't sure again.. Both codesign and otool are in that package but I have wondered for a long time if it was necessary.. To install that package or that it is existent on every mac by default.. I'm not printing that message, when the script call otool or codesign it prints this. Hope this info helps you :p

**Comment by cirodevel** [comment]
Man, you are the guy! Thanks from Brazil!

**Comment by Frenchie64** [comment]
Hi Floris,
Update to 10.11.5 recently and applied your new IOKit-Patcher for 11.5. It says "Unknown version of IOKit found.."

---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
     otool IOKit: d41d8cd98f00b204e9800998ecf8427e
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: a73dd1ed37da96000958bb781ce4ac15
       IOKit.bak: NO FILE (this is okay)
---- ENDING MD5 HASH SUMS -------

Any ideas? Thank you

**Comment by Frenchie64** [comment]
Ok, found it. xcrun was missing. I installed the XCode’s Com­mand line tools with the following terminal command:

xcode-select --install

Everything went smoothly after that.
Thanks again for your script Floris.

**Comment by Floris497** [comment]
Good to hear that it's working :)

**Comment by RiaanW12** [comment]
think I'm doing something wrong today...

Output...

SIP looks to be disabled, all good!

(otool) Detected patched IOKit on OS X 10.11.5.

**Comment by Floris497** [comment]
No other output?

**Comment by RiaanW12** [comment]
nothing else, really baffles my mind as well! However I am getting 4k @ 30Hz now without the Accell adapter, I also ordered a Mini Displayport to Mini Displayport cable for my monitor and just tried to see if I had any luck now and it actually worked, had a small issue where I just had to switch back to normal res and then 4k and everything is fine previously I used and tried Mini Displayport to Displayport and it didn't work and it was the same brand, Startech with same spec just different connectors.

**Comment by Floris497** [comment]
Try downloading the script again :) maybe that helps..

**Comment by donald-jackson** [comment]
Anyone know how to update this script to include Nvidia updated versions ?

Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading

Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

     NVDAGK100Hal: 62e429ce9f61893a5b7379b0b0b9839f
 NVDAGK100Hal.bak: 840234288d56c2171e75083dfdd6b1d9

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
I'll do that today :) i hope it's still the same.. I think you can force it tho. Look into the ```nvid.command -h```

**Comment by donald-jackson** [comment]
hehe thanks - I am using a hackintosh so I'm scared to try anything too risky as to break it :) will wait for someone smart to sort it out ;)

**Comment by Floris497** [comment]
Meh.. It will be fine :) I've not seen a chance since 10.9.5 i think :p

**Comment by byally** [comment]
Same thing here:

Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

     NVDAGK100Hal: bba91da3d3208e36c24c7a64562c6eed
 NVDAGK100Hal.bak: 62e429ce9f61893a5b7379b0b0b9839f

Floris497, really, I have no idea how to patch it or whatever myself. 
Can you please help us? Thank you!

**Comment by Floris497** [comment]
Yes! I can help you guys in a few hours

**Comment by byally** [comment]
I patched IOkit successfully, got more resolutions, using 4k lg tv. But I cannot get 60 hz on 4k resolutions! That is the main problem. So I guess nvidia patching is necessary. Under windows my video card is capable for 60 hz 4k resolution, I already checked.

**Comment by Floris497** [comment]
I Just added 10.11.5.

I can't test it, but i'm fairly sure it works!

**Comment by byally** [comment]
Thank you so much! Just applied, tomorrow morning will check at my office! Great service to hackintosh community!!

**Comment by Floris497** [comment]
Im happy that I can help you all with this, I would never have imagined that this tool would help any hackintosh users! But that's great!

**Comment by byally** [comment]
So tried applying patch, still can't get 60 hz, only 30! Any ideas? It is GTX 980M, laptop, and under windows it gives 60 hz 4k, no way under mac! Any ideas?

**Comment by Floris497** [comment]
Applied both patches?

**Comment by byally** [comment]
Yes, both applied. IOkit patch gives lot of resolutions in the SwitchResX, I applied it initially, and with no errors. Then today applied Nvidia patch successfully, but still no 60 hz in switchres. And I have another question - I have also macbook pro 2015 15" with AMD R9 M370X 2Gb, I tried with office tv, and I am getting correct hidpi resolutions, but only 30 hz. Is it possible to get 60 hz on this videochip?

**Comment by Floris497** [comment]
I will look if i can update for AMD.. But i had little luck so far finding the lock.. I didn't have much time lately to find it :/ I will see what i can do this weekend, but no promises

**Comment by nuhll932** [comment]
Hi, 10.11.6 beta1 (15G7a) was out two weeks ago, would you consider add support for it? Thanks!

**Comment by Floris497** [comment]
Yep.. Let me look into it later today. But I'm not updating my mac to that version now.. You can try and force the patch.. As explained in the readme :)
