### ISSUE TITLE
Unable to login after unpatch the IOKit patch 

### ISSUE THREAD

**Issue by diophung** [Floris497/mac-pixel-clock-patch-V2#220]
So I unpatched it by restoring the file at `/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit.bak` to be `System/Library/Frameworks/IOKit.framework/Versions/A/IOKit`.

The process failed midway, Finder hang and I have to reboot.

After that, I was unable to login anymore. When I boot into Recovery mode, I can't find the *.bak file at System/Library/Frameworks/IOKit.framework/Versions/A/ anymore, but still not able to log into Mac OS 10.12.6.

How do I fix it now?

**Comment by Floris497** [comment]
Hm, unlatch should be done using `patch.commmand unpatch` or `mv IOKit.bak IOKit` otherwise it will crash your system and it will be impossible to fix it without installing the OS again..

**Comment by diophung** [comment]
:( I learned it the hard way. Just have to restore the OS from backup

**Comment by Floris497** [comment]
I've learned it the hard way too.. didn't realize Finder relies in IOKit like that..
