### ISSUE TITLE
Coredisplay patch code signing

### ISSUE THREAD

**Issue by sieula** [Floris497/mac-pixel-clock-patch-V2#221]
So I was having this problem that I cannot fix while patching the framework:

/System/Library/Frameworks/CoreDisplay.framework/Versions/Current/CoreDisplay: replacing existing signature
/System/Library/Frameworks/CoreDisplay.framework/Versions/Current/CoreDisplay: code object is not signed at all
In subcomponent: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.tbd

And then when I restart the display is blank. Any ideas?
This is with mac version 10.12 initial release

**Comment by ploddi** [comment]
Having same issue on Mac mini (late 2012). Updated to 10.12 from 10.11.

**Comment by JunyuT** [comment]
I had to `/sbin/mount -uw /` before I could patch it correctly.

if your display is blank, reinstall osx without wiping, unless you want to wipe, of course. Update to whatever version you want, run that command, then patch. If anything goes wrong, quickly replace the CoreDisplay.bak with `mv CoreDisplay.bak CoreDisplay` before restarting.

**Comment by Floris497** [comment]
Not sure how this happened it does happen sometimes..
