### ISSUE TITLE
Hackintosh 10.12.6 - 4k only 30hz problem - win10 4k60hz works fine

### ISSUE THREAD

**Issue by artcheone** [Floris497/mac-pixel-clock-patch-V2#223]
i have ASUS GeForce [GTX1060 strix](url+https://www.computeruniverse.ru/products/90660106/asus-geforce-gtx1060-strix-gtx1060-6g-gaming.asp) 6gb with 2 hdmi output 

and ASUS prime[ Z270-A](url+https://www.computeruniverse.ru/products/90679673/asus-prime-z270-a.asp) motherboard

i have installed macos sierra and windows 10 on another ssd
i have LG 40UF771V 4K TV and **when i use LG on Windows 10 i have perfectly worked 2160p - 60hz via HDMI on my GTX1060**

**when i boot Hackintosh** i have **only 2160p 30hz** (4k) 

i have installed nvidia web driver 378.05.05.25f01 (up to date)
and CUDA driver version 9.0.197
i tried to patch with pixel clock patch v2 CoreDisplay and I0Kit
i have installed SwithResX and when i chose 4k 60hz i have only Black screen
i have 2 monitors and thats why i can experiment with black screen

please, help me get 4k60hz on my hackintosh

**Comment by artcheone** [comment]
gtx 1060 have hdmi 2.0b
lg 4k have HDMI ultra HD mode deep colour 4K 60 HZ ( 444 , 422, 420)
hdmi cable - ver 2.0

**Comment by artcheone** [comment]
Last login: Mon Oct 16 23:33:47 on ttys000
/Users/artcheonedesk/Downloads/mac-pixel-clock-patch-V2-master/NVIDIA-WEB-PASCAL-patcher.command ; exit;
iMac-artcheonedesk:~ artcheonedesk$ /Users/artcheonedesk/Downloads/mac-pixel-clock-patch-V2-master/NVIDIA-WEB-PASCAL-patcher.command ; exit;
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading

Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.6 build:16G29

     NVDAGP100HalWeb: dc88b21c3869f41e24637fc32b06edc3
 NVDAGP100HalWeb.bak: dc88b21c3869f41e24637fc32b06edc3

---- ENDING MD5 HASH SUMS -------
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Процесс завершен]

**Comment by Kaygusuz91** [comment]
Same issue in High Sierra with Nvidia Web Driver 378.10.10.10.15.117. Lilu + CoreDisplayFixup applied but nothing changed.

**Comment by Floris497** [comment]
New patch will be made available soon :)
