### ISSUE TITLE
Tried Coredisplay, doesn't change anything

### ISSUE THREAD

**Issue by Thrashkal** [Floris497/mac-pixel-clock-patch-V2#225]
Hello,
I have a macbook pro with an HDMI connected to my 4K display.
I followed every step in the tutorial but nothing changed, the "30 hertz" still displayed and the animations are still stuttering.
I got this when executing CoreDisplay.command
<img width="566" alt="screen" src="https://user-images.githubusercontent.com/5334069/32389440-e31f3882-c0ca-11e7-909f-6a5b98474eb9.png">
Can someone help me?

**Comment by Thrashkal** [comment]
Can someone help me? Or am I the only one to have this issue on High Sierra?

**Comment by Floris497** [comment]
The HDMI connection is HDMI1.4 and not compatible with any 4K display.. try to use DisplayPort if possible

**Comment by Thrashkal** [comment]
I understand :/ would something like this work in this case? https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.co.uk%2Fulk%2Fitm%2F192135225129
I do have a displayport cable, a connector to the screen and a mini displayport connector in my macbook pro so this would be a solution if it supports 60hz

**Comment by Floris497** [comment]
If your screen has DP just buy a mDP to DP cable :) and what year is your mac?

**Comment by Thrashkal** [comment]
I already have a DP delivered with the screen that's why I'd take the adapter :)
My mac is late 2014, the 15"

**Comment by Floris497** [comment]
Anything I can help with still? I'm trying to close issues feel free to reopen if you need any help :)
