### ISSUE TITLE
High Sierra stuck on launch after patch

### ISSUE THREAD

**Issue by che1404** [Floris497/mac-pixel-clock-patch-V2#226]
Hi!
I ran the patch on my Mac mini (2014) with high Sierra installed. Everything went OK according to the console log. 
After rebooting the loading indicator stays forever and nothing happens. 
I rebooted with command-R, entered the terminal, ran the patch with with the unpatch parameter, but it said that the system was not previously patched??
I really need to recover all my files. 
Any help?
Thanks!

**Comment by Floris497** [comment]
Please use lilu, look in the other issues for more info

**Comment by che1404** [comment]
Hi!
Thanks for your response. I think that’d be too advanced for me. 
If I reboot with Command-R and reinstall the OS, will it remove my user files? Or will it run a fresh install?
How can I restore the OS preserving my files?
Thanks!

**Comment by Floris497** [comment]
Running a fresh install with either cmd+r or from the installer app will preserve all user files. Although it's still recommend to have a backup.

**Comment by che1404** [comment]
Hi!
Finally I reinstalled and the files are there... phew!
Is there any step by step guide on how to run the patch properly on High Sierra using lilu? Anything for dummies (like me)?

**Comment by Floris497** [comment]
https://github.com/PMheart/CoreDisplayFixup Here should be some info

**Comment by che1404** [comment]
Hi! 
Thanks for the link, but I wouldn’t know where to start reading the information provided on the link.

Thanks anyway!

**Comment by Floris497** [comment]
New patch will be ready soon after a bit of testing
