### ISSUE TITLE
MacBook Pro (15-inch, 2016) Sierra + Samsung 4K HDMI [Solved]

### ISSUE THREAD

**Issue by mmontag** [Floris497/mac-pixel-clock-patch-V2#227]
Hi, I'm posting here in desperation since this issues board seems to have a lot of smart people around. I cannot seem to get past 30 hz 3840x2160 from my Mac with a Samsung 4K TV. When I hook the display up to a Windows 10 computer, it pushes 4k @ 60 hz by default. 

I have a USB-C to HDMI 2.0 cable.  I have reset the PRAM. I have updated the Samsung TV firmware. I have tried the SIP disable, install CoreDisplay patch, mess around with SwitchRes. But I can't get SwitchRes to do anything.  Maybe it's because it is shareware and my 14 days expired? Not the biggest fan of SwitchRes, frankly. The custom resolutions I entered are stuck on "Not installed".

Anyone have any tips for this combination?

**Comment by Floris497** [comment]
Even after your 14 days you can have 2 custom resolutions I think.. make sure you save the resolutions before restarting and having SIP disabled. Let me know of that works

**Comment by turner-btp** [comment]
@mmontag I had some success by creating a new user and installing Switchresx.  I can at least get the resolutions to save.  But I cant get the 60Hz resolutions to work, I just get a black screen.  But I am on High Sierra and I don't think the Core Display Patcher is ready for it yet.  Don't know if that will help...

**Comment by turner-btp** [comment]
@mmontag That is exactly what I had working on Sierra.  I do caution you to not upgrade to High Sierra, as without the CorePatcher, that setting will not function.

**Comment by Floris497** [comment]
There will be a new patch soon for High Sierra :)
