### ISSUE TITLE
Does this work anymore for anyone? MacOS 10.13.1 + MBA 2017

### ISSUE THREAD

**Issue by vonkoda** [Floris497/mac-pixel-clock-patch-V2#228]
Repost from Mac-Forums. Just wondering if Im chasing a dead end at the moment, thanks!

> 
> 
> Brought my "surplus" home monitor in to work with my MBA, which I thought would work properly at 4k after reading so here:
> https://www.macrumors.com/2015/03/25...-display-60hz/
> and 
> https://9to5mac.com/2016/06/04/how-t...-2016-macbook/
> (tried both CoreDisplay and IOKit patches AND SwitchResX).
> Both display **"Unknown version of IOKIT** (or CoreDisplay, respectively)".
> 
> 
> However its stuck at 30Hz which is pretty painful. I know the HD6000 integrated graphics can do 60Hz 4k. 
> 
> Monitor is a (admittedly basic but functional) 28" 4k "Electriq EIQ-284KMB" display, which has 2x DP inputs (and 2x HDMI). 
> Im using a mDP to Full DP adapter to the standard Full DP cable. 
> 
> 2017 MBA with MacOS 10.13.1

**Comment by Floris497** [comment]
Update will be there in a little time (got it working already)
