### ISSUE TITLE
MD5 sums for MAC OS 10.13.1 (High Sierra)

### ISSUE THREAD

**Issue by JeffreyCSmith75** [Floris497/mac-pixel-clock-patch-V2#229]
I updated to MAC OS 10.13.1 before checking if the pixel clock patch was available. My bad! Looks like it has not been added yet so here are the MD5 sums for 10.13.1:

jeff@Jeffreys-MacBook-Pro:MAC Pixsel Clock Patch $ sudo ./IOKit-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.13.1 build:17B48

     otool IOKit: 9ecc90a411976081c6120594a017b898
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: abd8e7db073e89c07af39decdcd93c43
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
jeff@Jeffreys-MacBook-Pro:MAC Pixsel Clock Patch $ sudo ./CoreDisplay-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.13.1 build:17B48

     otool CoreDisplay: 0c369927b33af75756cba3ac40e2f3e2
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: a5d3052c9ae2c8f798666671484472ff
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

I don't think you need the sums for the IOKit patcher but I included them anyway.

If you need anything else to update the patch kit please let me know.

Thanks much,
Jeff

**Comment by Floris497** [comment]
Hey, so since 10.13 the patch is partly broken, and I'm still trying to figure it out. It's working but also breaking copy/paste (currently I'm quite busy so have little time to work on it :/) if you have a Hackintosh you should be able to use the patch with Lilu

**Comment by JeffreyCSmith75** [comment]
OK, I'll give that a shot. I assume that if I go the Lilu route copy/paste will not be broken?

**Comment by spencerjason** [comment]
I've been running the Lilu route since High Sierra went official and except for a few apps, I've had no problems. I was hesitant but did push through the update for 10.13.1 and it's still working.

I'm running a Late 2012 Mac Mini with HD 4000 graphics at 2560 x 1080 @ 60Hz. 

There are some video/graphics issues in apps like Chrome, but I switched to Canary and they are gone. I've also read a lot about that issue across the board, so it's possible that's unrelated to the video driver.

**Comment by marnovo** [comment]
Just for those who come here and know not what Lilu is and how to get it:

- Lilu: https://github.com/vit9696/Lilu
- Lilu Plugins: https://github.com/vit9696/Lilu/blob/master/KnownPlugins.md
- CoreDisplay plugin: https://github.com/PMheart/CoreDisplayFixup

**Comment by Floris497** [comment]
Patch for Mac mini on the way :) (got it working need some time to test)
