### ISSUE TITLE
macbook air, HD Graphics, No video, Black screen

### ISSUE THREAD

**Issue by devM4x** [Floris497/mac-pixel-clock-patch-V2#230]
Hi, i found your script in google and try to executing script, result is black screen and no signal, if i put away it just artefacting picture.

what i need: i want connect my notebook (macbook air 2012) to 4k TV LG with resolution (2560x1440), everything work without patch (with SwitchResX) but picture (fonts if i want some coding) is very ugly  and not readble (more pretty is 1920x1080. 

i try to execute patch but just make no signal and only have blackscreen .

**Comment by rvprasad** [comment]
After upgrading to High Sierra, I too experienced blurry fonts on 2560x1080@60Hz external display via HDMI.  Following [this advise](https://gist.github.com/adaugherity/7435890) fixed the issue.
