### ISSUE TITLE
Can the patch macOS High Sierra work?

### ISSUE THREAD

**Issue by Ranger007** [Floris497/mac-pixel-clock-patch-V2#232]
Can the patch macOS High Sierra work?  thanks!

**Comment by Floris497** [comment]
On Hackintosh: yes, on genuine mac: Not yet

**Comment by Ranger007** [comment]
I'll give you feedback on the test at macOS High Sierra 10.13.1 Hackintosh!  Thank you for your reply

**Comment by isosa28** [comment]
Floris, 
on a 10.13.1 hackintosh are we running patcher.command v3?

**Comment by Floris497** [comment]
No, hackintosh is Lilu.kext and CoreDisplayFixup. It should be somewhere in the issues

**Comment by isosa28** [comment]
Thanks Floris,
I had no luck for on hackintosh, the ID 16260006 for the hd5500 is not getting my internal LCD to work, only getting video of the HDMI Port.
I thought it was a 4k patch issue.

**Comment by Floris497** [comment]
I've got it working for me now.. some testing and I'll publish the new patch :D
