### ISSUE TITLE
Can this work with Intel Iris Plus Graphics 650?

### ISSUE THREAD

**Issue by RichardSuen** [Floris497/mac-pixel-clock-patch-V2#233]
My macbook pro is 13 inch 2017 version with bar OS 10.13.1
When connected to a 4K display can only use 4K@30 but not @60
I tried this script but not work, it's the problem with my graphics or my OS?

**Comment by Floris497** [comment]
What cable/adapter are you using?

**Comment by RichardSuen** [comment]
Hi Floris,
I use a type-c to DP cable, this cable support 4k@60hz
I saw some people use 15 inch macbook pro 2017 can use 4K@60hz without any script
So I guess it's the problem with this Intel Graphics

**Comment by RichardSuen** [comment]
But from the page of Inter Graphics I found that this Graphics can support 4K@60hz
Maybe it's still the problem of apple?

**Comment by Floris497** [comment]
For DP it should work without a problem.. have you checked SST MST (or DP1.1 vs DP1.2) settings in the monitor? I think there is still some problems with MST in MacOS :/ (for now the patch is working but also breaks some other stuff including copy paste leaving the mac in unusable state)

**Comment by RichardSuen** [comment]
I have set my monitor to DP1.2, but still 4K@30hz is the max..

**Comment by RichardSuen** [comment]
Is this the problem with my Graphics is Iris XXX but not HD XXX?
Or it's just the problem that my MacOS is 10.13.1 that have not been supported?

**Comment by RichardSuen** [comment]
After I uninstall the SwitchResX I can use 4k@60hz
I don't know how this happen
Still thank you, Floris

**Comment by Floris497** [comment]
Enjoy :)
