### ISSUE TITLE
doesn't recognize CoreDisplay in High Sierra 10.13.1

### ISSUE THREAD

**Issue by mbze430** [Floris497/mac-pixel-clock-patch-V2#234]
SIP looks to be disabled, all good!

Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.13.1 build:17B1003

     otool CoreDisplay: 0c369927b33af75756cba3ac40e2f3e2
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: a5d3052c9ae2c8f798666671484472ff
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

trying to patch the CoreDisplay (Hackintosh iGPU HD 4600 Desktop) so I can use 3840x2160p on HDMI or DP with Samsung KS8000 4K HDR TV.

**Comment by tuxtard** [comment]
You can apply the patch manually and thus avoid MD5 Hash check. Open the CoreDisplay-patcher.command and look for the v4 patch section, then copy the commands to your terminal. 

Be advised that I tried this on 10.13.1 with laptop version of Intel HD 4600 and got black screen after reboot.

**Comment by Floris497** [comment]
Patch 4 is not functional now.. and indeed gives black screen.. I've got a new patch working on my computer now.. so expect it soon after some testing :)
