### ISSUE TITLE
Can't patch IOKit after 10.11.6 (15G18013) update

### ISSUE THREAD

**Issue by chaosboylove** [Floris497/mac-pixel-clock-patch-V2#235]
Hi,
I'm a newbie on github.
I get the "Unknown version of IOKit found.." when I try to apply the IOKit patch
after the latest security update.
I was using it to enable HDMI 2.0 support on a non-EFI Maxwell card.
Is there any chance fix it?
Thanks in advance.

**Comment by naudin70** [comment]
Hi,
I don't know github also.
I get also "The unknown version of IOKit found" when i try to apply the IOKIT Patch.
Same problem than you with same Security update for El Capitan.
Have you an idea how to fix this problem ?

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G18013

     otool IOKit: aee2e3c30a213cf4299497a02da5aa1e
 otool IOKit.bak: 630fd968d68a0255c790e3af60c3dd86
           IOKit: 03820d62ca1ffbbe7eed0e2ad3e5b101
       IOKit.bak: 972287f63601ee522401a000eaf02a36

Thanks

**Comment by chaosboylove** [comment]
I suppose that it's a minor issue.
I think that we got to add the OS version string in the script,
but I'm not an expert so It's better to wait for an official fix.

**Comment by Floris497** [comment]
It's the security update I suppose? Idk actually. You can force it as described in the readme :)

**Comment by chaosboylove** [comment]
I'm on a project and for now I put back a gt 120 (for mac) to drive the second monitor at full res.
I will try to force it as soon as I can.
Maybe can I ask you to clarify the steps? I'm not so skilled on terminal stuff.
Thank you so much.

**Comment by Floris497** [comment]
Please see readme, it's easy :) `CD.command patch v3` something like that
