### ISSUE TITLE
doesn't recognize CoreDisplay in High Sierra 10.13.2

### ISSUE THREAD

**Issue by dmatora** [Floris497/mac-pixel-clock-patch-V2#237]
`./CoreDisplay-patcher.command 
SIP looks to be disabled, all good!

Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.13.2 build:17C88

     otool CoreDisplay: 5f51331dce01f1ced84643f6c996e324
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: 0c3053f88efea40b5113ee33b5449c96
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
`
patches v1-v3 don't make any changes
patch v4 prevents system from booting (progress bar is stuck)

**Comment by Floris497** [comment]
Coming soon .. really soon
