### ISSUE TITLE
CoreDisplay md5 after latest High Sierra update

### ISSUE THREAD

**Issue by aShure** [Floris497/mac-pixel-clock-patch-V2#242]
➜  mac-pixel-clock-patch-V2-master 2 ./CoreDisplay-patcher.command patch v3
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 3
Password:
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
The code is still the same.. Patch did seem to run, but was probbably from the wrong version..
If you are running an new os run ./CoreDisplay-patcher.command md5 and ask the maintainer of this script to add support for your system
➜  mac-pixel-clock-patch-V2-master 2 ./CoreDisplay-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.13.1 build:17B1003

     otool CoreDisplay: 0c369927b33af75756cba3ac40e2f3e2
 otool CoreDisplay.bak: 0c369927b33af75756cba3ac40e2f3e2
           CoreDisplay: 803714ac33f49831692ca216850fc457
       CoreDisplay.bak: a5d3052c9ae2c8f798666671484472ff

---- ENDING MD5 HASH SUMS -------
➜  mac-pixel-clock-patch-V2-master 2

**Comment by aShure** [comment]
nevermind, just found v4 in the source code!

**Comment by Floris497** [comment]
:) enjoy
