### ISSUE TITLE
Is there a way to remove the patch?

### ISSUE THREAD

**Issue by irobydl** [Floris497/mac-pixel-clock-patch-V2#25]
Hi, is there a way to remove the patch without have to reinstall OS X? thanks

**Comment by Floris497** [comment]
Yes, it's in the readme

**Comment by irobydl** [comment]
oh, sorry, I only downloaded one file, not the entire package. thank you!

**Comment by EctoSlymer** [comment]
Can you please provide instruction for how to remove the Coredisplay patch v4 from 10.13.6? My Netflix now won’t play on external display due to HDCP error.

**Comment by Floris497** [comment]
What are you waiting for.. I already answered your question in the other topic. 44 minutes ago....
