### ISSUE TITLE
Problem with Macbook Air 6.2 HD5000

### ISSUE THREAD

**Issue by Omletfer** [Floris497/mac-pixel-clock-patch-V2#251]
Hi, 

I have a Macbook Air 6.2 with an HD5000. I also have an Asus PB287 4K monitor. It is connected to the mac via MiniDP, with an adapter.

I have applied the patch do CoreDisplay, and v4 was applied. 

Now I installed Switchresx and I cannot save a custom resolution with more than 3000 pixels in horizontal resolution. I always have the "Not Activated - invalid?" message.

Can you please help me?

Regards,

Telmo

**Comment by Floris497** [comment]
Asking in 1 place is sufficient ;)

**Comment by Floris497** [comment]
As reference for others looking for the same answer: https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/248#issuecomment-359776387

**Comment by Omletfer** [comment]
Hi Floris,

I was never able to do it. My mac book air is a early 2014 with an HD5000.

I just placed a comment on Github. Should we proceed the discussion here or on GitHud?

Can you please help me?

Thanks for your help.

Regards,

Telmo

Telmo Rui C. C. Fernandes, PhD
R&D Consultant
 
DigiWEST - Wireless and Embedded Solutions, Lda.
Zona Industrial dos Pousos - EN113
Cova do Homem, Pavilhão A
2410 - 201 Leiria
Portugal

Telephone:   +351 244 826 565
Fax:             
Email : telmo.fernandes@digiwest.pt <mailto:telmo.fernandes@digiwest.pt>

**Comment by Omletfer** [comment]
Thanks. I will only ask here.

Do you have any ideia what is the problem with my computer?

Regards,

Telmo

Telmo Fernandes <telmo.fernandes@digiwest.pt> escreveu em ter, 23/01/2018
às 12:48 :

**Comment by Floris497** [comment]
Please let's take it to the other issue, already closed this one :)
