### ISSUE TITLE
Unknown version of IOKit found..

### ISSUE THREAD

**Issue by prakhs123** [Floris497/mac-pixel-clock-patch-V2#259]
Hi, I am not able to get 4k @60hz even after running the script
The script didn't ask me for patching and said unknown version of IOKit found..
Here's the output

INMACC5L3H:~ gns9$ chmod +x /Users/gns9/Desktop/IOKit-patcher.command 
INMACC5L3H:~ gns9$ /Users/gns9/Desktop/IOKit-patcher.command 
SIP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.6 build:16G1212

     otool IOKit: 449aceaeea2662eeb2625fdf9473cd76
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: cd5e51ad1a6436bdc64d7d319520231e
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Use CoreDisplay patch :)

**Comment by prakhs123** [comment]
Hi, I have a work laptop and many things have been preinstalled in my laptop.
When I ran the CoreDisplay patch, my OS sticks at boot screen loading, after entering my credentials.

However, I can go to recovery mode and unpatch using terminal. How to unpatch CoreDisplay patch?

**Comment by Floris497** [comment]
Boot in single user mode (cmd+s on boot), Mount your drive as described there. Locate the patchfile `cd /Users/<your name/Download/` And run there: `sh patch.command unpatch`

If you need additional help please let me know.

But the thing that is happening most probably is an unintended resolution being selected that isn't supported by you screen.. you can fix this with loging in winter Remote Desktop or connecting it to some other display might work as well. Or resetting NVRam can work as well to get back to standard resolution.. but I'm not sure about the last one.

**Comment by prakhs123** [comment]
Hi, I have unpatched now, my laptop is booting up.

But how to get 4k @ 60 hz..

I have a 2017 Macbook Pro
Is it due to HDMI?
I have usb c to HDMI cable which outputs 4k @60 hz. But it doesn't seem to working I guess.
I think i need to get display port solution for it. and it will work out of box as read in internet.

**Comment by Floris497** [comment]
By any chance get USB-C to Displayport.. it should work out of the box way better.. HDMI2.0 has quite some compatibility issues with mac..

**Comment by XipSirK** [comment]
Hello.

I got the same problem after IOS update and I resolved it with these commands

./IOKit-patcher.command unpatch
./IOKit-patcher.command patch v6

**Comment by kataklops** [comment]
hi, any solution on how to get 4k 60hz in mac pro 3.1?
macos 10.11.6 with gtx680 and displayPort
