### ISSUE TITLE
../usr/bin/xcrun missing

### ISSUE THREAD

**Issue by Rsam7** [Floris497/mac-pixel-clock-patch-V2#260]
Hi there,
I'm getting the following error message when running coredisplay-patcher script:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
SIP looks to be disabled, all good!

(otool) Detected unpatched CoreDisplay on OS X 10.12 16A313a.
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 1
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: the codesign_allocate helper tool cannot be found or used
Closing..

Any suggestions? 
Running MacOs Sierra 10.12 | Intel Iris Pro 1536MB

Thanks

**Comment by Rsam7** [comment]
Fixed by:
xcode-select --install

**Comment by Floris497** [comment]
It prompts to install this, but you probably said no ;)

**Comment by Floris497** [comment]
Unpatch.. hm strange you are the second one today who has that.. what hardware do you have?

**Comment by Rsam7** [comment]
any documentation on how to unpatch? I have a 17in mac book pro with intel Iris pro. Thanks

**Comment by Floris497** [comment]
Yes, it says in the readme. But since you cannot login.. boot it single user mode (cmd+s) mount your driver as described there. Then find the patch file and run it with the option 'unpatch'
