### ISSUE TITLE
Unknown version of IOKit found..

### ISSUE THREAD

**Issue by slash83** [Floris497/mac-pixel-clock-patch-V2#28]
Macbook 12" 2015 
OSX 10.11.5

```
/Users/XXX/Downloads/mac-pixel-clock-patch-V2-master/IOKit-patcher.command status
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
SIP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
     otool IOKit: d41d8cd98f00b204e9800998ecf8427e
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: a73dd1ed37da96000958bb781ce4ac15
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```
Thanks for your help!

**Comment by Floris497** [comment]
You need to install the tools when prompted :) I think it's taking a signature from the error message instead of the actual file this way

**Comment by slash83** [comment]
thanks, I had to reinstall Xcode. Now your script installed without problems.

Unfortunately, I couldn't get to work with 1920x1080 at 60Hz. I am using a MacBook 12" 2015 (Intel HD Graphics 5300 1536 MB Graphics) and a HooToo USB-C to HDMI (2.0) Dongle on a 4K Samsung U28E850. So I guess the problem is that I would need a USB-C to Displayport instead - however maybe the 2015 MacBook won't be able to do it anyway. Just wanted to let you guys know...

Cheers

**Comment by Floris497** [comment]
Few days ago there was a nice article about this for the 2016 version. Did you try switchresx and make a custom resolution?

**Comment by cesarramos50** [comment]
Hi i had the same issue with the patch, after checking the files i noticed that there weren`t modified so i sudo the patch, checked again and it worked, rebooted my Macbook Pro and i could get my monitor working on 2560x1080 on a Lg Ultrawide

**Comment by slash83** [comment]
Hey, I did a sudo install, and if I do a status check, it also shows the patch as installed.

@Floris497 do you mean this article? http://9to5mac.com/2016/06/04/how-to-enable-4k-60hz-resolution-2016-macbook/

I did use SwitchResX. Here is a screenshot of my setup. 1920x1080 Hz installed via SwitchRes but the System Profiler shows 30Hz (and I also see it is 30Hz with my eyes) ... bummer no 60Hz 4k for me...
![setup](https://cloud.githubusercontent.com/assets/12987207/15969147/f846443c-2f2e-11e6-9518-bdb8f87a1ba2.jpg)

**Comment by Floris497** [comment]
You need to put 3840x2160 in switchresx it will give the option of 1920x1080 HiDPI in the "current resolutions" tab try to see if 40Hz will work :) it's better to watch but not as demanding as 60Hz

**Comment by slash83** [comment]
Thanks Floris, for your kind advice. I set it to 3840x2160 in switchresx. However, I don't get the option of 1920x1080 HiDPI and also I don't get more than 30Hz tab to select from. :-/

**Comment by Floris497** [comment]
It looks like that adapter is HDMI1.4.. So not able to do 4k@60Hz.
This one should be able to work.. but if it actually works.. I have no idea..
https://store.google.com/product/usb_type_c_to_displayport_cable

**Comment by slash83** [comment]
I am using this adapter: http://www.hootoo.com/ht-uc001-usb-type-c-hub-hdmi-4k-adapter-apple.html Somewhere I read it has HDMI 2.0, but I can't find that anymore. I read elswhere that no Apple Laptop actually supports HDMI 2.0. So I guess I would need that DisplayPort cable that you are suggesting.

**Comment by Floris497** [comment]
while it is true that none of the apple laptops support HDMI2.0 even when using an DP to HDMI2.0 adapter. the IOKit patch makes it work :)

If you choose to buy that cable and test it, please tell me if it works or if you find any problems.

**Comment by slash83** [comment]
interesting! will do, thanks!

**Comment by Floris497** [comment]
Got this to work thought?

**Comment by slash83** [comment]
thanks for your message. No, no 4K for me. I guess the first version MacBook simply isn’t capable of that…

**Comment by slash83** [comment]
Hi floris,

are you aware of any of your patch users able to get a mac mini up and running using 4K at 60Hz?

As we chatted before.. I am stuck with my MacBook 12” Early 2015 and can not get 4K at 60Hz running. So I got this 4K monitor standing around and I need a machine to hook it up with. So I was thinking of getting a mac mini. Whats your experience on that?

Cheers,

Marcel

**Comment by Floris497** [comment]
Hm I think the newest Mac mini's can do it.. but animations will not run that well, as you could understand. I don't think Mac mini's are that powerful anymore these days.. but I have to check the specs. I am able to get 4k@40Hz out of my Mini 2011.

**Comment by serkansokmen** [comment]
Same issue on MacBook Pro (15-inch, Late 2016) 
macOS Sierra Version 10.12.2 (16C67)

```
SIP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.2 build:16C67

     otool IOKit: 16edb16d18d52003e010bdcd4070463d
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: df88c0fa7806c6515f0e256f7eec2593
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```
