### ISSUE TITLE
Please add MacBook Air Mid-2013 (OSX 10.10.5) 4k Resolution Support

### ISSUE THREAD

**Issue by qwertyfat** [Floris497/mac-pixel-clock-patch-V2#282]
I have followed the steps to disable SIP, use IOKit Patcher and finally re-enable SIP. After the patch the maximum available resolution in Apple's external display preferences and SwitchResX is 2560x1440(the same as before patching). I have checked Intel's official specifications for the internal Intel HD Graphics 5000 and it states that it can support up to 3200x2000@60Hz. My mac is connected to a 4k monitor through display port 1.2.

**Comment by Floris497** [comment]
Does not work on this model :(

**Comment by qwertyfat** [comment]
Why does the patch not work on this model and is there any alternative methods of achieving a 4k(3840x2160) external monitor resolution?

**Comment by Floris497** [comment]
By editing the frambuffer kext you can.. but i never found the correct values. Check the other issues here and on the old patch linked in the readme.. you should be able to find something there

**Comment by qwertyfat** [comment]
I have read about the problem in other issues but I couldn't find a solution. The old patch does not support OSX 10.10. How would I use the framebuffer kext to output 4k?

**Comment by qwertyfat** [comment]
Floris497?

**Comment by Floris497** [comment]
Well.. in Ubuntu it is possible to get 4k30Hz so the hardware is capable. I was able to get the thing to output 4k but the internal screen stops working properly.. and also there is some distortion when running an external screen at 4k a black band on the bottom ~50x3840 pixels

**Comment by qwertyfat** [comment]
I have done a lot of research and have not been able to find a methode of outputting 4k on an external monitor. Would you by any chance be able to walk me through the steps you used to output 4k(with some issues).

**Comment by Floris497** [comment]
Well, there is hardly documentation about it available, if any.. so far I think nobody has had good results. Let me check some infos for you.

This might steer you in the right direction:
https://github.com/Floris497/mac-pixel-clock-patch/issues/3

**Comment by qwertyfat** [comment]
Would upgrading to Mac OS High Sierra enable the ability to switch to 4k in display preferences or switch ResX?

**Comment by Floris497** [comment]
I don't think so, I have the exact same mac.. and it didn't change anything for me..

https://pikeralpha.wordpress.com/2013/08/02/appleintelframebufferazul-kext-part-ii/

Use this with absolutely caution.. because it will look like you completely messed up your MacBook if you use wrong settings :)

Some settings gave me really bad screen distortions.. from what I thought I even dammaged the hardware.. but I didn't :)

https://github.com/Piker-Alpha/AppleIntelFramebufferAzul.sh
