### ISSUE TITLE
Doesn't work on 10.13.4

### ISSUE THREAD

**Issue by wulei123** [Floris497/mac-pixel-clock-patch-V2#286]
It seems like the patch is patched , but the system can't detect my 4k monitor
```
./CoreDisplay-patcher.command
SIP looks to be disabled, all good!

(otool) Detected patched CoreDisplay on OS X 10.13.4 (17E199).
```
![image](https://user-images.githubusercontent.com/18435126/43362288-4f3a5724-9319-11e8-8570-550e64289e2d.png)

md5:
```
./CoreDisplay-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.13.4 build:17E202

     otool CoreDisplay: 11882f5e04a525da6701777c814c920a
 otool CoreDisplay.bak: 11882f5e04a525da6701777c814c920a
           CoreDisplay: 8acadc56f9aca61f91eae8ef8e13419c
       CoreDisplay.bak: 41e8b79bdd491e0d0da04ef5d66a2507

---- ENDING MD5 HASH SUMS -------
```

**Comment by sas0ri3** [comment]
I am getting the same thing, aside from the fact that it didnt work, can we uninstall the patch?i dont want it to cause any issues later.

**Comment by Floris497** [comment]
On hackintosh use, Lilu and CoreDisplayFixup :) it's easier

**Comment by wulei123** [comment]
OK, thank you very much!
