### ISSUE TITLE
macOS10.14 (18A389) Need new patch support.

### ISSUE THREAD

**Issue by gujiangjiang** [Floris497/mac-pixel-clock-patch-V2#288]
Now the patch can't use in macOS10.14 (18A389) and boot failed and must need FakeID=0x12345678 to boot without graphic work.

So I want to update the patch to support the latest macOS10.14 (18A389).

**Comment by Floris497** [comment]
https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/280#issuecomment-419691545
