### ISSUE TITLE
Is there any possibility to run on macOS 10.15?

### ISSUE THREAD

**Issue by PtNan** [Floris497/mac-pixel-clock-patch-V2#309]
I think whatevergreen didn't work in macOS 10.15, I can't even complete installation.

**Comment by ars0nboi** [comment]
will not work in 10.15. Any fixes coming?

**Comment by Floris497** [comment]
Does 10.15 run on machines that need this patch?

**Comment by pitichampi** [comment]
Yes it does... I've got a late 2014 Mac mini and I do need the patch. Supported devices are listed on this page : https://www.redmondpie.com/macos-10.15-catalina-compatibility-full-list-of-compatible-macs/

**Comment by PtNan** [comment]
ohh, yesterday whatevergreen add cdf for 10.15 support, and work well.

**Comment by basmeyer** [comment]
Closed? Opening again

**Comment by basmeyer** [comment]
Please share how you used WhateverGreen. Thanks
