### ISSUE TITLE
2013 MacBook Air Intel HD5000, black screen on 3440x1440

### ISSUE THREAD

**Issue by meras** [Floris497/mac-pixel-clock-patch-V2#31]
I have this issue where the mba does not recognize monitor's native resolution or size (show's up as 30 inch instead of 34). From reading around I've seen people using 3440x1440 with this mba model and even using it with an older HD4000 model. What's more, if I boot into linux on the machine the native resolution is recognized on bootup and set automatically so I think I've all the evidence that the macbook can support this resolution.

Now after applying the patch the display settings recognizes the correct size and native resolution of the display BUT if I switch to 3440x1440 both native and external screens go combletely blank/black and I need to reboot the machine with the monitor unplugged to have the mba output video.

Any suggestions as to what the issue here might be ?

btw, I tried this on El Capitan (11.5) and later with the 11.6 beta but the outcome was the same.

**Comment by Floris497** [comment]
That is interesting.. The fact that linux works and osx not can be because of the framebuffer.. My 2011 mac mini is able to do 4k for instance.. But my 2013 MacBook Air not.. I was able to get it working in my MacBook Air by editing the framebuffer kext.. But it's very unstable.. Also the script seems not to be working well anymore.. Anyway are you sure people are using this screen with the mac you have not an older version? Also try lower framerates like 24, 30, 40, 50.

Hope this helps you

**Comment by meras** [comment]
The mid 2013 mba is the only machine available so there's no way an older version could be used. 

I'm also not sure how to use a lower frame rate because I only see an option for a 60hz and 75hz option, although according to the spec lower rates should also be there.

Do you have any pointers for editing the kext file on the Mac? Worst case scenario I'll just have to switch back to linux, staying with OS X would be much more preferable.

Thanks!

**Comment by Floris497** [comment]
I'll give you some info when I'm home. Look at switchresx for custom resolutions and framerates

**Comment by meras** [comment]
I'll see if switchresx can help tonight. Thanks for that.

**Comment by Floris497** [comment]
The script that i was using to edit the script and get it to work.. I'll let you know when i get something out of it :)

**Comment by meras** [comment]
Thanks for all your help, I was able to get 3440x1440 working with your patch and switchresx by defining a custom resolution. By default the mba was reying to push the resolution with a much higher pixel clocK rate. After some adjustments it now works fine.

**Comment by Floris497** [comment]
Good to know! Have fun with it :)

**Comment by allaturca89** [comment]
hi, can you help me about how did you do this? Can you post the switchresx settings and where can i get patch? I have a mba early 2014, thanks.

**Comment by Floris497** [comment]
I will look at it later.. But i thinking it's not positive on your mac..

**Comment by allaturca89** [comment]
the monitor has been delivered today. i did not change any setting, just i installed the monitor with thunderbolt to hdmi and i get 3440x1440 30 hz. i ordered a thunderbolt to thunderbolt cable, i hope i can get 60 hz. :)

**Comment by Floris497** [comment]
You have a better chance with thunderbolt if the display has it :) let me know if it works
