### ISSUE TITLE
Will this enable me to run 5120x1440 on a 49" Ultrawide?

### ISSUE THREAD

**Issue by Phunky** [Floris497/mac-pixel-clock-patch-V2#316]
I've got a Philips 499P9 Ultrawide that runs at 5120x1440 but no matter how I connect it to my 2015 Macbook Pro it'll only run at 3840x1080. 

- Thunderport 2 to DP didn't work.
- HDMI didn't work.
- USB-C on a latest Macbook Pro didn't work.
- Apple Thunderport 2 to Thunderport 3 adapter didn't work.

Currently I have to power this monitor by two outputs on my Macbook, which is fine but annoying as hell...

Could this help remove any limitations within MacOS or do I need to keep looking into a custom EDID (if even possible!)

**Comment by zhuzhe1983** [comment]
try RDM software, it works for me

**Comment by Phunky** [comment]
Sadly RDM, SwitchResX and all the others don't help as the underlying OS refuses to support the device correctly.
