### ISSUE TITLE
could not get it to work on my macbook pro retina (early 2013), please help!

### ISSUE THREAD

**Issue by milouz** [Floris497/mac-pixel-clock-patch-V2#35]
I have been following your directions and even applied 2 patches but it still not working. i'll provide screenshots so you can have a better idea of what my current situation is.

I'm using this monitor here: http://4k.com/monitor/lg-27ud68-review-4k-uhd-ips-monitor-with-freesync-lg-27ud68-w-lg-27ud68-p/
With this cable here: https://www.amazon.com/gp/product/B004CAGDUA/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

I'm desperate to get it to work, if you can help me I really appreciate it.

![screen shot 2016-06-22 at 8 10 23 pm](https://cloud.githubusercontent.com/assets/5533911/16291362/e3482236-38ba-11e6-8c8c-5eb43581a460.png)
![screen shot 2016-06-22 at 8 50 06 pm](https://cloud.githubusercontent.com/assets/5533911/16291365/e9d7e53c-38ba-11e6-97d5-54f9df341c07.png)
![screen shot 2016-06-22 at 8 50 41 pm](https://cloud.githubusercontent.com/assets/5533911/16291376/15988db6-38bb-11e6-8f63-52553c559d6c.png)
![screen shot 2016-06-22 at 8 51 15 pm](https://cloud.githubusercontent.com/assets/5533911/16291377/18db2812-38bb-11e6-9661-a1db01768f24.png)

**Comment by Floris497** [comment]
You can try and see what thto web drivers do from
Nvidia.. Cables is good patch looks good.. Try switchresx also, make custom resolution. Try 30Hz 40Hz 50Hz 60Hz.

**Comment by milouz** [comment]
I tried SwitchResX to create custom resolution but it's not going anymore than 40Hz. Btw, 50Hz and 60Hz showed up as inactive and one time it did not power up my LG display too! :( I really want to get that 60Hz because the lag drives me crazy.

Sorry to ask again but I didn't quite understand when you say: "You can try and see what thto web drivers do from"

Here is what I got when I applied the NVIDIA patch, does it look good?
![screen shot 2016-06-22 at 11 25 11 pm](https://cloud.githubusercontent.com/assets/5533911/16293734/15112608-38d1-11e6-9945-80064739e6b8.png)

Again thank you so much for the fast response!

**Comment by Floris497** [comment]
Ah yes.. Nvidia is not supported on 10.11.6 you can try to force the last patch, it could work. See readme for more info on that :) 

Web drivers are nvidia's own drivers for mac

**Comment by milouz** [comment]
I tried to force the NVIDIA patch but I only got this:
<img width="585" alt="screen shot 2016-06-23 at 12 16 28 pm" src="https://cloud.githubusercontent.com/assets/5533911/16316635/561d36d0-393c-11e6-822b-948a009f7749.png">

I also tried to force the IOKit patch but no luck too:
<img width="585" alt="screen shot 2016-06-23 at 12 18 02 pm" src="https://cloud.githubusercontent.com/assets/5533911/16316684/8b06959e-393c-11e6-9c57-ec572c3f2038.png">

I don't know what happen but now SwitchResX does not let me run 3840 x 2160 at 40Hz anymore. I'm looking to just be able to use it at 2560 x 1440 at 60Hz. Is there anyway you can TeamViewer into my Mac and check everything up for me please? I'm desperate to get it to work or I have to return this monitor which I don't want to. I really appreciate your help.

**Comment by Floris497** [comment]
You need ti write "patch v2" not only "v2" the IOKit one is working anyway. I have no 10.11.6 system live now.. So can't check the executible..

**Comment by milouz** [comment]
I tried just now and I got this, is it a good thing? 
<img width="711" alt="screen shot 2016-06-23 at 12 47 07 pm" src="https://cloud.githubusercontent.com/assets/5533911/16317587/b0855d2e-3940-11e6-95ab-b66d2e3cfb46.png">

**Comment by Floris497** [comment]
Nope.. That means that the script did not patch correctly.. Can you send me an email? Then I can help you better. (You can find my mail in the Paypal link in the readme :) use 1 of those 2 )

**Comment by milouz** [comment]
I just emailed you.

**Comment by Floris497** [comment]
I know xD

**Comment by Floris497** [comment]
I don't quite remember if we fixed this problem you had? If not please send me an email :) after we get it fixed it will post the outcome here for the rest to read

**Comment by Phosse** [comment]
Doesn't seem to work for me either:

Philips-MBP:~ philipbecker$ /Users/philipbecker/Downloads/mac-pixel-clock-patch-V2-master/IOKit-patcher.command 
SIP looks to be disabled, all good!

(otool) Detected unpatched IOKit on OS X 10.11.5.
SIP looks to be disabled, all good!
Patching IOKit with patch version 6
Password:
Re-singing /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: replacing existing signature
Closing..
Philips-MBP:~ philipbecker$ /Users/philipbecker/Downloads/mac-pixel-clock-patch-V2-master/IOKit-patcher.command status
SIP looks to be disabled, all good!

(otool) Detected patched IOKit on OS X 10.11.5.

Can't get 1920*1080 in 60 hz with sharp fonts etc.

You got any news on this, anything i can help?

**Comment by Floris497** [comment]
What does`'IOKit-patch.command status ` report?

**Comment by Phosse** [comment]
Hi Floris497,

thanks for your quick reply. 

output of status is:
"Philips-MBP:~ phil$ /Users/philipbecker/Downloads/mac-pixel-clock-patch-V2-master/IOKit-patcher.command status
SIP looks to be disabled, all good!

(otool) Detected patched IOKit on OS X 10.11.5.
Philips-MBP:~ phil$"

strange to me that it's saying 10.11.5, i definitely have 10.11.6. 
Tried nvidia web driver also, but not working.

many thanks for any help in advance.

Phil

**Comment by Floris497** [comment]
Maybe my signatures got messed up.. I will check at home immediately :)

**Comment by Phosse** [comment]
thanks so much

Phil

**Comment by Floris497** [comment]
Unfortunately I don't have much time at the moment.. I will get back when I know more :)

**Comment by m-sch** [comment]
Coming from this issue, which is basically the same
https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/24
I'm also interested if the patch works. Curiously, it works @ 60Hz on Windows via Bootcamp. Maybe there's a way to tell MacOS to use Nvidia Graphics instead of the Intel HD?

**Comment by Floris497** [comment]
What hardware do you have?

**Comment by m-sch** [comment]
I own the Macbook Pro retina 15 inch (early 2013)
https://support.apple.com/kb/SP669?viewlocale=en_US

with 2,4 Ghz CPU and 8GB RAM

**Comment by Floris497** [comment]
Did you have it working before? Windows tricks 60Hz sometimes with less color..

**Comment by m-sch** [comment]
It hadn't worked for me before. You mentioned that you'd like to update the signatures. I'm just curious to know if something has changed in this area.

> Maybe my signatures got messed up.. I will check at home immediately

**Comment by Floris497** [comment]
Nope, was okay. Are you on 10.12 now?

**Comment by m-sch** [comment]
Nope 10.11.6

**Comment by Floris497** [comment]
What cable do you use?

**Comment by m-sch** [comment]
I use a Displayport 1.2 cable from my Dell P2415Q monitor.

**Comment by Floris497** [comment]
I'm not sure if your mac supports DP1.2 MTS this display is devided into 2 tiles for 60Hz.. you can force nvidia GPU with a program called gfxcardstatus if I recall correctly. Maybe that helps :) and maybe use nvidia web drivers too

**Comment by m-sch** [comment]
Cheers, man. Thanks for your help!
