### ISSUE TITLE
version: 10.15.4 build:19E250c support?

### ISSUE THREAD

**Issue by LTKort** [Floris497/mac-pixel-clock-patch-V2#350]
Unknown version of CoreDisplay found.
---- BEGINNING MD5 HASH SUMS ---- version: 10.15.4 build:19E250c

     otool CoreDisplay: 0203d76df0c9c8e8cd9f12039b5d988c
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: 37c13f76752bb9b6b0544e231884e163
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by HVRyan** [comment]
Tried to force both v4 and v5 patched:

$ sh CoreDisplay-patcher.command patch v5
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 5
Can't rename /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay to /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.bak: Read-only file system, skipping file.
touch: /System/Library/Extensions: Read-only file system
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: Read-only file system
update_dyld_shared_cache: warning: x86_64h rejected from cached dylibs: /System/Library/PrivateFrameworks/HelloWorldMacHelper.framework/Versions/A/HelloWorldMacHelper (("Could not find dependency '/System/Library/PrivateFrameworks/UHASHelloExtensionPoint-macOS.framework/Versions/A/UHASHelloExtensionPoint-macOS'"))
Patch failed to run

┬─[rburke@RBurkeMBP:~/Desktop]─[17:51:17]
╰─>$ sh CoreDisplay-patcher.command patch v4
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 4
Can't rename /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay to /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.bak: Read-only file system, skipping file.
touch: /System/Library/Extensions: Read-only file system
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: Read-only file system
Running 'sudo update_dyld_shared_cache' (Might need a re-run after reboot) - CAN TAKE A WHILE (Maybe even 10/30 minutes)update_dyld_shared_cache: warning: x86_64h rejected from cached dylibs: /System/Library/PrivateFrameworks/HelloWorldMacHelper.framework/Versions/A/HelloWorldMacHelper (("Could not find dependency '/System/Library/PrivateFrameworks/UHASHelloExtensionPoint-macOS.framework/Versions/A/UHASHelloExtensionPoint-macOS'"))
Patch failed to run

**Comment by marclope** [comment]
> Tried to force both v4 and v5 patched:
> 
> $ sh CoreDisplay-patcher.command patch v5
> SIP looks to be disabled, all good!
> Patching CoreDisplay with patch version 5
> Can't rename /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay to /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.bak: Read-only file system, skipping file.
> touch: /System/Library/Extensions: Read-only file system
> Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: Read-only file system
> update_dyld_shared_cache: warning: x86_64h rejected from cached dylibs: /System/Library/PrivateFrameworks/HelloWorldMacHelper.framework/Versions/A/HelloWorldMacHelper (("Could not find dependency '/System/Library/PrivateFrameworks/UHASHelloExtensionPoint-macOS.framework/Versions/A/UHASHelloExtensionPoint-macOS'"))
> Patch failed to run
> 
> ┬─[rburke@RBurkeMBP:~/Desktop]─[17:51:17]
> ╰─>$ sh CoreDisplay-patcher.command patch v4
> SIP looks to be disabled, all good!
> Patching CoreDisplay with patch version 4
> Can't rename /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay to /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.bak: Read-only file system, skipping file.
> touch: /System/Library/Extensions: Read-only file system
> Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: Read-only file system
> Running 'sudo update_dyld_shared_cache' (Might need a re-run after reboot) - CAN TAKE A WHILE (Maybe even 10/30 minutes)update_dyld_shared_cache: warning: x86_64h rejected from cached dylibs: /System/Library/PrivateFrameworks/HelloWorldMacHelper.framework/Versions/A/HelloWorldMacHelper (("Could not find dependency '/System/Library/PrivateFrameworks/UHASHelloExtensionPoint-macOS.framework/Versions/A/UHASHelloExtensionPoint-macOS'"))
> Patch failed to run

You have to run the following command first:

sudo mount -rw /

**Comment by freddy5566** [comment]
does anyone success?

@marclope, I execute script and it says it might install successful, I was too excite to get a screen shot.

but, anyway, I cannot get 4k@60Hz, it is still 4K@30Hz,

```
❯ ./CoreDisplay-patcher.command status
SIP looks to be disabled, all good!

Unknown version of CoreDisplay found.
---- BEGINNING MD5 HASH SUMS ---- version: 10.15.4 build:19E266

     otool CoreDisplay: 1de59c1de7ea466ff74f617cdc8ab9de
 otool CoreDisplay.bak: a4afd360d5a91e3d78d32d833350d288
           CoreDisplay: 6c039d30a107b94ddb05df78703500d3
       CoreDisplay.bak: fd95fbe3bea2f9083e0500798b7aa8a4

---- ENDING MD5 HASH SUMS -------
```

here is my status

**Comment by t12ung** [comment]
@jamfly Does your hardware/cables support 4K@60Hz? - Have a look at the recent discussion in this issue:
https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/349#issuecomment-602047119

**Comment by freddy5566** [comment]
@t12ung, yeah my monitor supports 4K@60Hz, or I need to use Display Port over HDMI?

**Comment by t12ung** [comment]
@jamfly I'd already assumed your monitor is capable of 4K@60Hz, otherwise you probably wouldn't have ended up here :smile:

Specifically, you should check your computer's specs for outputting at 4K, and ensure you are using capable cable/dongle that also supports 60Hz.

**Comment by freddy5566** [comment]
@t12ung it turns out you are right, my adapter only supports 4k@30Hz, so I bought another cable for display port -> type c, then it works.
