### ISSUE TITLE
GTX 970 not improved with patch

### ISSUE THREAD

**Issue by Memorion** [Floris497/mac-pixel-clock-patch-V2#36]
I was hoping to get 3840x2160@60hz working via HDMI with this patch but it doesn't seem to work.

I used the IOKit patch because the readme stated it should enable HMDI 2.0 but that doesn't seem to be true as the output was still at 30hz and when I set the resolution to "Default for display" my tv didn't detect any input until I unpatched and rebooted. The same configuration works at 60hz on windows. 

I'd be happy to help and debug this issue if you have any idea why that might be the case!

**Comment by Floris497** [comment]
Use switchresx :)

**Comment by Memorion** [comment]
I tried :/ without the patch it doesn't even show 60hz as an option for 4K, with the patch it does show the option but when I chose it I got no input again

**Comment by Floris497** [comment]
Try making a custom resolution for 40Hz and 50Hz and see what that does.

**Comment by Memorion** [comment]
Just tried with 40Hz and no input again

**Comment by Floris497** [comment]
Hm.. Try the nvidia webdrivers. Maybe that helps. I never tried this. But people reported this path got HDMI2.0 to work. You are sure you are using the right port on the screen. In windows it sometimes does 4k@60Hz with less colors. So the same amount of data is used as in 4k@30Hz

**Comment by Memorion** [comment]
I'm already using the webdrivers, otherwise I can't use my hackintosh. yes, the tv has two ports with 60Hz support and I tried both. How can I check whether windows "cheats" like that?

**Comment by Floris497** [comment]
If it's using RGB 4:4:4 or YUV 4:2:2 not sure.. Never had windows, have this from someone else.

**Comment by Floris497** [comment]
Found anything else on this? I will look at it again this weekend :)

**Comment by Memorion** [comment]
Not yet, but I confirmed trough http://www.geeks3d.com/20141203/how-to-quickly-check-the-chroma-subsampling-used-with-your-4k-uhd-tv/ that windows does not use 4:4:4 with my GTX 970 and Hisense TV combination, but I'm not sure if the tv even supports 4:4:4 because I can't find anything in the spec sheet and the support didn't answer me yet. I'll update to 10.11.6 with the new nvidia webdriver and try again tomorrow

**Comment by Memorion** [comment]
I just tried again and no change :/ without the patch the system preferences look like this:
![screenshot 2016-07-29 00 27 14](https://cloud.githubusercontent.com/assets/1974743/17231701/e94eb6c4-5523-11e6-9675-85ba13c9d6a9.png)
and after it looks like this:
![screenshot 2016-07-29 00 30 31](https://cloud.githubusercontent.com/assets/1974743/17231713/f8803fdc-5523-11e6-9955-40ac83d7682a.png)
but when I change anything after patching the screen goes black and I have to switch to my other display and unpatch before I get input again.

**Comment by Floris497** [comment]
I would recommend you using switchresx, could you have a look if that works?

**Comment by Memorion** [comment]
I already tried that the last time and I did also try it yesterday but when I make a custom resolution at 4K with more than 30hz I get no input

**Comment by Memorion** [comment]
I'll close this for now because I assume OSX tries to use 4:4:4 and I don't actually now whether my TV supports that.

**Comment by Floris497** [comment]
Ah I see, maybe we get a way force 4:2:0, if I remember and find something I'll let you know.

**Comment by Memorion** [comment]
Luckily it's only the TV, there isn't that much 40K@60Hz content so it'll probably be fine for movies at 24Hz for the foreseeable future. If I buy a new desktop monitor I'll make sure to get one that supports 4:4:4 and I'll try the patch again, thanks for all the help and patience!
