### ISSUE TITLE
M1 MacBooks

### ISSUE THREAD

**Issue by Nahasean94** [Floris497/mac-pixel-clock-patch-V2#376]
has any one tried this with the new mac book M1s? I don't want to risk my work laptop

**Comment by Floris497** [comment]
I wouldn’t see why it’s needed. What are you trying to accomplish?

**Comment by Nahasean94** [comment]
I bought an HP Z43 and I have a MacBook Pro with M1 chip. Connecting the laptop using the charging usb c cable, the monitor is not detected. I ended up buying a dongle and connect via HDMI instead. Unfortunately the monitor settings are capped at 30Hz. I did some research and I was brought to this repo. I thought I could use the scripts to either be able to connect via USB C direct without dongle, as well as use 60 Hz on the monitor. But I am afraid if I run any scripts, I might brick my work computer.

**Comment by Floris497** [comment]
The charging cable doesn’t do display data.. only USB2.0 speeds as far as I’m aware (definitely this was the case for the earlier usb-c macs.. so I’m pretty sure it’s still the case). for display data you’ll need a USB-C cable with all the data lanes enabled.

**Comment by Nahasean94** [comment]
ow okay
do you have a link I can buy one? amazon or wherever?
