### ISSUE TITLE
Applying patch takes long

### ISSUE THREAD

**Issue by bbss** [Floris497/mac-pixel-clock-patch-V2#39]
Goeiedag,

How long is patching supposed to take?
I disabled SIP and ran the script with sudo but after half an hour or so of just displaying applying patch I cancelled the command. Not smart as I had to reinstall my OS to get it to boot again. 😄

Not sure how to give you other debug information.

Bedankt voor je werk en groetjes uit Korea.

**Comment by Floris497** [comment]
Ehm.. it's supposed to take 1 second.. interesting it took so long.. ehm i have no idea how to see what went wrong. Maybe try again?

What does the script say when running "iokit.command md5"

**Comment by bbss** [comment]
That says:
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.5 build:15F34

     otool IOKit: d8829f2234464985863c7a501c288547
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: a73dd1ed37da96000958bb781ce4ac15
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment]
Ik zou het nog eens proberen.. ben je een beetje handig met sit soort dingen? Zoja: maak een backup van je IOKit. "mv iokit iokit-backup" (gebruikt geen 'iokit.bak') als het dan weer fout gaat kun je die in single user mode of recovery weer terug zetten. Scheelt herinstalatie :)

**Comment by bbss** [comment]
Ik ben een programmeur maar niet zo bekend met unix/posix/Apple-specifiek spul.

Recovery doe ik door opnieuw de installatie usb disk te gebruiken en dat ging redelijk okay (duurt alleen ff maar niet veel werk).

Ik ga het weer proberen, met de CsrActiveConfig op 0x03
```
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
```
Lijkt me dat alleen filesystem en kext signing nodig zijn?

**Comment by Floris497** [comment]
Alleen filesys.. maar het is beter als je alles uit zet.. het script kan niet overweg met deze output van csrutil status :/ maar hierna kan je het weer aanzetten :)

**Comment by Floris497** [comment]
VooDooHDA is dat niet hackintosh?

**Comment by bbss** [comment]
Yeah, t is een hackintosh. Mijn MBP is te sloom voor het werk dat ik doe. Ik heb nog geen 60hz beschikbaar in displays of switchresx, of moet ik handmatig ergens de hz setten?

Ik kan proberen het opnieuw te doen. Ik weet niet of ik de voodoohda wel nodig heb, had t alleen aangevinkt in clover toen ik m'n geluid niet werkend kreeg een tijdje terug.

**Comment by Floris497** [comment]
Geen idee wat het met elkaar te maken heeft. Gebruik switchresx voor custom resolutions.

**Comment by bbss** [comment]
Met disabled geprobeerd:
```
sudo /Users/bb/Downloads/mac-pixel-clock-patch-V2/IOKit-patcher.command
Password:
SIP looks to be disabled, all good!

(otool) Detected patched IOKit on OS X 10.11.5.
```
Dus 0x03 was voldoende denk ik. Ff met switchresx aan de slag!

**Comment by bbss** [comment]
Okay I guess this patch did its job, was able to push it to 32hz. Too bad the 4k@60hz active adapter nor the HDMI2.0 did the trick for going higher. Sad to find out that my tv [only supports 30hz](http://download.p4c.philips.com/files/4/49pun5800_61/49pun5800_61_pss_.pdf) even though it had big bold letters with 100hz on the box, probably some internal interpolation shizzle.

Thanks for your effort @Floris497
