### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by zprovo** [Floris497/mac-pixel-clock-patch-V2#41]
Please help me out.
I am looking to uninstall this patch.

The reason is that anytime I now use the thunderbolt port to output 4k my wifi connection becomes terrible. i know this sounds ridiculous but it is literally like an on off switch. I can try loading a page and it will hang while plugged in to my external display and the minute I unplug it the webpage loads instantly.

My first step in troubleshooting is uninstalling this, because I have used my display at 4k and 52Hz in the past flawlessly without it... (http://forums.macrumors.com/threads/dell-p2715q-and-p2415q-4k-ips-displays.1816805/page-60#post-22916575)

Any other advice/ideas? This is a new problem, I used it for over a year without this issue, but recently reinstalled OS and changed miniDP cable and now have this problem.

This is a terrible problem... I need my display and wifi! One without the other sucks!

Many thanks.
Z

**Comment by Floris497** [comment]
So if I'm correct you don't have the problem when the patch is not there? Or is it a problem with having the display connected? Did you try slightly different framerates? I can't see why this patch is a problem other than that limits of the computer are reached..

**Comment by zprovo** [comment]
Correct, partially... I did not have the problem before, but I have now introduce a few new variables:

1. New miniDP to miniDP cable
2. Installed this patch
3. Reinstalled Mavericks

If you honestly do not think that this patch is related to my issue, then I guess that is good in a way, it allows me to narrow down my problem.

Unrelated question:

Do you know if it is possible, using any software or otherwise to output 60Hz 4k from a late 2013 rMBP? As far as I know, this 52Hz thing I am doing with switchresx is the best I can do.

Many thanks.
Z

**Comment by Floris497** [comment]
Did you force integrated graphics? There is software that can do this. If problems persists it's probably not your mac.. but i can't really troubleshoot from this distance :/

Yes.. using external GPU :p

**Comment by zprovo** [comment]
Ok well I appreciate your help anyways thanks!

Is uninstalling the patch complicated? I would like to try just for the heck of it... I am running out of ideas and this is one of my last ones.

Sorry to bother you with something so trivial and isolated...

Z

**Comment by Floris497** [comment]
Yep run ```patch.command unpatch```
