### ISSUE TITLE
Wrong $gOSVer value

### ISSUE THREAD

**Issue by Tricheur-one** [Floris497/mac-pixel-clock-patch-V2#44]
Hello, Floris!

It may be wrong $gOSVer and $gDelimitation_OSVer comparison values in the recent IOKit-patcher.command script:

$ ./IOKit-patcher.command 
./IOKit-patcher.command: line 14: [: 10.11: integer expression expected
SIP is enabled, this script will only work if SIP is disabled
Closing..

You use gOSVer=${gProductVer:0:5} to get current OS version (10.11.6 in my case, which gives as gOSVer = 10.11). Then you compare it with variable gDelimitation_OSVer = 12

-ge conditional operator in line 14 can test integers only. I think you should use gOSVer=${gProductVer:3:2} in line 7 of the IOKit-patcher.command script.

**Comment by Floris497** [comment]
Oh thank you :) I merged this from a different person without having time to test it.. I will probably delete the whole thing and make a new script for this. But for now this looks like a good fix.

**Comment by syscl** [comment]
@Tricheur-one @Floris497 I fix the issue but Floris497 is busy these day to merge that fix.

Also I added dp3 support.

syscl

**Comment by Floris497** [comment]
I have removed all the changes by @syscl I'm going to make a new script for the new file to be patched in 10.12. For now look at his repo to patch. This weekend I will add the new file after some research
