### ISSUE TITLE
Working on 10.11.6 ?

### ISSUE THREAD

**Issue by adrieno** [Floris497/mac-pixel-clock-patch-V2#45]
Hello :)

Before to update my hackintosh would just know if the patch was working on 10.11.6 ?
You mentioned beta for 10.11.6, but not for the final version :)
Just want to be sure !

Thx for your work again !

**Comment by BloomingtonDJ** [comment]
Tried the patch on a MacBook Pro 15 (mid-2015) with the AMD Radeon R9 M370X 2048 MB video card... No luck. I kept getting an installation error (not sure)


**line 14: [: 10.11: integer expression expected**
SIP looks to be disabled, all good!

(otool) Detected patched IOKit on OS X 10.11.6.


Also tried this on a MacBook Pro Retina (Late 2013) with Intel Iris Pro 1536 MB and also no luck... Same error on both install files. 

Are either of these machines supported? I have a lighting bolt to HDMI cable. I also have a normal HDMI connection. Any information would be appreciated! 

Thanks

**Comment by Floris497** [comment]
You can ignore the error, the script has done it's job and patched the IOKit.

Unfortunately AMD gpu's are not supported now..

**Comment by BloomingtonDJ** [comment]
I'm hoping for 4K @ 60hz... What is the special adaptor?  Also a special display? I have a normal 4K 60hz TV... Doesn't support MST.. Just 4:4:4 60hz..

**Comment by Floris497** [comment]
MST is a DisplayPort standart. And has nothing to do with HDMI. HDMI cannot send 4k@60Hz only 4k@30Hz. Windows tricks 60Hz by using 4:2:0. If your display has DisplayPort use a Displayport adapter. If your screen has HDMI2.0 use an DisplayPort to HDMI2.0 adapter.. The only one I know for now is one from Club3D.

**Comment by Memorion** [comment]
> HDMI cannot send 4k@60Hz only 4k@30Hz.

This doesn't seem to be true: http://www.geeks3d.com/20150112/msi-gtx-970-lg-uhd-tv-60hz-444-finally-it-works/

**Comment by giulioungaretti** [comment]
@Memorion  AFAIK only hdmi2.0b can do.

**Comment by Memorion** [comment]
@giulioungaretti no idea, but hdmi2.0b is still HDMI isn't it?

**Comment by giulioungaretti** [comment]
@Memorion  yas, the calbe that is but the hardware on either side may not.
I.e. apple's  usb-c adaptor speaks usb 1.4. Some displays speak hdmi 2.0.

**Comment by Memorion** [comment]
Yes, I'm aware that there are many parts that have to work together to enable 4:4:4 4K@60hz via HDMI but it doesn't seem to be impossible.

**Comment by Floris497** [comment]
Apple has never shipped any computer featuring HDMI2.0. That's what i was referring to. On 900 series cards HDMI2.0 can be enabled with the IOKit Patch, as I'm told by people using these cards. Windows does doe HDMI1.4 4K@60Hz but on half the color data. 4:2:0 YUV vs 4:4:4 RGB

**Comment by Floris497** [comment]
The macbook does DP1.2 and can spit out 4k@60Hz when used with the corect monitor and adapter cable.

**Comment by markomitranic** [comment]
Yes, as far as i know, MDP ports on macs can spit out full 4k@60Hz^4:4:4.

You WILL need MDP>HDMI2.0 cable/adapter. These adapters are unfortunately not reliable if you try to buy low quality ones. Often times, they are marketed as "4K MDP" adapters, but are in fact HDMI1.4@30Hz, so beware of that.

As of now, there seems to be no known way of forcing the drivers to output 4:2:0 (like windows does) without advanced editing of the drivers. So all in all, it seems that we will get apple support for HDMI2.0 faster than we are able to implement 4:2:0 approach.

**Comment by Floris497** [comment]
Try looking at EDID overwrites, if you list the screen to only support 4:2:0 maybe we can get it to output 60Hz :)

**Comment by Floris497** [comment]
Working on 10.11.6 now :)
