### ISSUE TITLE
Unknown Hash @ no effect after installation

### ISSUE THREAD

**Issue by markomitranic** [Floris497/mac-pixel-clock-patch-V2#46]
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

     NVDAGK100Hal: 857c03c644620a3e7b828cbefe1da225
 NVDAGK100Hal.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

This is the response i get from NVIDIA.command md5

I have installed both scripts, but i am still getting only 30Hz as an option.
I have verified that my machine can output 4k@60Hz, because when i go to bootcamp, i am getting 60Hz no problem...

This is the full output of my commands

```
Hackintosh-Pro:mac-pixel-clock-patch-V2-master markomitranic$ chmod +x IOKit-patcher.command 
Hackintosh-Pro:mac-pixel-clock-patch-V2-master markomitranic$ chmod +x NVIDIA-patcher.command 
Hackintosh-Pro:mac-pixel-clock-patch-V2-master markomitranic$ ./NVIDIA-patcher.command 
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading

Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

     NVDAGK100Hal: 857c03c644620a3e7b828cbefe1da225
 NVDAGK100Hal.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
Hackintosh-Pro:mac-pixel-clock-patch-V2-master markomitranic$ ./IOKit-patcher.command 
./IOKit-patcher.command: line 14: [: 10.11: integer expression expected
SIP looks to be disabled, all good!

(otool) Detected unpatched IOKit on OS X 10.11.5.
SIP looks to be disabled, all good!
Patching IOKit with patch version 6
Password:
Re-singing /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: replacing existing signature
Closing..
Hackintosh-Pro:mac-pixel-clock-patch-V2-master markomitranic$ 
```

**Comment by Floris497** [comment]
So it looks like IOKit does patch but Nvidia not.
An update is needed for the Nvidia script to make it work. You can also run the Nvidia script with ```NVIDIA-patcher.command patch v2``` if this works please provide me the MD5 and I will update the script :)

**Comment by markomitranic** [comment]
Yes, i believe it is because of the newest update to El Capitan (10.11.6 as i recall) which i have updated to today. Of course NVIDIA asked for update too, and i believe i did that one also.

Anyways, i wont bother you with that for now... Afterall its weekend and you should rest :D
i'll look into the code and try to figure out how to do it myself.
If you have any advice, i'm all ears.
If not, see you Monday Floris!

I googled far and wide in order to find out how to force 60Hz, created some custom EDIDs, on windows it works great, on mac not. So if pixel clock patch does not help, i am out of options...

From my research, i believe that either Apple made a software cap, or they have locked us out by not supporting HDMI with this throughput. I hope the first one is the culprit since from what i understood, your epic patch should remove this cap.

**Comment by Floris497** [comment]
Read this one: https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/45 windows tricks 60Hz by using 4:2:0 instead of 4:4:4 effectively halving the color information and doubling the framerate. Sadly the weekend is the only time I can work on this.. but this weekend i have to fix a drone and my MacBook USB port 😅. Try to force the script for now with v6 for IOKit and v2 for Nvidia :-)

**Comment by markomitranic** [comment]
This response is gold, i suspected that windows cheats it in a very clever way.

Now, i will definitely buy a HDMI2.0 to DP adaptor, but since i am a geek and an apple technician, i will continue on in search of a way to force 4:2:0 on mac :) thank you for this tip i am not sure how i missed it!

I will send you the hash tomorrow since i am not home at the moment.

P.S. Good luck with the drone and USB! USB fix should be simple enough if you know how to remove the MLB from the topcase takes about ~20min of work. Usually the issue is as simple as the connections to the MLB broken...

**Comment by Floris497** [comment]
Let me know what you find on 4:2:0 I think there is some good info on the hackingtosh fora for this! USB fixed :-) the connection was good, top side grounds somehow bend into the conector.. could not get anything in there.. the hardest part was getting the PL5 screwdriver :p got to love apple this..

**Comment by markomitranic** [comment]
Yo Floris,

So, i did force the patch, but it seems unsuccessful. Per our previous conversation, i expected for the macOS to force 60Hz and i expected that the display will be out of range. Neither of there happened. Actually as far as i can tell nothing happened.

The response i got from the shell was:
**SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading
Patching NVDAGK100Hal with patch version 2
Password:
The code of the driver has changed, the patch was probbably succesfull**

So, lets break it down, the NVDA has changed, so the patch does not work and needs to be updated (or maybe i did something wrong). So i would like to close this issue since it is no longer relevant, as we now know the culprit. If you still need md5 i will be happy to send it to you, just tell me how and of what :)

As per my voyage into the 4:2:0 realm, i am proficient with hackintoshes, so i will definitely look there (in my experience those guys know far more about osx than any of the apple agents and engineers i have met so far.) i will keep you posted if i discover something, and we shall open a new issue for that, maybe update the readme.md if we acctually find a way :)

**Comment by Floris497** [comment]
Keep this open till I update the script.. Maybe I have some time today, but you should not count on it.. I've seen that Apple changed quite a bit of code in 10.12 now.. Need to look into that too.. The pixel clock seems to have moved to a different driver there..

For Nvidia.. Maybe try their web drivers :) it might help with 4k@60Hz.

As for 4:2:0 I would like to hear what you find.. We can keep this issue open for that or make a new one. Maybe I have some time next week to look into it myself :)

**Comment by markomitranic** [comment]
Hmm, this is a very interesting development Floris...

First of all, i started writing that i AM using web drivers all along, and that i am confused because i thought that your script removes the system wide clock rate, so that it is not really important which drivers i use. (i now believe that i was wrong to think that)

**Now for the side effects:** My card used to only play nice with nvidia web drivers... Now, i was certain that i am still using those. But it seems that the systemUpdate/yourScript (not sure which one) changed something, and now the vanilla support also works for my card.

Unfortunately, both of them show a maximum of 30Hz :( haha

**Comment by Floris497** [comment]
Wait.. I need to read back.. I don't always remember everyones system :P Yes.. IOKit removes lock for Integrated and Desktop Nvidia GPU's with HDMI2.0, Nvidia removes for Apple Nvidia drivers for Dedicated mobile GPU's

**Comment by markomitranic** [comment]
Of course you cant remember, and we don't expect you to :D

My rig is a MacPro with a GTX 750 Ti, i have always needed nvidia web drivers so far, because i could not get more than 800x600 and a horrible refresh rate with native support. Now, for some reason, it works the same with or without the NVidia web drivers.

Either the update changed the native drivers significantly so we now have vanilla support (judging by the tonymacx86 forums - i dont think so), or the old drivers had full support all along, but were capped by Apple and your IOKit script removed this cap. So now they work in their full potential. I will verify this asap on my hackintosh with an older system, just to be sure. This has nothing to do with the Issue i opened, but might be a really interesting and important side-effect

**Comment by Floris497** [comment]
That sounds interesting.. Ive never tested a 700 series card.. But 600 series cards seem to work with normal drivers both in MacPro and External GPU enclosure.. Maybe there has been some updates on the GPU drivers for Nvidia lately. But I don't know that..
It's not apples main priority (if it is a priority at all) to support other cards than the cards they sell for the MacPro.

**Comment by markomitranic** [comment]
Yes, this is exactly why it is interesting.

Apple has a habit of... writing the whole thing and then excluding models as per the agenda at the moment. Think bootcamp assistant, smb, apis, even the parts themselves...
So it might not sound crazy to think that they wrote the support and then included only supported models.

I will try to verify this theory and report my findings. If i am right, you may have just discovered a brand new approach for the hackintosh people :D

**Comment by markomitranic** [comment]
Ok, just a quick followup on the native driver thing, i have tested it and i can confirm that it does indeed, for some reason (you know better than me) allow me to select larger resolutions and normal refresh rates on native support. It looks as if you lifted some kind of limiter from the OSX itself.

BUT, upon further testing i have decided that the overall performance is not that great compared to NVIDIA web drivers especially in working with Photoshop, or Preview.

So all in all this is not as important. I just wanted to update you :)
Ok, enough with the hackintosh stuff, the next time i write something, it will be concerning 420, i promise haha

**Comment by Floris497** [comment]
Haha no this information is interesting to me! Don't limit your self to spread your knowledge :)
