### ISSUE TITLE
Macbook Retina 2015 stopped working with 10.11.6. Can I downgrade?

### ISSUE THREAD

**Issue by arturojovann** [Floris497/mac-pixel-clock-patch-V2#49]
Hi, 

I ran this patch on a macbook 2015 retina and everything was working beatifully. Out of no where this morning I had to start my computer by holding the power button then I got a message on a black screen that it didnt turn off properly. After that patch doesnt work even though Ive tried to install it a few times again. Any help would be greatly appreciated. 

EDIT: Actually believe its because my compute updated to 10.11.6 without me knowing. Any ideas could I downgrade?

**Comment by Floris497** [comment]
See if SIP is disabled and run the patch again

**Comment by arturojovann** [comment]
I did that already. Didn't work.

**Comment by arturojovann** [comment]
Anyway to downgrade or will upgrading to Sierra make it work again?

**Comment by Floris497** [comment]
Lately i have very little time to work on this.. Siera brings some interesting changes to the graphics drivers.. Let me look tonight if I can update everything correctly so it will work again

**Comment by arturojovann** [comment]
Okay thank you very much. I will make sure to donate to paypal. This was
the only reason I bought a 4K moniter just for this patch.

**Comment by Floris497** [comment]
Please download the patch again and try :)
I have messed up the repository a bit.. But it should be kinda okay now!

**Comment by arturojovann** [comment]
I am getting this error:

Arturos-MacBook:~ arturojovann$ /Users/arturojovann/Desktop/IOKit-patcher.command 
md5: /Users/floris/Desktop/IOKit: No such file or directory
error: /Library/Developer/CommandLineTools/usr/bin/otool: can't open file: /Users/floris/Desktop/IOKit (No such file or directory)
SIP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

error: /Library/Developer/CommandLineTools/usr/bin/otool: can't open file: /Users/floris/Desktop/IOKit (No such file or directory)
     otool IOKit: d41d8cd98f00b204e9800998ecf8427e
 otool IOKit.bak: NO FILE (this is okay)
md5: /Users/floris/Desktop/IOKit: No such file or directory
           IOKit: 
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
Arturos-MacBook:~ arturojovann$

**Comment by Floris497** [comment]
Whoops my bad

**Comment by arturojovann** [comment]
Its okay!

**Comment by arturojovann** [comment]
Im getting this:

Arturos-MacBook:~ arturojovann$ /Users/arturojovann/Desktop/IOKit-patcher.command 
SIP looks to be disabled, all good!

(otool) Detected patched IOKit on OS X 10.11.5.
Arturos-MacBook:~ arturojovann$ 

Im assuming its reading the old patch and not installing the new one. Figuring out a way to uninstall and install the new one.

**Comment by Floris497** [comment]
Hm.. The patch is the same anyway, it's just the string that is wrong.. Could you please run ```patch.command md5```

**Comment by arturojovann** [comment]
Not getting anything with that. Not 100% sure I'm doing it right. I'm not
super savvy with terminal. But I typed in "patch.command md5" and nothing.

**Comment by Floris497** [comment]
Oh.. Ye sorry, I meant add "md5" at the end of the command, patched file in the terminal add it to there :) "patch.command" does not exist it was just a placeholder

**Comment by arturojovann** [comment]
Haha sorry for that. Thank you so much for your patience. 

Heres what Im getting from that "md5" add.

Arturos-MacBook:~ arturojovann$ /Users/arturojovann/Desktop/IOKit-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

     otool IOKit: 5ff1819545b8e127728a904c8f41bc5f
 otool IOKit.bak: d8829f2234464985863c7a501c288547
           IOKit: ccc53e3714823e941182e96a09aee6a0
       IOKit.bak: f238e7c45a405e520f5852c89a81707b

---- ENDING MD5 HASH SUMS -------
Arturos-MacBook:~ arturojovann$

**Comment by Floris497** [comment]
Hm.. Most interesting.. You have got the old files in place somehow..
I would recommend you to reinstall 10.11.6 (reboot in recovery and reinstall, it takes some time tho..)

**Comment by arturojovann** [comment]
That's okay totally worth it. Okay will try that and let you know the
outcome.

**Comment by Floris497** [comment]
Perfect, hope it works good again after :)

**Comment by arturojovann** [comment]
Alright Im back. I reinstalled osx, that took a few hours. Disabled SIP and this is what Im getting know. Again so sorry to be a bother about this :( Hopefully you could take a look at it one more time and see whats up! Thank you.

Arturos-MacBook:~ arturojovann$ /Users/arturojovann/Desktop/IOKit-patcher.command 
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
SIP looks to be disabled, all good!

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
     otool IOKit: d41d8cd98f00b204e9800998ecf8427e
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: f238e7c45a405e520f5852c89a81707b
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
Arturos-MacBook:~ arturojovann$

**Comment by Floris497** [comment]
Hm.. It looks like your command line tools are not working good.. Did you get the option to install them? Else.. Install Xcode from the App Store.. I'm not sure why this is giving you so much trouble.. :/

One of the commands I use in the script is ```otool``` you can try and run this command without anything else. It will print out the usage if It's working, if it's not installed you will get prompted to install it I hope :)

**Comment by arturojovann** [comment]
I am installing Xcode now on the app store. I typed in otool and got this:

Arturos-MacBook:~ arturojovann$ otool
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Arturos-MacBook:~ arturojovann$

**Comment by arturojovann** [comment]
This is what I get typing otool now:


Arturos-MacBook:~ arturojovann$ otool
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool [-arch arch_type] [-fahlLDtdorSTMRIHGvVcXmqQjCP] [-mcpu=arg] [--version] <object file> ...
	-f print the fat headers
	-a print the archive header
	-h print the mach header
	-l print the load commands
	-L print shared libraries used
	-D print shared library id name
	-t print the text section (disassemble with -v)
	-p <routine name>  start dissassemble from routine name
	-s <segname> <sectname> print contents of section
	-d print the data section
	-o print the Objective-C segment
	-r print the relocation entries
	-S print the table of contents of a library
	-T print the table of contents of a dynamic shared library
	-M print the module table of a dynamic shared library
	-R print the reference table of a dynamic shared library
	-I print the indirect symbol table
	-H print the two-level hints table
	-G print the data in code table
	-v print verbosely (symbolically) when possible
	-V print disassembled operands symbolically
	-c print argument strings of a core file
	-X print no leading addresses or headers
	-m don't use archive(member) syntax
	-B force Thumb disassembly (ARM objects only)
	-q use llvm's disassembler (the default)
	-Q use otool(1)'s disassembler
	-mcpu=arg use `arg' as the cpu for disassembly
	-j print opcode bytes
	-P print the info plist section as strings
	-C print linker optimization hints
	--version print the version of /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool
Arturos-MacBook:~ arturojovann$

**Comment by arturojovann** [comment]
Ran it again after xcode install and Im getting this:

(otool) Detected patched IOKit on OS X 10.11.5.
Arturos-MacBook:~ arturojovann$ 

But still not working at 60hz :/

**Comment by Floris497** [comment]
Hm.. Interesting that it shows you it is from 10.11.5 I don't understand.. Can you give the md5 output again?

(otool has nothing to do with it, but I hoped it would trigger the install of the commandline-tools)

**Comment by arturojovann** [comment]
Okay thank you. I am away from my computer at the moment but will be back
tomorrow. Thanks for help so far.

**Comment by arturojovann** [comment]
Back again! Heres the md5 update:

Arturos-MacBook:~ arturojovann$ /Users/arturojovann/Desktop/IOKit-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

     otool IOKit: 5ff1819545b8e127728a904c8f41bc5f
 otool IOKit.bak: d8829f2234464985863c7a501c288547
           IOKit: 2335504d4138e0619cc7ae6f09ea906e
       IOKit.bak: f238e7c45a405e520f5852c89a81707b

---- ENDING MD5 HASH SUMS -------
Arturos-MacBook:~ arturojovann$ 

Thanks!

**Comment by Floris497** [comment]
Hm.. how did you reinstall the system.. I don't understand why your file is stuck at 10.11.5?? Did you boot into recovery and reinstalled it from there? If not could you try this? 

Can you after a reinstall not do the patch and see what the MD5 says before patch.. or did you not patch at all now?

**Comment by arturojovann** [comment]
I did boot into recovery and reinstalled the os. I can do it again if you'd
like and do md5 before the patch.

**Comment by arturojovann** [comment]
None of my stuff got deleted though and I didn't have to back up from time
machine. Maybe I did it incorrectly?

**Comment by Floris497** [comment]
No that's the nice thing about reinstalling OS X that it just installs the os and leaves all your files as is :) hm.. maybe unpatch first then try and reinstall again.. for me reinstalling takes about 20m but that might be due to my SSD. You could try yes, but I don't get why it happens

**Comment by arturojovann** [comment]
How do I exactly unpatch first? I will unpatch and reinstall the os again
and apply patch afterwards.

**Comment by Floris497** [comment]
```IOKit-patch.command unpatch``` will unpatch

**Comment by arturojovann** [comment]
Just updating: This is what Im getting with unpatch. 

Arturos-MacBook:~ arturojovann$ /Users/arturojovann/Desktop/IOKit-patcher.command unpatch
There is no backup file, we can not undo the patch. the patch might not even been done.
Closing..
Arturos-MacBook:~ arturojovann$ 

Going to reinstall OS again

**Comment by Floris497** [comment]
Are you sure you have the latest version of the patch?

**Comment by arturojovann** [comment]
I just deleted whatever I had and reinstalled the one posted on the website
that said it was updated 3 days ago. Is the patch not uninstalling
correctly?

**Comment by Floris497** [comment]
It says that it can't find the backup file.. while there is decently a signature for the backup.. So I wonder if you might have a wrong version that acts weird..

**Comment by arturojovann** [comment]
Okay so I just reinstalled it and then unpatched and that registered.
However even with the most recent download it still says 10.11.5. Could the
wrong file be uploaded on the site by any chance? I'm just trying to think
here but I did unpatch it correctly now. Any ideas?

**Comment by Floris497** [comment]
Oh.. that you should not have done.. after a reinstall an old patched backup can stay in place.. what you just did is replace the new IOKit with an old backup..

**Comment by arturojovann** [comment]
I didn't re install the OS yet. Just re installed the patch then took it
off with unpatch. I don't mind wiping to factory setting if I have to make
this work. Whatever it takes.

**Comment by Floris497** [comment]
Sorry about getting you trough so much trouble.. 

I'm now going to bed.. what you can do is check the md5, if it says no file on the backup it is okay. Then reinstall the OS and see again if the MD5 has changed..

I will help you tomorrow after work.

**Comment by arturojovann** [comment]
Alright no problem thank you

**Comment by arturojovann** [comment]
So reinstalled OS and checked md5. This comes up I think were good. Ill wait for your instructions whenever you are free tomorrow. Thanks. 

Arturos-MacBook:~ arturojovann$ /Users/arturojovann/Desktop/IOKit-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

     otool IOKit: d8829f2234464985863c7a501c288547
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: f238e7c45a405e520f5852c89a81707b
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
Arturos-MacBook:~ arturojovann$

**Comment by arturojovann** [comment]
I just found out I can downgrade the OS if I take it to the Apple Store.
Just going to do that. I hope to the god that will fix this and make it
work again when I reninstall the patch. Crossing my fingers!

**Comment by arturojovann** [comment]
Not good. They couldn't downgrade to 10.11.5 but I am downgrading to 10.10
Yosemite. Not sure if that will work but worth a try. If anything I'll
upgrade to 10.11.6 again and take it from there.

**Comment by Floris497** [comment]
Hope that works.. else send me an email i can help you tomorrow after work, that might be better than github.

**Comment by arturojovann** [comment]
Alright. I installed it running Yosemite and it works again at 60hz. Thank god! Looking forward to seeing if this ever works on Sierra but until then Ive turned off automatic downloads in the settings to prevent this nightmare again! Thanks again for being so helpful and responding so quickly to this issue. Will be donating for sure because I obviously cant use computer without this patch if you couldn't tell haha.
