### ISSUE TITLE
Scaled Resolutions Missing between 2160P and 1080P

### ISSUE THREAD

**Issue by brettcrowell** [Floris497/mac-pixel-clock-patch-V2#52]
Not necessarily patch related, but I'm writing to ask if anyone else is missing Scaled Resolutions on their 4k monitor?  The only options that I have in "Scaled" mode are...

- 1152x648
- 1504x846
- 1920x1080
- 3840x2160

![screen shot 2016-07-28 at 6 41 24 pm](https://cloud.githubusercontent.com/assets/1547447/17232445/19c00e4e-54f6-11e6-883d-c14aa1f89a0b.png)

The situation doesn't get any better when selecting [Alt] + Scaled.

Has anyone else run into this?  I'm using a Late 2013 Retina Macbook Pro 13" with an LG 27UD68 monitor.

**Comment by Floris497** [comment]
I mainly use switchresx to change resolutions, everything is there always :)
