### ISSUE TITLE
Unknow version 10.11.6

### ISSUE THREAD

**Issue by nlamot** [Floris497/mac-pixel-clock-patch-V2#57]
Hi

Thanks a lot for this great tool!
However, for my graphics card, I get the following error:
Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G31

In the README, it says that this version should be supported, however, I still get this error.
Is there something I'm doing wrong?

I'm executing the patch on a mid-2010 15 inch macbook pro.

Kind regards
Nils

**Comment by Floris497** [comment]
I would need to take a look at the Nvidia drivers, I hope I have some time this week. You can try forcing the patch as described in the readme :)

**Comment by alexanderzinolidis** [comment]
I managed to get it working on the latest nvidia web drivers (osx 10.11.6, nvidia 346.03.15f02) by patching iokit and then nvidia v2.

Im not 100% sure what I did and in what order, but it sure works now.

**Comment by nlamot** [comment]
Thanks @Floris497 and @alexanderzinolidis, I tried forcing it to version 2 and now it patched.
However, I still can't use 2560x1080 pixels. As far as I can see, nothing has changed, even when I use switchresx. Maybe there's something else I need to do?

**Comment by nlamot** [comment]
I managed to solve it for my display by trying some different switchresx settings.
For future reference, these are the settings for the LG 25um65:(https://cloud.githubusercontent.com/assets/3662516/17712920/8fab55d0-63f8-11e6-85f7-82692f26f6b3.png)

Thank you for your feedback, I'll close this issue.

**Comment by bora89** [comment]
Thank you @nlamot for your config - that worked for me. But when switchresx expire will the settings get back? Is there any other way to make it work? I installed  NVIDIA Driver 346.03.15f03 but untill switchresx that did not work. Do I need to patch IOKit after nvidia driver?
