### ISSUE TITLE
10.11.4 beta 4 unknown

### ISSUE THREAD

**Issue by nos1609** [Floris497/mac-pixel-clock-patch-V2#6]
Unknown version of IOKit found..
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.4 build:15E49a

     otool IOKit: 08fe7e9724c60e084dd3d8822106a963
 otool IOKit.bak: 9522ce35bbc6d1e629e0a7a47a359ee0
           IOKit: d5e3a75e6d1d1086eff8c961e9bb76f5
       IOKit.bak: 792596541652a8501da5b2fa6514c07b

---- ENDING MD5 HASH SUMS -------
```

Fails to patch...

**Comment by Floris497** [comment]
It looks like it is patched now? The MD5's are different.. Can you confirm it works when you patch with ```patch.command patch v6```

**Comment by nos1609** [comment]
It has no results...

**Comment by Floris497** [comment]
Seems like the code did change.. I had no time to test it today.. Maybe tomorrow, but i dont run beta software most of the time.
