### ISSUE TITLE
command not found and syntax error

### ISSUE THREAD

**Issue by grumpyoldbloke** [Floris497/mac-pixel-clock-patch-V2#64]
I get the following errors when I run IOKit-patcher.command on my 10.11.6 Hackintosh:

IOKit-patcher.command: line 1: {rtf1ansiansicpg1252cocoartf1404cocoasubrtf470: command not found
IOKit-patcher.command: line 2: syntax error near unexpected token `}'
IOKit-patcher.command: line 2: `{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}'

I'm all out of ideas so any help would be gratefully received.

**Comment by Floris497** [comment]
Did you download the raw file or the zip? Or did you download the html page?

**Comment by grumpyoldbloke** [comment]
I downloaded the html page

**Comment by grumpyoldbloke** [comment]
Just tried the zip which worked, thank you. Probably need more sleep before I start messing around nowadays.

**Comment by Floris497** [comment]
You are not the first one to do this.. i find github doesn't make this really clear either..

Enjoy
