### ISSUE TITLE
still cant setup resolutions over 165mhz in switchresx after patch

### ISSUE THREAD

**Issue by Ialf** [Floris497/mac-pixel-clock-patch-V2#7]
Hi,
I applied patch as necessary, but resolutions over 165mhz are still marked as "Not activated - invalid" in switchresx for me. I have 
MacBook Pro (Retina, 15-inch, Late 2013)
with NVIDIA GeForce GT 750M 2048 MB
OS version 10.11.3

This is md5 output
```
MacBook-Pro:mac-pixel-clock-patch-V2-master igoralferov$ ./IOKit-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.3 build:15D21

     otool IOKit: 422c441e207a011b355f712fc0ff7fba
 otool IOKit.bak: e70f3a302a6f87190e6d6fe7609cb4b5
           IOKit: 5c91441d636cb302ad09057e0e65b6b7
       IOKit.bak: 3cec8ae287ee52a3622082bfc049bb86

---- ENDING MD5 HASH SUMS -------
```
Could you help, please?

**Comment by Floris497** [comment]
Try if the nvidia patch works :)

**Comment by Ialf** [comment]
Floris, thanks, already installed NVIDIA patch:
MacBook-Pro:mac-pixel-clock-patch-V2-master igoralferov$ ./NVIDIA-patcher.command patch v2
SIP looks to be disabled, all good!
Keep SIP disabled, if enabled again SIP prevent the Nvidia Driver from loading
Patching NVDAGK100Hal with patch version 2
The code of the driver has changed, the patch was probbably succesfull
MacBook-Pro:mac-pixel-clock-patch-V2-master igoralferov$ 

But no success: 
https://gyazo.com/52fa65775a220a13bd3aa2f2c1242eb7

Also I installed nvidia web driver, but switching on that driver also dont help.

**Comment by Floris497** [comment]
I can look into it a bit later, and in a few hours

**Comment by Ialf** [comment]
Thank you! Tell me if you need some additional info

**Comment by Floris497** [comment]
Okay let's start at the beginning: 
Did this patch or the previous version ever work?
This patch does not support Nvidia WEB driver.. if i have time i'll add it!
What kind of cable do you use? any adapters?
What kind of connection does your display support? (HDMI1.4/2.0, DP1.1/1.2, DVI)

That is usefull information to have to solve this problem :)

**Comment by Ialf** [comment]
This is the first time I'm trying to set up connection to the TV (Sony x9005b) from my Mac. I have tried previous patch but with no luck too. TV should support hdmi 2.0, at least it is said in the Tv review. I use techlink Iwires cable to connect Mac Mini DisplayPort to TV HDMI port ( http://www.techlink.uk.com/products/wires_cables/iwires/iwires_mini_displayport_plug_to_hdmi_plug ). It should support 4K as I understand.

**Comment by Floris497** [comment]
TV should be fine cable should be fine, can you see if the drivers are loaded?
Open "System Information.app" scroll down to the software part and select extensions, let it load for 5/20 sec, then sort on "obtain from" you should see a the nvidia driver as unknown, click it and see if it is loaded properly.

**Comment by Ialf** [comment]
Ok, it shows me this info:

NVDAGK100Hal:

  Version:	10.8.14
  Last Modified:	18/12/15 08:09
  Bundle ID:	com.apple.nvidia.driver.NVDAGK100Hal
  Loaded:	Yes
  Get Info String:	NVDAGK100Hal 10.8.14 310.42.15f01
  Obtained from:	Unknown
  Kind:	Intel
  Architectures:	x86_64
  64-Bit (Intel):	Yes
  Location:	/System/Library/Extensions/NVDAGK100Hal.kext
  Kext Version:	10.0.8
  Load Address:	18446743521861900000
  Loadable:	No
  Signature Validation Errors:	Kext signature validation error code -67061
  Dependencies:	Satisfied
  Signed by:	Unknown

Is it ok?

**Comment by Ialf** [comment]
Maybe Kext signature validation error code -67061 looks like a problem?

**Comment by Floris497** [comment]
Nope that looks right, that error is expected, because we change the file the code signature is invalid.. The file is loaded. Can you download an app that forces dedicated graphics gfx.io can do that.

**Comment by Floris497** [comment]
It should work on the machine because it has dedicated graphics, but my 2013 MacBook does not play nice with 4k.. But my 2011 Mac mini does fine..

**Comment by Ialf** [comment]
I have chosen Discrete only in gfx.io. 
What I see in switchresx is that I can set resolutions with > 165Mhz pixel clock for internal LCD of MacBook, but resolutions with > 165Mhz for external TV is still not activated.

**Comment by Floris497** [comment]
So you get 4k@18Hz does work? If that is the case thene there is something wrong that is fixable! Doesn't matter if the tv can receive 18Hz good.. As long as your computer is sending it, it should be able to work.

**Comment by Floris497** [comment]
Do you have 2 TB ports? Sometimes it matters which has ne you use..

**Comment by Ialf** [comment]
Yes, I can switch to 4k@18Hz output, but TV displays that this signal is not supported. Accordingly to TV specs it supports 4k@24Hz, 25Hz, 30Hz video input, but it is not reachable now. I tried to use different HDMI ports of TV and TB ports on Mac, all have the same result. 
Maybe there is need to patch something else to enable >165Mhz pixel clock for TB video output?

**Comment by Ialf** [comment]
Tv spec https://www.sony.co.uk/support/en/content/cnt-specs/KD-55X9005B/list 
3840 x 2160/24p (HDMI 2/3)YES
3840 x 2160/25p (HDMI 2/3)YES
3840 x 2160/30p (HDMI 2/3)YES
4096 x 2160/24p (HDMI 2/3)YES

**Comment by Floris497** [comment]
I'm sure the TV supports it well.. did you try using a normal HDMI cable? does you mac have HDMI out?

**Comment by Ialf** [comment]
My mac have HDMI output but I have no HDMI2HDMI cable near me right now. I can get one on Monday and check.

**Comment by Floris497** [comment]
Your mac does support 4k@30Hz without any modifications over HDMI.. still weird it does not over your current cable.. Make sure you use either port 2 or 3 on your TV the cable should be well capable of 4k@30Hz.. some strange condition it seems, can't think it's not the cable at this point

**Comment by Ialf** [comment]
Thanks, Floris, I will try HDMI port on Monday, maybe it helps. Still I also dont understand the difference..

**Comment by Ialf** [comment]
I found HDMI cable and when I use it 4k@30 Hz is available and run perfectly. 
Still strange that TB2HDMI cable doesnt support it. Maybe this is due to my mac configuration.
I will change the cable for HDMI.
Thank you Floris for your help!

**Comment by Floris497** [comment]
I have no idea why.. Very strange.. good it is somewhat solved now :)
