### ISSUE TITLE
macOS Sierra - No signal after patch and reboot

### ISSUE THREAD

**Issue by Ruatilda** [Floris497/mac-pixel-clock-patch-V2#76]
Hello!

First of all, let me give you a deep appreciation for making things possible! Your hard work will not go unnoticed.

Now we are all tackling this as a team fighting with the new release! 

Here is a brief summary of my past tackles

1. Been using El Capitan after the IOkit patcher. Worked beautifully.

2. Updated macOS Sierra natively, installed fine, everything worked except the resolution went back to 1920x 1080.

3. Used CoreDisplay-patcher.command. (Used clover to boot SIP disabled.) 

4. No panic but black screen. Seems like no signal; it's not frozen.

5. Mac's Screen sharing not working since the mac is not logged in. Tried to log in blind (typed the password and return): no luck.

6. Clean installed. Repeated the patcher. No luck but "no signal."

7. Tried different flags; -s -x -nv_disable -nvda_drv etc. still nothing.

Seems so close, but still not working.

Help would be most welcome!

My rig:
I7-6700K
Asus Maximus VIII Hero Alpha
Nvidia Geforce 670
LG 29UM57-P

**Comment by Ruatilda** [comment]
Read the previous issues, and now I am trying to do the remote desktop trick.

**Comment by Floris497** [comment]
Delete all custom resolutions in switchresx before applying the patch. this could help.

**Comment by Ruatilda** [comment]
Thanks for the reply, Floris!

I didnt have or use switchresx to begin with. ;)

**Comment by Floris497** [comment]
try it, maybe you don't need the patch :)

**Comment by Ruatilda** [comment]
Ah it didnt work with EC on my rig but maybe it would for sierra. 

Be right back

**Comment by Ruatilda** [comment]
I don't know if it is me, but I can't make Switchresx working. I created a custom resolution, but nothing happens even if I click it. 

SIP is off. Went through the FAQ. Did a research if other people with the ultra wide monitor have the same issue. There are couple, but none is useful.

**Comment by Floris497** [comment]
Do they show active?

**Comment by Ruatilda** [comment]
I was researching on that as of speaking and how to make it active.

The status shows Not Installed.

**Comment by Floris497** [comment]
Save and reboot :)

**Comment by Ruatilda** [comment]
Sadly.. nope, it went into Kernal Panic + reboot.

I found another person's resolution data (front porch, sync width etc) of the same monitor who got it working with your patch (thank you) back on El Capitan.

So theoretically it must work, yet didn't. hmmmm. Now I'm starting to lost my morale here

**Comment by Floris497** [comment]
Hm.. i'm hearing more and more problems with nvidia and 10.12.. don't know when i have time to investigate..

**Comment by Ruatilda** [comment]
Thanks for trying tonight though anyway! I hope sooner or later people figure it out. 
I can always go back to EC and that is thanks to your work!

**Comment by rufabf** [comment]
I have the same issue, but my pc is a laptop and i can see trough laptop screen. The screen preferences doesn't work after the patch

**Comment by rufabf** [comment]
I resolve the screen preferences with this : http://www.insanelymac.com/forum/topic/304530-clover-change-explanations/page-2#entry2277736

**Comment by Ruatilda** [comment]
Which post are you refering to exactly, rufabf?

**Comment by rufabf** [comment]
The number 34, that it say about  the fake EDID

**Comment by rufabf** [comment]
Another thing i've seen is that after the patch decreased the performance. The videos are more laggy and windows are glitchy when i move them over the screen

**Comment by dockdude** [comment]
I had the same problem as OP and had to revert back to EC with the IOKit patcher on a SAMSUNG UN48JS9000 running GTX 760, which is natively support on OSX. What happened to me was it once rebooted, the signal was lost and the 4K TV didn't detect a signal. I tried to unpatch the CoreDisplay patcher | unpatch in Recovery Mode via Terminal, but the patcher complained "found no backup file", so I had to abort and restore my EC time machine backup. I did try SwitchResX in 10.12 with custom resolution of 3840x2160 @60Hz with no luck. Will keep an eye on this thread for updates. Thanks Floris for the patch, it worked wonderfully for me in EC at 3840x2160 @60Hz, but no so in Sierra.

**Comment by Ruatilda** [comment]
# Thanks to @dockdude for his inquiry, and super thanks to @Floris497 for giving it another try at this patch.

Floris' [Siera-nvidia-IOKit-test](https://github.com/Floris497/mac-pixel-clock-patch-V2/tree/Siera-nvidia-IOKit-test) worked on my system.

![screen shot 2016-09-29 at 3 42 21 pm](https://cloud.githubusercontent.com/assets/22405541/18969615/d35960c6-865b-11e6-919a-fb41fe023799.png)
![screen shot 2016-09-29 at 3 45 06 pm](https://cloud.githubusercontent.com/assets/22405541/18969614/d3571974-865b-11e6-9828-4c9c8da62fe0.png)

All I did was what dockdude did:

- Install Xcode from the terminal with `xcode-select --install` (for those who didn't)
- Disabled SIP with clover boot Rt-variables 
> To disable or enable SIP add the settings to your config.plist.
>Clover Configurator > Rt Variables > BooterConfig and CsrActiveConfig
>
>Relevant user options for SIP are as follows:
>csr-active-config 0x0 = SIP Enabled (Default)
>csr-active-config 0x3 = SIP Partially Disabled (Loads unsigned kexts)
>csr-active-config 0x67 = SIP Disabled completely
- use `chmod +x` to make the patches executable, and run first the new IOKit-patcher.command, then CoreDisplay-patcher.command.
- reboot
- BAM! all systems functional.


Thank you again, and godspeed! Let me know your paypal link too.

**Comment by Floris497** [comment]
Whaat it really works?? I just made an update to the CoreDisplay one! Need to
Push it to github

**Comment by Floris497** [comment]
Looks like the new new CoreDisplay is also not working.. when looking at the assembly i can clearly see it should be patched.. maybe this one fixes the not able to login issues. I'm loosing track of the issues.. there are too many :p hopefully I have some time too clean this a bit in the weekend :)

For PayPal there is 2 mail adresses on that page linked :)
