### ISSUE TITLE
macOS Sierra HD3000

### ISSUE THREAD

**Issue by JeyPay** [Floris497/mac-pixel-clock-patch-V2#77]
Hi, on El Capitan I used your patch to access to the resolution 2560x1080. It worked fine.
After updating to Sierra, I tried to re-patch my graphics drivers (with CoreDisplay this time) but it doesn't work. When patching, monitor preferences crash and when I want to reboot, I get stuck on the loading bar.
I reinstalled macOS and my MacBook Pro (early-2011) boot up.
Can you search where was the error in your patch ?
(Sorry for my bad English, I'm French :3)
Thanks in advance

**Comment by Floris497** [comment]
Whoops.. ehm.. do you have Nvidia card?

**Comment by JeyPay** [comment]
No, I have a 13" MacBook Pro and that's why I only have the Intel Chip

**Comment by Floris497** [comment]
Let me give it a look.. because something is going on.. the patch does not work very well for a lot of people. Apple changed quite some stuff in 10.12 I think..

**Comment by JeyPay** [comment]
Yes I saw (for the changements and the issues). I trust that you'll find a solution. Just give me (us) feedback :)

**Comment by hugoe8** [comment]
Oh mon dieu un Français ! Tu peux pas savoir comme je suis heureux, j'ai exactement à la lettre près le même problème que toi, je branche un 21:9 LG sur mon MacBook air, il a besoin de la résolution 2560x1040 mais mac ne propose pas, donc sur El Capitan j'avais fais ce patch et ça marchait parfaitement aucun soucis. Après l'update de Sierra, j'ai voulu repatch et en redémarrant je reste bloqué après avoir entré mon mot de passe, la barre de chargement se bloque ... Du coup comme tu dit le seul moyen c'est de réinstaller OSX , ça dure environ 2h30 et je l'ai déja fais 3 fois en voulant test le patch donc je désespère un peu ...

**Comment by Floris497** [comment]
It's not necessary to reinstall macOS/OS X you need to undo the patch from recovery. I will make a script to unpatch easily from recovery.. if you are a bit familiar with comand line. Replace the CoreDisplay file with Contents of CoreDisplay.bak
Using mv command.
