### ISSUE TITLE
Support for nvidia web drivers

### ISSUE THREAD

**Issue by rarens** [Floris497/mac-pixel-clock-patch-V2#8]
After I run the nvidia patch the md5's are the same.  
NVDAGK100HalWeb: c24068230334f93c43ddca619e4d95f9

I am running a newer maxwell card and need to use the alternate web drivers in order for it to work.  I opened the NVDAGK100HalWeb with a hex editor and there wasn't a pattern matching v1 or v2.  However, there is several _similar _  patterns.   Is it possible for me to alter the patch to work with the web drivers?  

Thanks.

**Comment by Floris497** [comment]
Yes.. But for maxwell and HDMI2.0 you only need IOKit patch :) as far as I know, if not, i will see if i can add the webdriver!

**Comment by Floris497** [comment]
The driver has a set value of 165 000 000Hz sometimes both signed and/or unsigned and in reverse (big/small endian notation) change it to 400Mhz or maybe 800Mhz but you don't need it :)
