### ISSUE TITLE
Mac Mini mid 2011 with dedicated AMD Graphics

### ISSUE THREAD

**Issue by Justen-GitHub** [Floris497/mac-pixel-clock-patch-V2#82]
Been trawling through to try an find whether I can lift the pixel clock restriction and achieve 4K@30 for this machine (I have 2 of these driving TVs). Is there a solution for this configuration?
[Mac Mini mid 2011 with dedicated AMD Graphics]

**Comment by Floris497** [comment]
Hm.. i don't have a patch for AMD at this moment.. but forcing integrated GPU and CoreDisplay/IOKit patch could work..

**Comment by Justen-GitHub** [comment]
Thanks for such a swift response!
Anyone else out there got this working?
Is so I'll buy an active adapter and give it a go....

**Comment by Justen-GitHub** [comment]
Does the Mini Mac 2011 with Radeon HD 6630M machine have integrated graphics as well (this doesn't seem to be documented anywhere on the usual sites?) - Cheers

**Comment by Floris497** [comment]
Yep, all i series (i3, i5, i7) CPU's have intel grapics..

**Comment by Justen-GitHub** [comment]
- Thanks for that.
I can choose my OS - currently on 10.8.5 but would rather go up a bit as browser support seems to have fallen off a cliff. Is there an optimal OSX version to maximise the chances of getting the 4K@30 working - what would you recommend? - Cheers.

**Comment by Floris497** [comment]
10.11.. 10.12 has some problems at the moment.. not for everyone but for some..

**Comment by Justen-GitHub** [comment]
Thank you very much for the advice & support

**Comment by mithrendal** [comment]
Did you made it work ?

**Comment by Justen-GitHub** [comment]
Thanks for asking – not yet – planning to do so when we get he 4K tv in October – currently the mini is feeding a 1080 Sony TV – have bought the active adapter in readiness though…

 

Best regards, Justen

**Comment by mithrendal** [comment]
I will try it out this weekend.

**Comment by Justen-GitHub** [comment]
Fantastic – could you let me know how it goes?

Good luck!

**Comment by Justen-GitHub** [comment]
Hi - now trying to do this but cannot find instructions on how to force my mid 2011 Mac Mini to use the integrated graphics - anyone know how I can do that?
-Cheers

**Comment by Floris497** [comment]
For external display that is not possible I think.. maybe this is working [gfxCardStatus](https://gfx.io)
