### ISSUE TITLE
new build of Sierra

### ISSUE THREAD

**Issue by pitichampi** [Floris497/mac-pixel-clock-patch-V2#86]
Hello. I've just updated my 10.11 to 10.12 with the latest release but CoreDisplay doesn't support my version and stops after the md5 check.

```
Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12 build:16A323

     otool CoreDisplay: 0a4be6cb6944fb6fcd262b967bac2ad2
 otool CoreDisplay.bak: 0a4be6cb6944fb6fcd262b967bac2ad2
           CoreDisplay: 9edc422aef8d53d1479eadba8b45aa07
       CoreDisplay.bak: 9edc422aef8d53d1479eadba8b45aa07

---- ENDING MD5 HASH SUMS -------
```

Could you add support for build 16A323 please ?

**Comment by Floris497** [comment]
Are you on the latest version of OS X 10.12? mine is: 16A313a are you on a beta?

**Comment by pitichampi** [comment]
It's not a beta. I've just updated it today from the App Store.

**Comment by Floris497** [comment]
Interesting thing is that you do have a backup file.. did you try to unpatch?

**Comment by pitichampi** [comment]
I was on 1.11 with IOKit.
After upgrading to 1.12, the patch was lost. I went on your GIT and saw I had to use CoreDisplay.
I started it and had an error message. So, before trying anything else, I've tried to unlatch IOKit but I've got this message : "There is no backup file, we can not undo the patch. the patch might not even been done."
After looking further on the error of CoreDisplay Patch, I've noticed that xcrun tools were missing so I reinstalled them.
Then I restarted the patch and I had the MD5 checksum error.

**Comment by Floris497** [comment]
Please force the v2 patch see in the something like `CoreDisplay.command patch v2` see if that works. it will give you a warning that you will be overwriting the backup.. this is fine because the backup is identical to the current running file.

**Comment by pitichampi** [comment]
v2 doesn't seem to work.

_./CoreDisplay-patcher.command patch v2
An backup file already exists, if you force this patch on an already patched version you will loose the original backup!
This will lead you to reinstall the OS if you loose a working version of CoreDisplay. be carefull
It might be wise to undo the patch before trying to redo it using: ./CoreDisplay-patcher.command unpatch
Do you want to continue? [Y/n] y
SIP looks to be disabled, all good!
This patch does not exist, make sure you used the right patch identfier_

I tried with v1 to v6 and the only one that made something different was v1. 
_./CoreDisplay-patcher.command patch v1
An backup file already exists, if you force this patch on an already patched version you will loose the original backup!
This will lead you to reinstall the OS if you loose a working version of CoreDisplay. be carefull
It might be wise to undo the patch before trying to redo it using: ./CoreDisplay-patcher.command unpatch
Do you want to continue? [Y/n] y
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 1
Password:
Re-singing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
The code is still the same.. Patch did seem to run, but was probbably from the wrong version..
If you are running an new os run ./CoreDisplay-patcher.command md5 and ask the maintainer of this script to add support for your system_

**Comment by Floris497** [comment]
Oh wait.. I already see what is going on.. You have a patched file there.. both backup and active file are patched.. the only thing you can do now is reinstall macOS.. :/

**Comment by pitichampi** [comment]
Holly crap.
So I have to reinstall by rescuing the system with cmd-r you think ? I hope this will be enough to get the unpatched file back.

**Comment by Floris497** [comment]
Let me see.. send me an email, maybe I can help you there ;)

**Comment by qvt** [comment]
Had the same problem, both the driver and the backup were patched. Luckily I could copy that file from my MacbookPro over to my MacMini. Perhaps you know someone with a clean installation of 16A323. Next time I'm going to save the file manually before applying the patch :)

**Comment by Floris497** [comment]
Was there no backup file? In the same directory as CoreDisplay there is a CoreDisplay.bak file.. although for some reason it can go wrong sometimes. I tried to build some security into the script to prevent this from happening.. but there is still a case where it can happen..

**Comment by qvt** [comment]
Backup file was there , but had the same hash as printed out by the patcher command, and didn't restore the corrupt driver. I somehow managed to patch twice :)

**Comment by pitichampi** [comment]
Didn't see that this issue was still open... Fixed a long long time ago (in a galaxy far far away...)
