### ISSUE TITLE
CoreDisplay-patcher doesn't work on 10.12.1

### ISSUE THREAD

**Issue by XWhatevs** [Floris497/mac-pixel-clock-patch-V2#91]
```
SIP looks to be disabled, all good!

Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.1 build:16B2555

     otool CoreDisplay: 172b7e2fe2e45e99b078e69684dd3c10
 otool CoreDisplay.bak: aa7607dd72a2a4ca70ce094a2fc39cce
           CoreDisplay: b38bbe5c6fbde7892e3ee8af78737d50
       CoreDisplay.bak: eb27b5d68e9fb15aa65ea0153637eae2

---- ENDING MD5 HASH SUMS -------
```

Doesn't seem to work on the latest 10.12.1 update. SIP Disabled, using HD530.

**Comment by Floris497** [comment]
Let me check tomorrow morning :)

Did you already run something? Or is that the old backup still in place?

**Comment by XWhatevs** [comment]
Backup of what? I just ran the patch after updating to 10.12.1 because the update removed the patch I already had installed. Oh and thanks for the quick response 👍.

**Comment by Floris497** [comment]
It looks like it didn't run, but the opd bavkup from previous systems was maybe there. Will check this.

**Comment by Floris497** [comment]
Yep, that's the old one. Just force the patch as described in the readme :) don't worry about overwriting ONCE. As long as your backup or current file is 172b7e2fe2e45e99b078e69684dd3c10 you are good. In this state DON'T unpatch, as it will write back the old (10.12.0) version of the file :)

**Comment by XWhatevs** [comment]
Do I force with `v6` or.. ?

**Comment by Floris497** [comment]
Yep, think that's the latest one. Maybe 7.. look in the script :) don't remember ;p

**Comment by XWhatevs** [comment]
Doing `./path_to_patcher patch v6` leads to: 

```
An backup file already exists, if you force this patch on an already patched version you will loose the original backup!
This will lead you to reinstall the OS if you loose a working version of CoreDisplay. be carefull
It might be wise to undo the patch before trying to redo it using: /Users/bogdan/Downloads/CoreDisplay-patcher.command unpatch
Do you want to continue? [Y/n] y
SIP looks to be disabled, all good!
This patch does not exist, make sure you used the right patch identfier
```

**Comment by OrcaXS** [comment]
According to the code it seems only v1 patch is available for CoreDisplay-Patcher.
So I tried `$ ./CoreDisplay-patcher.command patch v1` on 10.12.1:
```
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 1
Password:
Re-singing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
The code is still the same.. Patch did seem to run, but was probbably from the wrong version..
If you are running an new os run CoreDisplay-patcher.command md5 and ask the maintainer of this script to add support for your system
```
And the md5s are:
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.1 build:16B2555

     otool CoreDisplay: 172b7e2fe2e45e99b078e69684dd3c10
 otool CoreDisplay.bak: 172b7e2fe2e45e99b078e69684dd3c10
           CoreDisplay: 93dda7203e59c2405ee3770f08b56453
       CoreDisplay.bak: b38bbe5c6fbde7892e3ee8af78737d50

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment]
Whoops.. yep, had IOKit in mind. For CoreDisplay it is only 1 and it looks like it's not working. Will have a look after work, and after updating :)

**Comment by hpcarlos** [comment]
Hello, I have the same problem to have updated to version 10.12.1, have any estimate of when we can update the patch for this version?

**Comment by Floris497** [comment]
It's currently 16:20 I will be home around 19:00 will have some food, after this it can be between 10min and 10days depending on the changes.. :)

**Comment by hpcarlos** [comment]
Thank you, I'll be here watching, still want to learn a little of that to be able to help the community :)

**Comment by XWhatevs** [comment]
Alright, thanks!!

**Comment by f0ntana** [comment]
it's my problem to. =/

**Comment by Floris497** [comment]
I've got something, no idea if it is working... can't test it here. please be advised that you might need to undo the patch in single user mode. and please backup you system before trying :)

use the patch from this branch: https://github.com/Floris497/mac-pixel-clock-patch-V2/tree/10.12.1-tests

**Comment by hpcarlos** [comment]
I'll test so my friend get here in the office and say if it worked ok!

**Comment by f0ntana** [comment]
Hey it's work here thanks a lot!

**Comment by f0ntana** [comment]
![screen shot 2016-10-25 at 16 42 33](https://cloud.githubusercontent.com/assets/6570783/19701507/15977862-9ad2-11e6-899b-5778f922e53c.png)

**Comment by LETRA** [comment]
It seems to work perfectly. Billions of thanks @Floris497 :-)

**Comment by Floris497** [comment]
Awsome, anyone got 4k working with it already? after that is confirmed to be working I'll put the update the that master branch

**Comment by LETRA** [comment]
btw this useful program "easyres" now free for osx https://itunes.apple.com/es/app/easyres/id688211836?mt=12

**Comment by Floris497** [comment]
4k? @XWhatevs

**Comment by vanekgsa** [comment]
Seems like it doesn't support 4k, i can have only 1080p on patched but up to 3360x2100 on unpatched
rMBP 2012 13" (HD4000)

**Comment by XWhatevs** [comment]
Don't know about 4k (I don't have a 4k monitor), I used it to get 2560x1080 working.

**Comment by f0ntana** [comment]
Work perfect, i had 4k

2016-10-25 16:48 GMT-03:00 Floris Fredrikze <notifications@github.com>:

**Comment by f0ntana** [comment]
For me dont work

Em terça-feira, 25 de outubro de 2016, Carlos Antônio <
notifications@github.com> escreveu:

**Comment by Floris497** [comment]
@f0ntana so does it work for 4k or not? haha.. unfortunately I can't test it myself either 😞

**Comment by f0ntana** [comment]
Works i didn't, but i had to reconfig switchres

**Comment by Floris497** [comment]
Super! Thanks for confirming!

**Comment by hpcarlos** [comment]
is perfect, fix the problem of my friend, thank you.

**Comment by legotheboss** [comment]
Can confirm, works for Late 2012 Mac Mini. Thanks @Floris497!

**Comment by rodolfoleo** [comment]
Confirmed working  for Sierra 10.12.1 on a Mini 2012 by running the command: 

`$ ./CoreDisplay-patcher.command patch v2`

Thanks so much :D

**Comment by pitichampi** [comment]
Everything works perfect with the test branch :)

**Comment by Floris497** [comment]
It's in the master branch as well now :)

**Comment by sebastianwebber** [comment]
To fix the update issue , run the steps bellow:

1. update the `CoreDisplay-patcher.command` script.
1. unpatch:

    ```bash
    ./CoreDisplay-patcher.command unpatch
    ```
1. apply the patch again:

    ```bash
    ./CoreDisplay-patcher.command patch
    ```
1. then reboot.

Thanks so much @Floris497 !

**Comment by diafebus** [comment]
I was having problems with the previous version for 10.12.1 but the test version is working again just fine! Thanks for this great work!

**Comment by Floris497** [comment]
Whoops.. I didn't merge correctly. Now the new code is in the master branch!
