### ISSUE TITLE
MacOS El Capitan 15G1108 & new MD5

### ISSUE THREAD

**Issue by maleorderbride** [Floris497/mac-pixel-clock-patch-V2#94]
Hello Florian,

Thank you for maintaining this utility!

There is a new Security Update & matching Nvidia driver out for 10.11.6. Can you please add it?

bash-3.2# ./NVIDIA-patcher.command md5
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.6 build:15G1108

     NVDAGK100Hal: 93bc574ecbef134a62400e21811b1b7b
 NVDAGK100Hal.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Does it work?
