### ISSUE TITLE
Seems doesn't work on Mac Mini(Late 2012) version: 10.12.1 build:16B2555

### ISSUE THREAD

**Issue by iAstro** [Floris497/mac-pixel-clock-patch-V2#99]
Seems doesn't work on Mac Mini(Late 2012) version: 10.12.1 build:16B2555.

SIP looks to be disabled, all good!

Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.1 build:16B2555

```
 otool CoreDisplay: 127c930ff200a296e8d890c43863dbb2
```

 otool CoreDisplay.bak: 4cba52b41ceee7bc658020c9e58780a3
           CoreDisplay: b38bbe5c6fbde7892e3ee8af78737d50
       CoreDisplay.bak: eb27b5d68e9fb15aa65ea0153637eae2

---- ENDING MD5 HASH SUMS -------

I used it well on version 10.12 before. Please help to check, thank you!

**Comment by qvt** [comment]
This latest version of the CoreDisplay patch works on my MacMini Late 2012 with Intel HD Graphics 4000 under macOS 10.12.1.

**Comment by Floris497** [comment]
@iAstro I do not recognise your signature.. the backup one is from one is from one of 10.12 versions. and it looks like your OS version is the same as mine.. I would advice to uninstall SwitchResX reinstall macOS then patch and then install SwitchResX again.

**Comment by iAstro** [comment]
Got it, I will try, thank you @Floris497.

**Comment by fsseven** [comment]
I have the same md5 with @iAstro , and my macbook is MacBook Pro(also is Late 2012). So maybe there' s some other reason failed to install the patch?

**Comment by fsseven** [comment]
I'm sorry, I have made a mistake. I was using the old patcher when I got the error. Now I use the latest patcher which supports the new macOS(10.12.1). It works perfect now. Thank you.

**Comment by iAstro** [comment]
It works after reinstall the OS with 10.12.3, thank you!
